### ISSUE TITLE
workDir is not the current working directory of the process

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#10]
In my ScalaTask, I use a configuration file in the current working directory of the OpenMOLE console. I specify it as ```resources += "repeat.conf"``` of the ScalaTask so it is copied to the remote machine. What I had not expected was that the resources and input files for my task are not in the current working directory, but in ```workDir```. Now that I know of the existence of this variable, I can make use of it. However, I was wondering if it is for a reason that the current working directory of the process is not the actual ```workDir``` where the input and output of the process should go ? And any chance this could be changed ?

```
user.dir: /vol/medic01/users/as12312/OpenMOLE/.tmp/ssh/5255b992-aae3-4fa6-8dce-a56079207f3d_install/runtime7b6c5f95399e3f3bdee2280685d10188746e595d
workDir:  /homes/as12312/.openmole/.tmp/ssh/5255b992-aae3-4fa6-8dce-a56079207f3d/tmp/1428619263637/184981b6-c860-4e81-8447-2f00945c99aa/6ea4b403-e234-44d2-9ff9-e91595ef02a9/.tmp/13b5c1f1-3490-4440-b60c-de069b754fee/category7dd502bf-af7e-46d2-b510-5b3b79dda85c
Found configuration file: /homes/as12312/.openmole/.tmp/ssh/5255b992-aae3-4fa6-8dce-a56079207f3d/tmp/1428619263637/184981b6-c860-4e81-8447-2f00945c99aa/6ea4b403-e234-44d2-9ff9-e91595ef02a9/.tmp/13b5c1f1-3490-4440-b60c-de069b754fee/category7dd502bf-af7e-46d2-b510-5b3b79dda85c/repeat.conf
```

(Note: /homes/as12312/.openmole is a symbolic link to /vol/medic01/users/as12312/OpenMOLE)

**Comment by romainreuillon** [comment]
This is the expected behaviour since each task execution should have its own workdir for isolation and since the user.dir is common to the all JVM.

**Comment by schuhschuh** [comment]
Alright then, I can work with ```workDir```.

**Comment by schuhschuh** [comment]
What **is** confusing though that the ```addResources``` method as default argument ```inWorkDir = false``` whereas ```addInputFile``` and ```addOutputFile``` have default value ```inWorkDir = true```. Still, all of these files end up in the ```workDir```.

```scala
/**
   * Copy a file from your computer in the workspace of the task
   *
   * @param file the file or directory to copy in the task workspace
   * @param name the destination name of the file in the task workspace, by
   * default it is the same as the original file name
   * @param link tels if the entire content of the file should be copied or
   * if a symbolic link is suitable. In the case link is set to true openmole will
   * try to use a symbolic link if available on your system.
   *
   */
  def addResource(file: File, name: Option[ExpandedString] = None, link: Boolean = false, inWorkDir: Boolean = false, os: OS = OS()): ExternalTaskBuilder.this.type = {
    _resources += Resource(file, name.getOrElse(file.getName), link, inWorkDir, os)
    this
  }
```
If I could use the ```inWorkDir``` parameter to specify whether I want the configuration file (resource) to be copied to either ```user.dir``` (i.e., process working directory, prefix "runtime") or ```workDir```, I could just set ```inWorkDir = false``` and wouldn't need to make other changes.

**Comment by schuhschuh** [comment]
I found some source code in OpenMOLE from which I can deduce the meaning of ```inWorkDir``` now. If ```true```, the files are copied to the ```workDir```, otherwise the ```tmpDir``` (wherever it is).

After modifying my plugin to read the configuration file from ```workDir```, it is working fine.
