### ISSUE TITLE
Total CPU Time

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#100]
Display a total CPU Time counter at the mole execution level.

**Comment by romainreuillon** [comment]
https://github.com/openmole/openmole/blob/master/openmole/gui/server/org.openmole.gui.server.core/src/main/scala/org/openmole/gui/server/core/Runnings.scala#L74

**Comment by mathieuleclaire** [comment]
030ecc5b69787d131fa937056777cbeb579be762 implements it
