### ISSUE TITLE
Catch CTRL-s in WebUI

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#101]
And make it save the current file instead of the browser's default action that tries to saves the page as html...

**Comment by romainreuillon** [comment]
Do you think it is possible to do so in JS?

**Comment by jopasserat** [comment]
I don't know i just noticed that's what happens in notebooks ;)

**Comment by jopasserat** [comment]
Actually it seems doable http://stackoverflow.com/a/93836/470341

**Comment by romainreuillon** [comment]
I think the correct behaviour would be to force the script saving on ctlr S.

**Comment by mathieuleclaire** [comment]
ed666ece87b547e7f5bd582ccbad7fc20e148755 fixes it. The Ctrl-S event is catched and mapped with nothing. The editor contents are saved automatically. The Ctrl-S event cathes is made in a more global scale.
