### ISSUE TITLE
Table view for CSV

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#105]
Being able to switch to a table view with sorting feature for CSV files in the editor would be great.

**Comment by romainreuillon** [comment]
FYI large CSV tables go beyond the frame:
![image](https://user-images.githubusercontent.com/1270995/38764782-b9511b0a-3fb5-11e8-94d5-d2943b307cdb.png)

**Comment by mathieuleclaire** [comment]
fd67995112c8da26780cfb42743ea95cef410649 should fix it
