### ISSUE TITLE
UI : add parent directory icon/link

### ISSUE THREAD

**Issue by RCura** [openmole/openmole#109]
Hi,
I think it would be usefull to have a parent folder link in the UI. It's currently like this :
![capture du 2015-09-10 15 10 32](https://cloud.githubusercontent.com/assets/807703/9789129/6b4576bc-57ce-11e5-9480-a1ee09f6f724.png)

And could be like this :
![capture du 2015-09-10 15 10 32 copie](https://cloud.githubusercontent.com/assets/807703/9789633/8e7f404c-57d1-11e5-8af2-5ef59f6bd5ca.png)

The reason is that it is quite troubling to have the "navigation path" at the top of the menu

**Comment by mathieuleclaire** [comment]
I am not fully convinced of this proposal, cause it is redundant with the top navigation. However, I will give a try in the version 6.

**Comment by RCura** [comment]
Well, then, maybe, just switch the positions of the Edit menu (File, upload etc.) and of the breadcrumbs (path) ?

**Comment by jopasserat** [comment]
I agree with @mathieuleclaire  on this one

**Comment by mathieuleclaire** [comment]
What do you think of this ?
![capture](https://cloud.githubusercontent.com/assets/800035/9791037/7a111f4c-57d9-11e5-8125-f9ad0be0375f.png)

**Comment by RCura** [comment]
Way better in my opinion :) The first time I used the RC1, I did really struggle for 30-40 seconds to understand how to go up ^^

**Comment by mathieuleclaire** [comment]
It is because it is a very forward-thinking UI :). No objection @jopasserat , @romainreuillon  ?

**Comment by romainreuillon** [comment]
That's good, may be there could be less space between the directory hierarchy and the files, and the transfer bar could be interleaved inbetween the creation bar and the directory hierarchy.

**Comment by mathieuleclaire** [comment]
The large space between the file bar and the files is essentially dedicated to an extra line for the top line. It occurs when the folder names are long.

**Comment by mathieuleclaire** [comment]
But actually, you are right; it is doable to reduce of a third:
![capture](https://cloud.githubusercontent.com/assets/800035/9791768/094e5c76-57dd-11e5-8b8d-41f8954bacf8.png)

**Comment by mathieuleclaire** [comment]
59ebe7952e61c9bcc2947bd7ffbe387ddb9c2fcd fixes it
