### ISSUE TITLE
UI : add notification/alert on task completed

### ISSUE THREAD

**Issue by RCura** [openmole/openmole#110]
It would be pretty nice and usefull to have an alert (could use the alert class of bootstrap so it's pretty) when a OM task is finished, in the main environment (and not only in the Execution box).

This would display a non modal notification at the top of the window.

**Comment by mathieuleclaire** [comment]
Good idea, it is in the refinement list of the version 6.

**Comment by romainreuillon** [comment]
https://github.com/openmole/openmole/blob/master/openmole/gui/server/org.openmole.gui.server.core/src/main/scala/org/openmole/gui/server/core/Runnings.scala#L74
