### ISSUE TITLE
UI :  Allow the user to see the path of its projects

### ISSUE THREAD

**Issue by RCura** [openmole/openmole#111]
When downloading/creating a new project, a folder is created and used in OM without telling the user where it is. When producing a lot of data, it's awful to have to download the data through the UI, especially considering it's already locally on the computer.

I don't know what it could look like, but it would be nice to give to the user the path of those files. Maybe with a new icon next to the folder/file name (next to download/rename/delete) ?

The best thing would be to propose to the user to open this folder inside his default explorer, but it's not really possible in the browser. It could maybe be done from the running program (server), although I'm not sure it's possible either.

**Comment by jopasserat** [comment]
I think it would just translate as a way to choose the workDirectory basically

**Comment by mathieuleclaire** [comment]
You can download the folder containing the files. You will get it as an archive. Did you try to download a whole folder ?

**Comment by romainreuillon** [comment]
@jopasserat You can do that, just write: ```val workDirectory = File("/tmp/test/")``` at the begining of your script.

**Comment by RCura** [comment]
@mathieuleclaire Sure I did, it's just kind of strange to propose to the user to download a gzipped folder that's already somewhere else, unzipped, in the computer :)

**Comment by mathieuleclaire** [comment]
As strange as uploading a file that's already somewhere else  :). In this version, in general, both client and server run locally, but it is not supposed to be the case in general. In 2 versions, the server could be installed on a dedicated machine, so that downloads and uploads won't sound that strange.

**Comment by jopasserat** [comment]
@romainreuillon  Yeah sure, but to fit @RCura's needs, it might be cool to have that through the WebUI and be able to read it / set it?

**Comment by romainreuillon** [comment]
From my point of view this is really specific and you can very easily use another variable.

**Comment by jopasserat** [comment]
I guess we can close that one then.
