### ISSUE TITLE
Market display is messed up

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#117]
In the master version the market doesn't display properly.

**Comment by JusteRaimbault** [comment]
I have display problems for marketplace ; version 5.0 from http://www.openmole.org/current/openmole-5.0.tar.gz ; web browser Chrome 45 on OSX10.10.

![capture d ecran 2015-09-22 a 17 12 45](https://cloud.githubusercontent.com/assets/3902759/10022625/21d8b1cc-614e-11e5-813a-623a718d95b6.png)

**Comment by mathieuleclaire** [comment]
9fe23b0d7a12c3202632850bb66f3aeab032e6c7 fixes it. A 5-1 will be published at the end of the week with this patch.
