### ISSUE TITLE
Auto-extract more archives

### ISSUE THREAD

**Issue by RCura** [openmole/openmole#118]
Currently, openmole master only extracts the tar.gz once renamed into .tgz

Having the full unzip support would be usefull :)

**Comment by mathieuleclaire** [comment]
Do you mean you need some zip extension ?

**Comment by mathieuleclaire** [comment]
The tar.gz files were actually not extractable. 533a1e5892120dfaf25d907c39f01a1a0f0be8aa fixes it

**Comment by RCura** [comment]
That's what I meant, thanks :) I added a note in the commit to read/write more file types : *.nls (netlogo) and *.gaml (Gama)

**Comment by mathieuleclaire** [comment]
OK, what is the difference between .nlogo and .nls ?
In 5.1, we will support tar.gz but not .zip.

**Comment by RCura** [comment]
.nlogo is the main model file, but it can import other model files when they are in .nls file
It's the only way to have a file-based organisation of a model, as one can not include a .nlogo

See here : http://ccl.northwestern.edu/netlogo/docs/interface.html#includes

**Comment by mathieuleclaire** [comment]
fe3fc34279429a68c1a32fd9ea4bb424037cde55 fixes it.

**Comment by mathieuleclaire** [comment]
To do: the implementation of the zip archives.
