### ISSUE TITLE
Command arguments for openmole batch execution

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#12]
Is it possible to pass command arguments to OpenMOLE scripts when run in batch mode ? Using [com.typesafe.config](https://github.com/typesafehub/config) package works well for settings read from a .config file, but I would prefer the ability to pass some settings via an openmole command argument. This would allow me to write a wrapper Bash or Windows Command script with some options the user can choose from which influence the workflow execution.

For example as System properties, which doesn't seem to be possible right now:
```
> openmole -c -s Workflow.scala -Dworkflow.message
Apr 10, 2015 12:12:37 PM org.openmole.ui.Application start
WARNING: Ignored options: -Dworkflow.message

```

An alternative that is already working is to use environment variables:
```
> workflow_message=hello openmole -c -s Workflow.scala 
```
I would favour the ```-D``` system properties which would also override the .config file values.

Workflow.scala:
```scala
val msg1 = System.getProperty("workflow.message", "Got nothing to say")
val msg2 = sys.env.get("workflow_message") match {
  case Some(msg) => msg
  case None => "Got nothing to say"
}
```

**Comment by romainreuillon** [comment]
You can now use the --args option of the command line to pass arguments to the console. You may then refer to you arguments in the console using:
```args(0)``` for the first one.

**Comment by schuhschuh** [comment]
Would you also consider allowing ```--``` to have OpenMOLE pass everything following it on to the script ? This would allow also option syntax for script arguments. It is also quite common to have commands separate their own arguments/options (openmole) from the arguments of the wrapped command (i.e., OpenMOLE script) using ```--```. At least on UNIX (e.g., see [bash man page](http://linux.die.net/man/1/bash)).

The desired usage would look as follows (including possibly some logic in the Bash script to stop parsing when ```--``` is encountered in order to not drop ```-mem```):
```shell
> ./argstest.sh -mem 3 -- a b -mem 2 --logger-level FINE
args: ("a" "b" "-mem" "2" "--logger-level" "FINE")

> ./argstest.sh -mem 3 --args a b -mem 2 --logger-level FINE
args: ("a" "b")
```

The idea behind this is that using ```--```, everything following it will be in the ```args``` list of the OpenMOLE script and not considered by the openmole application.

**Comment by romainreuillon** [comment]
I think this would impact only the bash script, would you give it a try of implementing this?

**Comment by schuhschuh** [comment]
I actually did before posting. But then I realised that even when I rearrange the arguments, the OpenMOLE application will still not obey this. Here the Bash code I wrote:

```bash
SCRIPT_ARGS=()
scriptArgs()
{
  while [ 0 ]; do
    shift
    [ $# -gt 0 ] || break
    case "$1" in
      --*) break ;;
      *) SCRIPT_ARGS+=("$1") ;;
    esac
  done
  return ${#SCRIPT_ARGS[@]}
}

ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --) shift; break ;;
    --args) scriptArgs "$@"; shift $? ;;
    -mem) shift; MEM=$1 ;;
    *) ARGS+=("$1") ;;
  esac
  shift
done
SCRIPT_ARGS+=("$@")

[ ${#SCRIPT_ARGS[@]} -eq 0 ] || ARGS+=(--args "${SCRIPT_ARGS[@]}")

echo -n "ARGS: ("
i=0
while [ $i -lt ${#ARGS[@]} ]; do
  [ $i -eq 0 ] || echo -n " "
  echo -n "\"${ARGS[$i]}\""
  let i++
done
echo ")"
```

**Comment by schuhschuh** [comment]
I believe there must be a case for ```"--"``` added [here](https://github.com/openmole/openmole/blob/2227541037705d016c76451b404f4da4fd2b7b66/openmole/bin/org.openmole.ui/src/main/scala/org/openmole/ui/Application.scala#L107), something like

```scala
case "--" :: tail  ⇒ parse(dropAllArgs(tail), c.copy(args = takeArgs(tail)))
```

(I am sure there's a better way for the following)
```scala
def dropAllArgs(args: List[String]) = args.dropWhile(false)
```

**Comment by schuhschuh** [comment]
> I think this would impact only the bash script, would you give it a try of implementing this?

I'd give it a try and send a pull request then.

**Comment by romainreuillon** [comment]
:) I implemented it based on your bash script, I am testing it.

**Comment by schuhschuh** [comment]
;)

**Comment by romainreuillon** [comment]
I got rid of the --args and all the args after -- are passed to the console.

**Comment by romainreuillon** [comment]
(It has been pushed)

**Comment by schuhschuh** [comment]
Thanks!

**Comment by schuhschuh** [comment]
Just wondering if [this line](https://github.com/openmole/openmole/commit/dc493c7810b69a53c7e6bda6130f7cb06cbfd3a4#diff-dc2c6bbfa5e9eb5b557bd61f2a4e2443R50) was committed by mistake.
