### ISSUE TITLE
Uploading an already existing plugin should replace it

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#126]
When uploading a already existing plugin the old version is not unloaded. This case should be taken into account.

**Comment by mathieuleclaire** [comment]
I can't see any unload method in the PluginManager file. What to achieve the unload ?

**Comment by romainreuillon** [comment]
The plugin removal process is implemented in APIImpl.

**Comment by mathieuleclaire** [comment]
When an already loaded plugin is loaded again, an error message is displayed: ba02a9d5191bbdad181694e107719b1770369536
