### ISSUE TITLE
SBT out of memory with default compilation of OpenMOLE

### ISSUE THREAD

**Issue by reyman** [openmole/openmole#127]
Hi,
I have some problem to compile OpenMOLE on my pc with default option in sbt. 

With memory option by default, `sbt assemble` generate a `java.lang.OutOfMemoryError: GC Overhead limit exceeded`

Can you please add some compilation option for sbt with correct memory option into the project folder ? 

 A `.sbtopts` file at the root of openmole project, with this command, can probably help : 

```-J-Xmx4G
-XX:MaxPermSize=2G
-J-XX:+UseConcMarkSweepGC
-J-XX:+CMSClassUnloadingEnabled
-J-Xss2M -Duser.timezone=GMT
```

**Comment by romainreuillon** [comment]
I totally agree to add some option on sbt but those one seem outdated. For instance: `-XX:MaxPermSize=2G` is a java 7 option only isn't it?

**Comment by jopasserat** [comment]
@romainreuillon yes it is. Legacy options such as `-XX:MaxPermSize` are now ignored by the JVM in favour of `-XX:MaxMetaspaceSize`. But there's no need to set that one in our case as it's unlimited by default.
