### ISSUE TITLE
Replace GZIP by LZF

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#129]
At the moment we rely on the JDK's `java.util.zip.{ GZIPOutputStream, GZIPInputStream }` to transfer files.

GZip is now dramatically outperformed by other algorithms. One of them is LZF.
Benchmarks comparing the 2 are available here: https://github.com/ning/jvm-compressor-benchmark/wiki

A Java implementation of LZF is available here: https://github.com/ning/compress/

The API is pretty similar to the `GZIP`'s, so it should be quite straightforward to implement the change.

**Comment by romainreuillon** [comment]
Some files are then extracted using gzip in command line which is widely deployed on linux. It would be possible to have several compression algorithms for different files but it would complexify the design for a little CPU and bandwidth gain. I not sure these optimisation worth it for now. What do you think?

**Comment by jopasserat** [comment]
Fair point. So apart if there're some that are compressed/uncompressed by the app from end to end it's not worth it.
