### ISSUE TITLE
Option to skip execution, new otherwise keyword, and/or new SwitchCapsule

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#13]
Motivation
----

A lot of the difficulties in the past days were to find a proper way of setting up an OpenMOLE pipeline where a task is only executed (and thus submitted to the cluster/grid batch queuing system) when an output file is either non-existend or outdated (e.g. comparing modified date of input and output files). Otherwise, the task should just be skipped but the following task still be executed as it will consume this already present file as input. To achieve this, we (i.e., mainly @romainreuillon and @jopasserat, thanks a lot!) finally came up with something illustrated by the following toy example:

```scala
val i = Val[Int]
val f = Val[File]
val e = ExplorationTask(i in (1 to 10))

val template = "/path/to/file${i}"
val begin = EmptyTask() set(inputs += i, outputs += (i, f)) source FileSource(template, f)
val task = ScalaTask("val f = newFile; // write to file f") set(inputs += i) hook CopyFileHook(f, template)
val end = StrainerCapsule(EmptyTask())
val cond = "!f.exists()"
val mole = begin -- ((task -- end) when cond, end when s"!($cond)")

val others = StrainerCapsule(EmptyTask()) hook ToStringHook()
val ex = (e -< mole) + (end -- others) start
```

Here, the ```begin``` task simply introduces a ```File``` variable with the path of the output file to be generated by ```task``` using a FileSource. It is needed for the condition ```cond``` which determines whether the file has to be (re-)generated. Further, if the task is not executed because the file exists and is up-to-date, this file variable contains the path of the already existing file which is input for the following task (passed through by the ```end``` StrainerCapsule).

At first, I would have used the following instead to just place a condition on the task:
```scala
val i = Val[Int]
val f = Val[File]
val e = ExplorationTask(i in (1 to 10))

val template = "/path/to/file${i}"
val begin = EmptyTask() set(inputs += i, outputs += (i, f)) source FileSource(template, f)
val task = ScalaTask("val f = newFile; // write to file f") set(inputs += i) hook CopyFileHook(f, template)

val others = StrainerCapsule(EmptyTask()) hook ToStringHook()
val ex = e -< begin -- (task when "!f.exists()") -- others start
```

The problem with this is that all following tasks are never executed if the condition on ```task``` is false because the outputs of the task are not traveling along the transition to the inputs of the following task(s).

I think the OpenMOLE DSL would benefit from either one or more of the following enhancements.

Alternative 1: Adding an argument to ```when```
-----

A Boolean argument on the condition could let users specify whether the task should simply act as if it was a ```StrainerCapsule(EmptyTask())``` in case of the condition being false. Otherwise, it would just behave as it does at the moment, i.e.:
```scala
val ex = e -< begin -- (task when ("!f.exists()", skip=true)) -- others start
```
Instead of a Boolean argument, it could also be an enumeration value which would allow adding more possibilities later on if needed
```scala
val ex = e -< begin -- (task when ("!f.exists()", SKIP_TASK)) -- others start
```
In fact, given this notation, I would even negate the condition here and have the second argument indicate the action in case the condition is *true* rather than *false* because then it would read as:
```scala
val ex = e -< begin -- (task when ("f.exists()", SKIP_TASK)) -- others start
```
In that case, the default ```action``` argument would be something like ```EXEC_TASK``` which also maintains backward compatibility if only the condition is given as argument to ```when```. There are a number of reasonable choices.

Alternative 2: New ```otherwise``` keyword
-----

```scala
val ex = e -< begin -- (task when "!f.exists()" otherwise skip) -- others start
```
The ```skip``` could be either a method call on the task builder (or whatever internal type is building up the Puzzle at this point) or as ```val skip = StrainerCapsule(EmptyTask())```.

The second alternative is more natural I think and in particular more flexible because it could be used as general "if-else" branching in the workflow, where the user can define a task that is represents the else block. If you want to avoid introducing a global (possible unused) constant ```skip```, it would be fine to just have the user define it in their workflow script and the above in an example in the documentation.

Alternative 3: A new ```SwitchCapsule```
----

Before considering a new ```otherwise``` keyword, it might also be worthwhile to think how further "else if" tasks could be added as well. For example, you could have a new capsule type which holds several tasks in an ordered list together with a condition on each task. Upon execution, the capsule goes through this list of tasks and evaluates their condition. As soon as it finds a task whose condition is true, it executes this task and is done. If none of the tasks' condition is true, it executes an optional user defined default task. If no such default task was set, either pass all inputs to the outputs or do nothing.

```scala
val caps = SwitchCapsule(
  "cond1" -> task1,
  "cond2" -> task2,
  "cond3" -> task3,
  "default" -> task4
)

val ex = e -< begin -- caps -- others start
```
In above example, the SwitchCapsule object's apply method takes any number of arguments, i.e., ```tasks: (String, Task)*```. Nicely, the ```->``` operator in Scala is syntactic sugar to create such 2-tuple. You will have some better insights into OpenMOLE's data and workflow model as well as Scala features that might be useful to realise such "if-elseif-else" branching model.

**Comment by romainreuillon** [comment]
I just implemented 2 workflow pattern builder: Switch and Skip. For example you may use them as follow:

```
val i = Val[Int]
val j = Val[Int]

val t1 = ScalaTask("val i = 3") set (outputs += i)
val t21 = ScalaTask("i = i * 2") set (inputs += i, outputs += i)
val t22 = ScalaTask("i = i * 4") set (inputs += i, outputs += i)
val t3 = ScalaTask("val j = i") set (inputs += i, outputs += j)

val alternative = 
  Switch (
    Case("i < 2", t21),
    Case("i > 2", t21),
    Case(t22)
  )
  
val ex = t1 -- alternative -- (t3 hook ToStringHook())
val ex = t1 -- Skip(t21, "i < 4") -- (t3 hook ToStringHook())
```

Looks good? Any suggestion?

**Comment by romainreuillon** [comment]
Switch is not really a Switch since all true condition are executed...

**Comment by schuhschuh** [comment]
Looks great, that was quick again! I like your ```Switch``` and ```Case``` syntax.

What happens if I leave out the default Case without condition? Does it then not execute any task and also not trigger any transition to the following task(s)? This would be the desired behaviour which is most similar to the conditional transition using  ```when```.

Is it possible to use a ```val t22 = StrainerCapsule(EmptyTask())``` for the default Case? Such that the default for the Switch would be to simply pass the inputs to the outputs. Would be more convenient then having to define the inputs and outputs of the default EmptyTask. In other words, is it possible to have a capsule as second argument of the Case instead of a task. If not, maybe you could also add a special Case type, something along the lines of ```OtherwiseSkip()```.

Would it not be possible to only execute the first Case whose condition is true? Because if multiple Case tasks are executed then will you not have to deal with combining their outputs similar to the parallel task execution (i.e., ```val ex = (t1, t2, t3)```? How do you deal with this?

**Comment by schuhschuh** [comment]
I'm just looking at your changes to understand how such patterns are added. Very interesting! I think it would be a great addition to the developers documentation as people can use it in their OpenMOLE plugins to extend the OpenMOLE language.

> Is it possible to use a val t22 = StrainerCapsule(EmptyTask()) for the default Case?

Given that the argument to the Case pattern is of type ```Puzzle```, the answer to this should be yes.

**Comment by romainreuillon** [comment]
If no condition matches no transition are crossed and the workflow stops. If several condition matches it creates several new execution stream, one for each. 

You can use a strainer capsule (the syntax Capsule(t, strainer = true) is encouraged). The second argument is a puzzle, you can even feed it with a piece of workflow: Case("i < 2", t4 -- t5) is accepted.

I could be possible but it is a less workflow-oriented Switch. We might implement an ExclusiveSwitch witch check that previous conditions have not been met before evaluating the current condition.

**Comment by romainreuillon** [comment]
Indeed, documenting on how to extend the language would be great. Would you submit a PR for that?

**Comment by schuhschuh** [comment]
> I could be possible but it is a less workflow-oriented Switch. We might implement an ExclusiveSwitch witch check that previous conditions have not been met before evaluating the current condition.

Ok, I understand why you chose to have this Switch pattern as it is. It works for me, so I am happy :)

> Indeed, documenting on how to extend the language would be great. Would you submit a PR for that?

Yes, once I have most of the workflows for the REPEAT project up and running (which will then anyway take a couple days to finish), I was considering to extend the documentation with information and examples that would have helped me getting started more quickly.

**Comment by romainreuillon** [comment]
Wonderfull!
