### ISSUE TITLE
Comment uncomment in the editor

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#132]
Add a way to toggle comment on a set of line in the code editor exposing the same behaviour as intelij: 

```
if (all selected lines are commented with line)
then comment then uncomment them
else comment all of them with line comment
```

**Comment by jopasserat** [comment]
Seems to be working. Should be closed?

**Comment by romainreuillon** [comment]
Multi-line comment? How do you do that?

**Comment by jopasserat** [comment]
Select lines then CTRL + / 
Works for me in Chromium

**Comment by romainreuillon** [comment]
Cool. I don't know why but it's not working for me on firefox... And also we might add a button, I think.

**Comment by mathieuleclaire** [comment]
I works on my chromium 49.0.2623.87 but not on my firefox 45.

**Comment by jopasserat** [comment]
Works in my Firefox 45.2.20
#bepo #brokenkeyboard

**Comment by mathieuleclaire** [comment]
It seems to appear only on canonical firefox packaging.

**Comment by mathieuleclaire** [comment]
It works on version Firefox 60.0.1 on Ubuntu !
