### ISSUE TITLE
Link with Jupyter notebook ?

### ISSUE THREAD

**Issue by reyman** [openmole/openmole#135]
Hi,
Another path to explore can be interesting for scientific user is the possibility to integrate some simulation exploration run by openMole into interactive notebook , like http://jupyter.org/ ?

**Comment by mathieuleclaire** [comment]
I do not know jupyter very well. What kind of exports do have in mind ? Results to be plotted ? Is there an API to connect with ?

**Comment by reyman** [comment]
I think it can be interesting to display hook task from an openMole workflow directly into an interactive notebook compatible with scala (see bottom link) and openMOLE. So it can be easy to mix statistic/graphic computation with result of openMOLE workflow.

There is two Kernel -at least- for scala in Jupyter : 
- https://github.com/mattpap/IScala
- https://github.com/alexarchambault/jupyter-scala

It's just an idea, i don't know exactly if it's possible :)

You can see some example of jupyter notebook here : 
http://nb.bianp.net/sort/views/

**Comment by jopasserat** [comment]
Interesting issue as we'd started discussing about that recently.

My understanding of jupyter is that it serializes data back and forth from a kernel (your "engine") using JSON.
We could have a look at the Scala kernel and/or Spark kernel that have been written for Jupyter.

Another option is to integrate plotting features to the WebUI with something like Scala bokeh.

**Comment by jopasserat** [comment]
I suggest splitting this feature into two: 

- stick to a potential interaction with existing notebooks in this one
- move graphical plots to #175
- we need to revamp the REST API first

**Comment by reyman** [comment]
Hi @jopasserat 
I discuss with a research engineer of mathematic lab who is interested by jupyter coupling with OpenMOLE, i'm opening a post on the forum tomorow.

**Comment by JusteRaimbault** [comment]
Closing this as we moved to integrate many plots in the gui
