### ISSUE TITLE
Display environemnt error assynchronously

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#138]
Environment error display makes execution refresh unresponsive on DSL connection when there are a few errors. A solution would be to download and display them only on demand when clicking a button. In that case a new window containing the errors could be displayed.

This implementation would make the error/debug button obsolete as it would would be possible to display the exceptions in a calc sheet with sortable fields. The user could then sort on error type to get all the error by gravity level.

**Comment by mathieuleclaire** [comment]
f044385379c2c46fc5e4b97f8fe3bbe503913602 fixes it
