### ISSUE TITLE
Submodules don't get pulled from Market Place

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#144]
Neither in the GUI nor in the documentation does the submodule [advanced](https://github.com/guillaumecherel/TutorialEAForModelling/tree/5ea4ec7e3efff9882a7fd618cd2e3ee82c0cef29) appears.

Some equivalent to `git submodule update --recursive` should be used [(see this post)](http://stackoverflow.com/a/8084186/470341l).

**Comment by romainreuillon** [comment]
This is intended. Having sub-module is actually unfit for the market since we cannot update them easily when the syntax changes. I'm almost finished with merging a working version of advanced into the market as a plain folder.
