### ISSUE TITLE
java.util.noSuchElementException in WebUI's authentication panel

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#145]
When clicking on an already created authentication in the corresponding panel, the exception `java.util.noSuchElementException: key not found: org.openmole..` is displayed (see screenshot).

![exception](https://cloud.githubusercontent.com/assets/472083/14477334/09b5da0a-0105-11e6-92c1-f2811e3e0271.png)

This happens no matter the type of authentication clicked on.

**Comment by mathieuleclaire** [comment]
Fixed
