### ISSUE TITLE
Port not saved in WebUI's authentication panel

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#147]
When trying to replace the port number for an SSH authentication, the new value is not saved and always replaced by 22, the default value.

This happens with both LoginPassword and PrivateKey authentications.

A custom value directly set from the authentication file in the preferences folder is however correctly read and used by the panel.

The problem is only when saving from the panel.

**Comment by mathieuleclaire** [comment]
The authentications (and the whole GUI interface) are currently unstable, I will commit a fix today or tomorrow.

**Comment by mathieuleclaire** [comment]
Fixed.
