### ISSUE TITLE
Files button blanks out workspace panel

### ISSUE THREAD

**Issue by parisots** [openmole/openmole#150]
When clicking on the _Files_ button in the top bar, the workspace is successfully collapsed but not restored when clicking a second time on _Files_.

![image](https://cloud.githubusercontent.com/assets/9533058/15077663/62860a38-13a7-11e6-9e1b-29f8ac6bb834.png)

**Comment by mathieuleclaire** [comment]
Yes, this part is going to be refactored soon !

**Comment by mathieuleclaire** [comment]
3377772c6cce1a7c084bf3b78d6dbaf4b032898b fixes it
