### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#151]
Caught the monster ;)

Happened while uploading data to a remote environment at the beginning of a workflow:

![image](https://cloud.githubusercontent.com/assets/472083/15080068/0ee12388-13b4-11e6-8872-f1b50519ffa4.png)

**Comment by mathieuleclaire** [comment]
7a47b01349017d2e79ed71a6b907b8ed0b5bc57d fixes it
