### ISSUE TITLE
Add warning when the web client is not able to save the script

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#152]
It would be very useful (especially on unreliable connection) if some deconnection warning were displayed when the client is not able to save the scripts (connection timeout).

**Comment by jopasserat** [comment]
Here is an example of how Rocket.Chat notifies the user he's offline with a slick topbar containing the error message:

![rocketchat_offline](https://cloud.githubusercontent.com/assets/472083/16728413/0585849a-475e-11e6-92ab-5b7379bda8b7.png)

**Comment by romainreuillon** [comment]
Duplicate of #162.
