### ISSUE TITLE
Shutdown confirmation overlaps with workspace

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#154]
When clicking on the shutdown button, the confirmation message is displayed over the workspace:

![shutdown](https://cloud.githubusercontent.com/assets/472083/15198564/041036ea-17d0-11e6-9095-a1a986757b84.png)

This is perfectly functional and terminates the application correctly though.

Reproduced in Firefox 45.0.2 and Chromium 49.0.2623.108.

**Comment by mathieuleclaire** [comment]
5dd6e71ba9e832f8205d828de4dc1149e5036719 fixes it
