### ISSUE TITLE
Executions stop being refreshed after a while

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#157]
A long running workflow's Execution stops being updated after a while (about 5 days in my case) and the Executions panel is empty.

No log message in the console.

OpenMOLE was launched in remote mode with last commit 3a0d6a2a82dfcdd5b189ed48ebf178814a2ff75d.

![executions](https://cloud.githubusercontent.com/assets/472083/15672132/907f62a8-2726-11e6-9ed7-48b4aef33821.png)

**Comment by romainreuillon** [comment]
Are you sure that your server hasn't crashed for some reason?

**Comment by jopasserat** [comment]
Well i can still interact with the rest of the interface like editing files for instance.

One thing i just noticed is the market place panel is also empty. So it could be that a network problem occurred at some point.

**Comment by romainreuillon** [comment]
Even because of a network pb, OpenMOLE is not supposed to loose the trace of running execution. The code to manipulate running moles in the GUI is fully transactional. Maybe there is a mistake in that code. Could you review it, in case you find something odd?

**Comment by mathieuleclaire** [comment]
Weird, an empty market place is typical of server switched off. Can you see troubles when you do actions calling server in debug mode (F12 in your browser) ?

**Comment by jopasserat** [comment]
Yep:

`Failed to load resource: the server responded with a status of 500 (Internal Server Error)   https://hornbeam.doc.ic.ac.uk:50081/org/openmole/gui/shared/Api/allStates Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by jopasserat** [comment]
And now the market entries are back...

**Comment by jopasserat** [comment]
I keep on getting this error message when I leave the Executions panel open + debug mode:

![errors](https://cloud.githubusercontent.com/assets/472083/15677137/e1c85cfe-2740-11e6-8430-652063a1445b.png)

**Comment by romainreuillon** [comment]
May be due to a memory leak... fixed.
