### ISSUE TITLE
Model path is not right when importing a netlogo model in archive

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#159]
NetLogo import wizard produce an wrong path for the nlogo script when importing a model in an archive.

**Comment by romainreuillon** [comment]
To reproduce, archive a netlogo workspace and import with wizard.

**Comment by mathieuleclaire** [comment]
b63dc8c96c0bfdaf0c48c1cb38c7968bb4764d91 and d2811d0e066cc0fc6f499fda5383d4add1269471 fix it
