### ISSUE TITLE
Support .nls model import in NetLogo wizard

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#164]
.nlogo is the main model file, but it can import other model files when they are in .nls file
It's the only way to have a file-based organisation of a model, as one can not include a .nlogo

See here : http://ccl.northwestern.edu/netlogo/docs/interface.html#includes

PS : the doc says that "Caution: The includes facility is new and experimental. ", but it's been there for like 4-5 years :)

**Comment by romainreuillon** [comment]
Separated from #118

**Comment by romainreuillon** [comment]
@RCura

**Comment by JusteRaimbault** [comment]
The standard use of .nls files is to put functions and procedures ; good practices advise to put all primitives in the .nlogo code (extensions, globals, includes, breeds) and use .nls as auxiliary sources.
So even in the case of parsing globals in code we should'nt look into nls files (maybe in the case of reporters but how to know which reporters are intended to be outputs ? impossible !)
Anyway, the way the wizard works now is that it considers gui sliders/choosers/switches as inputs, ad monitors as outputs, what is relevant with the idea of most important input/output being modifiable/visible in the gui.
To be conservative for possible future enhancements, we could inject all .nls code in the .nlogo file before parsing it, so in an eventual future case of code parsing (let say with a provided list of globals/ reporters, or regex to match - let say a specific naming patterns to be taken into account by openmole) we will be able to take them into account. But that's a totally other issue and possible enhancement (on which more thinking is first needed).
I'm therefore closing this issue which is not relevant anymore given the wizard's philosophy.
