### ISSUE TITLE
Write CSV header if file does not exist

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#17]
The ```AppendToCSVFileHook``` appends the data to a file. If the file does not exist yet, it creates a new empty file. It would be nice if this hook could be passed also the expected header of the CSV, i.e., an ExpandedString of the first line and write it to this newly created file. If the file already exists, it can be assumed that the header is already in place. Hence, only the first task that tries to append to this file will also write the header. All others will only add the additional rows.

While it is possible to create the CSV file beforehand, the file name and header may depend on some expanded values. Therefore, this requires to create the CSV file and write its header within a previous task of the workflow. Would be convenient if ```AppendToCSVFileHook``` could take care of this.

Also, I am not sure in which order the output values are written. Is it the same as in ```outputs += (a, b, c)```, i.e., the appended CSV row would be ```${a},${b},${c}``` ?

Is it possible to include constant values in the appended CSV row for which no workflow variable is defined, e.g., ```bla,${a},${b},bla,${c}``` ?

**Comment by schuhschuh** [comment]
Hm, I don't actually have the case that it is hard to create the CSV file with header before starting the execution of the MOLE. So this feature suggestion is arguable.

More important the clarification of the other questions (which could have been posted to the mailing list) and if that can be addressed. Otherwise, I can work around this by using a ```AppendToFileHook``` instead which gives me greater control/is easier to understand what it does.

**Comment by romainreuillon** [comment]
Now you should be able to specify the header:
AppendToCSVHook (....) set ( csvHeader := "${a},${b},${c}" )

**Comment by schuhschuh** [comment]
Nice!

**Comment by schuhschuh** [comment]
> Also, I am not sure in which order the output values are written. Is it the same as in outputs += (a, b, c), i.e., the appended CSV row would be ${a},${b},${c} ?

I think the following snippet from AppendToCSVFileHook.scala should help to answer this question:
```scala
object AppendToCSVFileHook {

  def apply(fileName: ExpandedString, prototypes: Prototype[_]*) =
    new AppendToCSVFileHookBuilder(fileName, prototypes: _*)

}
```
Thus, I can specify the value of which variables I want to be written to the CSV file. Perfect! And the order should be equivalent to the order of the arguments to ```apply```.

(Note to self, needs to be documented!)

**Comment by jopasserat** [comment]
What about that f93b07ea4856451ba44810f0e4af3fadbaed8974 ?

**Comment by schuhschuh** [comment]
Looking good
