### ISSUE TITLE
Missing scrolling bar for file list

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#170]
The file list is missing a scrolling bar when it get long.

**Comment by FourquetDavid** [comment]
I have a similar bug : 
I have the scroll bar, but I can't scroll down to the end.
 I have 192 files in my data folder. 
Only around 120 are visible when scrolling down.
When launching a workflow on datafiles, I have 192 jobs : files are here but invisible.

and a third one probably related :
 scrolling with mouse wheel has a delay, no problem with the scroll bar

**Comment by mathieuleclaire** [comment]
18b6e61224751da84273ec18ec50c65e59eb05ce fixes it
