### ISSUE TITLE
+ symbol for folder containing files in GUI

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#171]
According to the Doc panel in the GUI (and that sounds like something I've seen before), there used to be a + symbol for files containing files.

I can't see it anymore. Is it the new desired behaviour and shall we simply remove it from the documentation?

![missing](https://cloud.githubusercontent.com/assets/472083/18255937/cf862a50-73a6-11e6-9304-234b57a0cb1a.png)

(tested with both Chromium and Firefox)

**Comment by mathieuleclaire** [comment]
This functionnality has been get rid off to avoid to compute the whole tree when launching openmole. The folder contents are now computed in a lazy manner and cached. Advantage: the application starts more rapidely when the file system contains a lot of files. Drawback, we loose the information about file contents. In Java, getting the folder size can be very slow in case of many files. 
Edit: after a fresh search, I realize it could be doable and fast with streams: https://stackoverflow.com/questions/5930087/how-to-check-if-a-directory-is-empty-in-java

**Comment by mathieuleclaire** [comment]
398f336055d2a2c54ee63e9e0e73bc907d608654 implements it
