### ISSUE TITLE
Over 100% upload while uploading multiple files

### ISSUE THREAD

**Issue by FourquetDavid** [openmole/openmole#173]
I tried to upload multiple (around 200) big files (3-20 Mo) . The uploading percentage went over 100% and did not complete.
![bug-178percent](https://cloud.githubusercontent.com/assets/2657984/18305729/2b6b1f5e-74e9-11e6-9660-1a98aa1f7837.png)

**Comment by mathieuleclaire** [comment]
It seems this occur with big files or with a very large amount of bytes to upload. A workaround wourd be to use the slice method of the XMLHTTPRequest: https://stackoverflow.com/questions/7395635/xmlhttprequest-fails-on-large-files
