### ISSUE TITLE
File manager very slow with numerous files

### ISSUE THREAD

**Issue by FourquetDavid** [openmole/openmole#174]
When I have plenty of datafiles (around 200) in the same folder, the file manager becomes really slow : it takes 4-5 second to show the panel "copy,drag,download" when I click on a file and to go to another folder. 

This only happens in my data folder. Everything is fine when I come back to my home folder with only 4 folders and 10 files

**Comment by mathieuleclaire** [comment]
Hi David,
what version do you use, this issue is supposed to be fixed in the 6.0 version.
Mathieu

**Comment by FourquetDavid** [comment]
Salut Mathieu,

 Je crois que j'utilise la version 7.0 snapshot que Romain m'a installée.
Il vaut mieux lui demander pour être sûr.

David

2016-09-22 23:09 GMT+02:00 Mathieu <notifications@github.com>:

**Comment by mathieuleclaire** [comment]
Commits from 4f8b9c2eb8407208d341904a5d8d8c5ff0c32665 to 1d7c5f2f9d0294f021cf62afa29f123b277a7cc2 on 6-dev branch would highly help !

**Comment by jopasserat** [comment]
closed then?
