### ISSUE TITLE
Move the Play button outside the text edition area?

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#179]
I've been suggested to move the Play button up to have it in the gap in between the text box and the top bar.

Not sure how doable it is, since the current location allows Play to be hit at anytime even if the workflow script is too long to fit in a single screen.

What do you think?

**Comment by mathieuleclaire** [comment]
implemented in #643c18d78798d16d74499cd3dc5714d574149c07. Merry Christmax Jo ;)
