### ISSUE TITLE
Issues writing sequence to single CSV row instead of column

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#18]
Using the ```AppendToCSVFileHook```, it is possible to write the values of workflow variables to a CSV file. When the type of the variable is ```Array```, the elements are interpreted as different values of the same column in the CSV file. Other variables consisting of only one or fewer values are extended by duplicating the last element to match the number of rows (array elements) across all variables. This behaviour is most likely due to how the aggregation transition works. It accumulates the results of all parallel streams into arrays. These would then naturally be written column-wise to the CSV.

However, in my workflow, I have a variable of type ```Array``` which stores the values of multiple columns for the final CSV and the number of columns is not fixed but depends on some user setting in a configuration file. These columns represent different quality measures computed from the experiment results which should all be written to the same row of the CSV for the particular experiment (set of parameters).

Given a task such as the following
```scala
val writeDiceToCsv = Capsule(EmptyTask() set (
    name    := "writeDiceToCsv",
    inputs  += (tgtId, srcId, diceRow)
  ), strainer = true) hook (
    AppendToCSVFileHook(diceCsvPath, tgtId, srcId, diceRow) set (
      csvHeader := "target,source," + regions.mkString(",")
    )
  )
```
where for example the values of the input variables are
```scala
val tgtId = 1
val srcId = 2
val diceRow = Array(0.1,0.2,0.3,...)
```
This should be appended to the CSV file as
```
1,2,0.1,0.2,0.3,...
```
instead of
```
1,2,0.1
1,2,0.2
1,2,0.3
1,2,...
...
```
If multiple sequence variables were to be written to the CSV file, the values of these should all be concatenated (separated by comma) and written to a single row.

When I use a 2D array (i.e., ```Array[Array[_]]```) as input to ```AppendToCSVFileHook``` or use the writer task after the aggregation, I end up with values written to the same row as intended. However, these are enclosed by brackets and differently formatted from other columns (i.e., space after comma) as in:
```
1,2,[0.1, 0.2, 0.3]
```

This shows actually also another issue. The prettified list should be enclosed in double quotes such that it is recognised as single column value instead of ```[0.1```, ```0.2```, and ```0.3]```. In general, all variable values which after conversion to a string contain a comma should be enclosed in double quotes (which then also requires escaping of double quotes within these strings).

The correct output should be
```
1,2,"[0.1, 0.2, 0.3]"
```
which however is still not what I would like in my case.

**Comment by schuhschuh** [comment]
For example, what about the addition of a Boolean ```singleRow``` member such as in
```scala
val writeDiceToCsv = Capsule(EmptyTask() set (
    name    := "writeDiceToCsv",
    inputs  += (tgtId, srcId, diceRow)
  ), strainer = true) hook (
    AppendToCSVFileHook(diceCsvPath, tgtId, srcId, diceRow) set (
      csvHeader := "target,source," + regions.mkString(","),
      singleRow := true
    )
  )
```
By default, it would be ```false``` in which case the values are written to the same column as it is done right now. Otherwise, all elements of sequences are concatenated on a single row. Nested elements are converted to a string using the prettified function and enclosed in double quotes if needed.

**Comment by schuhschuh** [comment]
I was also working on adding a ```singleRow``` option similar to how you added the ```csvHeader``` before. I think this just requires flattening the ```lists``` in the ```AppendToCSVFileHook.write``` function. However, direct use of the ```flatten``` function did not work as I got incompatible types.

**Comment by schuhschuh** [comment]
For the use of the ```AppendToCSVFileHook``` instead of a plain ```AppendToFileHook``` in my workflow, I have now only one issue remaining. I want to not only write the values of some workflow variables to a single row in the CSV file, but also some constant entries. One solution to this problem is to actually introduce a workflow variable which is set by the task on which the hook is installed to the appropriate value as in
```scala
val method = "affine"
val methodVal = Val[String]
val diceValues = Val[Array[Double]]
val meanDice = Val[Array[Double]]

val writeMeanDiceToCsv = ScalaTask(
  s"""
    | val meanDice = diceValues.transpose.map(_.sum / diceValues.size)
    | val methodVal = $method
  """.stripMargin) set (
    name    := "writeMeanDiceToCsv",
    inputs  += diceValues.toArray,
    outputs += (methodVal, meanDice)
  ) hook (
    AppendToCSVFileHook(meanDiceCsvPath, methodVal, meanDice) set (
      csvHeader := "method," + regions.mkString(","),
      singleRow := true
    )
  )

// [...]

val ex = exploration -< computeDiceValues >- writeMeanDiceToCsv
```

More convenient would be if the constructor of ```AppendToCSVFileHook``` would accept not only column entries of type ```Prototype```, but actually any type such that above example simplifies to
```scala
val writeMeanDiceToCsv = ScalaTask(
  s"""
    | val meanDice = diceValues.transpose.map(_.sum / diceValues.size)
  """.stripMargin) set (
    name    := "writeMeanDiceToCsv",
    inputs  += diceValues.toArray,
    outputs += meanDice
  ) hook (
    AppendToCSVFileHook(meanDiceCsvPath, method, meanDice) set (
      csvHeader := "method," + regions.mkString(","),
      singleRow := true
    )
  )
```

**Comment by romainreuillon** [comment]
You can also set variables in the hook I think:

```scala
val v = Val[Int]
    AppendToCSVFileHook(meanDiceCsvPath, method, meanDice, v) set (
      csvHeader := "method," + regions.mkString(","),
      singleRow := true,
      inputs += v,
      v := 3
    )
```

May be AppendToCSVFileHook should be able to take a list of ExpandedString and we could have an implicit conversion from Prototype to ExpandedString.

**Comment by romainreuillon** [comment]
Actually, it doesn’t work as it is....

**Comment by schuhschuh** [comment]
> You can also set variables in the hook

Ok, that is actually not too bad and wouldn't need any change of the ```AppendToCSVFileHook```. It would be just more convenient and flexible if one would not need a ```Prototype``` variable for a constant entry.

> May be AppendToCSVFileHook should be able to take a list of ExpandedString and we could have an implicit conversion from Prototype to ExpandedString.

Sounds interesting. And the string expansion would also still do the prettifying during the value to string conversion ?

> Actually, it doesn’t work as it is....

What does not work ?

**Comment by romainreuillon** [comment]
> What does not work ?

I think that exclusively only ExpandedStrings would prevent from keeping the multirow output...

**Comment by schuhschuh** [comment]
Actually, using ExpandedStrings instead for the ```AppendToCSVFileHook``` is not such a good thing anyway because in that case I could just as well use the ```AppendToFileHook```. Either the type of the arguments of ```AppendToCSVFileHook``` is changed from ```Prototype``` to ```Any``` (or ```AnyRef```?), or it is simply required to use a prototype variable which can be set by the ```AppendToCSVFileHook``` using ```v := value```. I am fine with the latter.

As soon as I can confirm that my workflow is working fine with the ```AppendToCSVFileHook``` I will close this issue.

**Comment by schuhschuh** [comment]
Up and running fine.
