### ISSUE TITLE
Hiding Files view leaves buttons over text area

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#181]
OpenMOLE 6.0, observed on Safari and Chrome.

See screenshot:
<img width="796" alt="screen shot 2016-11-20 at 14 21 50" src="https://cloud.githubusercontent.com/assets/975451/20463517/cb8e5820-af2c-11e6-8055-a36012e4c0dc.png">

**Comment by romainreuillon** [comment]
I observe the same problem on firefox and chrome.
