### ISSUE TITLE
Display starting tip when the file browser is empty

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#183]
For beginners (and the demo version) it would be useful to display a message when the file browser of OpenMOLE is empty. The message could advise to create a .oms file, to checkout examples in the market or to go to the openmole sites for documentation.

**Comment by mathieuleclaire** [comment]
Is it still useful, since we now have a start button (#169)

**Comment by mathieuleclaire** [comment]
#169 Fixes this
