### ISSUE TITLE
Clean code view in the execution panel

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#187]
The code view appear with red lines due to an automatic corrector, which has no sense at this place.

**Comment by romainreuillon** [comment]
May be your firefox or chrome corrector, isn't it?

**Comment by mathieuleclaire** [comment]
Maybe, but it is not suppose to happens. It does not on buttons or labels for instance. Fortunately !

**Comment by mathieuleclaire** [comment]
https://github.com/openmole/scaladget/commit/5ca44394822fbf9718ecf1f1e1653e93501f1d3c fixes it
