### ISSUE TITLE
Document importance of .bashrc on cluster environments

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#189]
- [ ] Explain where OpenMOLE looks for submission commands on remote hosts (boots up a non login bash shell and mimics the sequence of files loaded by bash as a login shell, ie:
```bash
/etc/profile
~/.bash_profile
~/.bash_login
~/.profile
```
(According to [HackTux](http://hacktux.com/bashrc-bash_profile/), _"Although ~/.bashrc is not listed here, most default ~/.bash_profile scripts run ~/.bashrc."_

But it might still be required to manually `source ~/bashrc` in `~/.bash_profile` if errors persist.

- [ ] Document typical error in new FAQ entry
`"Unexpected return code 127, when running cd /export131/home/rdr16/.openmole/.tmp/ssh/openmole-206dd73b-9f2a-4145-a62e-3e997ae10292/tmp/1480522302020/8d955736-5f5b-4fdd-9587-440bde9e1610 && qsub 01a1d162-3626-4232-bc81-aa30ad174d39.pbs (stdout=, stderr=bash: no job control in this shell bash: line 1: qsub: command not found"`

**Comment by jopasserat** [comment]
See if this is still relevant with new method to load `.bashrc`

**Comment by romainreuillon** [comment]
Fix source env files in gridscale.
