### ISSUE TITLE
Howto for documentation proposal

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#190]
This is to keep track of @reyman's [proposal on the mailing list](http://fedex.iscpif.fr/pipermail/openmole-users/2016-November/000978.html).

- [ ] Improve the existing [documentation page](https://openmole.org/Documentation_Development_Documentation.html)  [openmole/openmole/bin/org.openmole.site/src/main/scalatex/openmole/documentation/development/DocumentationWebsite.scalatex](https://github.com/openmole/openmole/bin/org.openmole.site/src/main/scalatex/openmole/documentation/development/DocumentationWebsite.scalatex)
- [ ] kickstart Github wiki as simple entrypoint for new contributors to the documentation
- [ ] link to [ScalaTex documentation](http://www.lihaoyi.com/Scalatex/) for the brave

**Comment by romainreuillon** [comment]
Edit page link has been added.
