### ISSUE TITLE
NPE when updating environment in GUI

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#191]
Just came across a `NullPointerException` in the Executions panel.

- Happened when submitting a basic workflow ([example 4 from Native application tutorial](https://github.com/openmole/openmole-market/blob/7-dev/tutorials/native/4/Param.oms))
- Only modification was to create a `PBSEnvironment` and delegate the main task to this PBS.
- After clicking Play, the Execution panel opens up normally
- When expanding envs/details, clicking Update leads to this crashed panel:

![untitled](https://cloud.githubusercontent.com/assets/472083/20764300/88331628-b725-11e6-88bb-4f1146b40fd9.png)

I'm trying to corner it to a reproducible scenario (just seen it once so far).
Best guess would be an SSH failure badly handled as there's still quite a lot of log messages printed in the console down form schmizz in GridScale: 

_the too famous_ 
```
17:08:30.617 [Thread-33] ERROR net.schmizz.concurrent.Promise - <<chan#10 / open>> woke to: Opening `session` channel failed: open failed
```

 

OS: Debian stretch
Browser: Chromium  53.0.2785.143
Outcome: **not fatal** the application and workflow keep on running, refreshing the page removes the error from the Executions panel

**Comment by jopasserat** [comment]
This is linked to a `null` errorMessage. See the JSON response retrieved in Chromium's debugger:

```json
{"datedErrors":[[{"environmentId":{"$type":"org.openmole.gui.ext.data.EnvironmentId","id":"d4c81928-4ff9-4f21-9a2f-2fd0190d8c98","executionId":{"$type":"org.openmole.gui.ext.data.ExecutionId","id":"a18c79b7-ec88-48be-8893-097d4e426941"}},"errorMessage":null,"stack":{"stackTrace":"java.lang.NullPointerException\n"},"date":"1497966454332","level":{"$type":"org.openmole.gui.ext.data.DebugLevel"}},"1497966454670",1000]]}
```

**Comment by romainreuillon** [comment]
Seems to be fixed, resubmit if it reappears.
