### ISSUE TITLE
Every documentation section should have an anchor link

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#192]
## Problem

Not all the sections in the doc can be directly pointed to with an hyperlink (typically the various entries in the [samplings section](https://next.openmole.org/Documentation_Language_Samplings.html) ).

## Proposal

Redefine the section operator in ScalaTex (or whatever replaces it ;) ) to automatically create an anchor link to the section.

**Comment by mathieuleclaire** [comment]
Fixed in the brand new website
