### ISSUE TITLE
EGI Authentication set in the console lead to a file not found in authentication test

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#194]
To reproduce:
 - set the EGI authentication in the console: EGIAuthentication() = P12Certificate(encrypted)
 - exit
 - launch the web interface
 - go in the authentication test panel, the authentication is read with a "file not found" exception

**Comment by mathieuleclaire** [comment]
3bee75be48cb4ba3c6cb3f8656b74d31855985f2 fixes it
