### ISSUE TITLE
Enhancement of the editor for oms scripts

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#199]
It would be great to make the etidor recognize OpenMOLE keywords (like inputs, ScalaTask, etc) including plugins keywords (NetLogoTask for instance).

**Comment by romainreuillon** [comment]
The mechanism has been implemented in d3b897b9ddfb0e2642cfbba7ce3b3c0f1499c7cb

The keywords are accessible using ```PluginInfo.keyWords```

All the keywords are not listed yet but the mechanism is ready.

**Comment by mathieuleclaire** [comment]
Implemented in the GUI.
