### ISSUE TITLE
Scrolldown is messed up when execution is finished on low resolution screen

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#206]
On a screen of 1366x768 the scroll down functionality of a script is impaired by the banner when a mole finishes.

**Comment by jopasserat** [comment]
Reproduced on both Chromium and Firefox.
Happens after running a workflow once.
Refreshing the page solves the problem.

![screenshot from 2017-06-14 20-12-49](https://user-images.githubusercontent.com/472083/27150421-1d9348d8-513f-11e7-9df9-c520755534f1.png)

**Comment by mathieuleclaire** [comment]
It appears when the top alert banner appears. Closing it fix the problem. It is still an open issue

**Comment by romainreuillon** [comment]
A solution: put the banner at the bottom of the page and on on top.
