### ISSUE TITLE
Header buttons overlap when resizing the app window

### ISSUE THREAD

**Issue by helenea** [openmole/openmole#211]
Hi openmole team,

I've encountered this issue a few times on different screens and resolutions. When I resize the app window, the Play and Menu buttons overlap with the other buttons on the header (see picture below).

![overlap_header](https://cloud.githubusercontent.com/assets/8794131/26150106/36912eac-3afd-11e7-9348-f1821c4c0216.png)

**Comment by mathieuleclaire** [comment]
2e3b5d5c046511ff3e120a68009285bd720e8100 fixes it
