### ISSUE TITLE
Netlogo 6.x don't load extensions

### ISSUE THREAD

**Issue by reyman** [openmole/openmole#213]
Hi, actually it's impossible to load extensions with some file path using `NetlogoHeadless` API, so `netlogoTask6` is not totally operational.

Today, i help some debug into Netlogo 6.0.1 API with dev, which finally found the bug into `AbstractWorkspaceScala` file.

I update this issue with the # number when Robert Grider commit the fix in Netlogo repository.

**Comment by jopasserat** [comment]
ok so it's a pure netlogo bug then? 

will just have to update the dependency in `libraries/build.sbt` when fixed

**Comment by reyman** [comment]
The Netlogo version `6.0.1-7243aaa` fix the change on [bintray](https://bintray.com/netlogo/NetLogo-JVM/netlogo/6.0.1-7243aaa)

**Comment by romainreuillon** [comment]
Hi Seb,

great job ! The NetLogo version has been updated to 6.0.1. Can you test it?

Romain

**Comment by reyman** [comment]
Hi, i already test it with 6.0.1, don't work, and the error persist also with `6.0.1-7243aaa` version, i try to continue discussing today with netlogo dev to understand.

**Comment by reyman** [comment]
Ok, so, after explanation with Robert Grider, we don't need an extension folder, extension can appear directly at the root of the model now. The fix appear in the next release of 6.0.x, but @romainreuillon meanwhile we could use the 6.0.1-7243aaa jar .
