### ISSUE TITLE
Tasks submitted to user account instead of OAR Scheduler

### ISSUE THREAD

**Issue by chasset** [openmole/openmole#214]
Hello,

I am using the HPC platform of the University of Luxembourg (https://hpc.uni.lu/).

There are two schedulers in use: SLURM and OAR (https://hpc.uni.lu/users/docs/scheduler.html).

I try to run the code below: 

```
val density = Val[Double]
val seed = Val[Int]
val burned = Val[Double]

val cmds = 
  List(
    "random-seed ${seed}",
    "setup",
    "while [any? turtles] [go]"
  )

val fireTask =
  NetLogo6Task(workDirectory / "Fire.nlogo", cmds) set (
    inputs += seed,
    outputs += (seed, density),
    netLogoInputs += (density, "density"),
    netLogoOutputs += ("burned-trees", burned)
  )

val csvHook = CSVHook(workDirectory / "result.csv", density, burned, seed)

val env = OAREnvironment(
    "UUUU",
    "DDD.uni.lu",
    port = PPPP
  )

val exploration = 
  DirectSampling(
    evaluation = Replication(fireTask hook csvHook on env, seed, 100),
    sampling = density in (20.0 to 80.0 by 1.0)
  )

exploration
```

This code attempts to submit task to the OAR Scheduler, but it raises a lot of logs like this :

```
15:53:21.322 [Thread-70] ERROR net.schmizz.concurrent.Promise - <<chan#81108 / open>> woke to: Opening `session` channel failed: open failed
```

My HPC administrator informs me that the jobs are running directly on the user account 'UUUU', not on the cluster.

Could you help me to fix my code in order to get the job submitted to the scheduler instead?

Best regards,

Pierre-Olivier

**Comment by jopasserat** [comment]
Hi @chasset,

Can you tell us what version of OpenMOLE you're using?

**Comment by chasset** [comment]
7.0-RC4

**Comment by jopasserat** [comment]
OK, you seem to have access to a Slurm cluster as well, do you encounter the same problem with it?

**Comment by reyman** [comment]
I also have possibility to use SLURM on CRIANN mesocentre in Normandy, so i'm interested to know if it's works well :)

**Comment by jopasserat** [comment]
I can definitely run it on a Slurm cluster (jobs get submitted but crash which I assume is linked with #213 ??)

**Comment by reyman** [comment]
Not sure, the **fire.nlogo** example given by @chasset doesn't use any netlogo extensions.

**Comment by chasset** [comment]
My model is a very simple one coming from the marketplace.
My account will be unavailable until next week in order to test the SLURM Scheduler.
Could you give me your code?

**Comment by jopasserat** [comment]
I've tested with the same example (I've no experience with netlogo so that's the best I could do :) )

The Slurm definition is similar to the OAR one:

`val slurm = ("UUUU", "DDD.uni.lu", port = 42)`

More info here: https://next.openmole.org/Documentation_Language_Environments_Clusters.html#Slurm

**Comment by chasset** [comment]
I create a public script in order to get a better understanding of your [code](https://gist.github.com/chasset/7132a4e00c3b0c0ecdd565f8052e0a78). Could you check please if is it alright?

**Comment by reyman** [comment]
I think this is more `evaluation = Replication(fireTask on env hook csvHook , seed, 100)`

**Comment by jopasserat** [comment]
I think both should work

**Comment by romainreuillon** [comment]
Hi @chasset, could you ask your cluster admin which command you are supposed to run to submit jobs on the cluster?

(FYI: openmole is supposed to run a installation script on the headnode and then to submit job to the scheduler)

(FYI2: don't bother with the log you see it is armless)

**Comment by chasset** [comment]
It seems to be a whole process. Could you find an answer of your question in this [page](https://hpc.uni.lu/users/docs/oar.html)?

**Comment by chasset** [comment]
@reyman : it works very well with just this line changed `val env = LocalEnvironment(4)`. The tasks are fast resolved and results look good.

**Comment by jopasserat** [comment]
Could you try with your Slurm cluster as well?

**Comment by chasset** [comment]
@jopasserat : I will. I need to recover my account first ;o)

**Comment by chasset** [comment]
@jopasserat @romainreuillon @reyman : Ok, I recover my HPC account, but I realize that I don't have the rights to access to  the cluster managed by SLURM. So, we are back to the OAR!

**Comment by romainreuillon** [comment]
OpenMOLE accesses the cluster in 2 phase. First it install OpenMOLE on the head node, then it launches jobs through the `oar` commands. On the OpenMOLE side do you see job being submitted or just some files being copied and 0 jobs submitted?

**Comment by chasset** [comment]
@romainreuillon: Both seem to happen. I have obtained results too.

![clipboard - 22 mai 2017 14-12](https://cloud.githubusercontent.com/assets/1488688/26575322/0611f522-4525-11e7-9b85-d92449a5be20.png)

![clipboard - 22 mai 2017 14-12](https://cloud.githubusercontent.com/assets/1488688/26575349/22d82424-4525-11e7-843b-48c602dba305.png)

**Comment by romainreuillon** [comment]
Could you execute the `oarstat -u username` to list you jobs on the head node? (while you workflow is running)

**Comment by chasset** [comment]
@romainreuillon Well, last time I submitted my jobs, the cluster was unavailable for all users. It looked like a DoS attack. So, I would prefer to find a lighter way to make new tests. What do you think of it?

**Comment by romainreuillon** [comment]
OpenMOLE opens max 10 ssh connections to the headnode. You can change that to 2 for instance by settings the property "SSHEnvironment.MaxConnections = 2" in the preference file in .openmole/hostname/persistent/....

**Comment by chasset** [comment]
It doesn't work on my side with SLURM.

**Comment by jopasserat** [comment]
Hi @chasset 

I've also had problems on Slurm due to a bug was fixed by @romainreuillon in master.
However we haven't redeployed to the website yet (spoiler alert) as it's undergoing a complete redesign for the 7.0 release.

Can you try with the archive in the pre-release?https://github.com/openmole/openmole/releases/download/v7.0-RC5/openmole.tar.gz

**Comment by jopasserat** [comment]
Any news on this @chasset ?

**Comment by mathieuleclaire** [comment]
Close due to inactivity. OAR environments have been fully refactored. New tests should be done.

**Comment by chasset** [comment]
I finally wrote the batch directly in SLURM and OAR.
