### ISSUE TITLE
Local environments are not displayed correctly in Executions view

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#219]
When a `LocalEnvironment` is defined as a computing environment for the execution of a task, it does not get merged with the `local` entry dealing with the workflow and explorations.

![screenshot from 2017-06-24 19-40-40](https://user-images.githubusercontent.com/472083/27511126-fe4e2770-5915-11e7-8bee-32c1b2ea7047.png)

**Comment by jopasserat** [comment]
Also, the total successful executions on this environment are not update (Flag should be 3 not 0 in this case).

**Comment by romainreuillon** [comment]
I think it make actually some sense since the 2 local envs are different and represent separated set of threads. You could name it differently than local to avoid the confusion.

**Comment by romainreuillon** [comment]
For the total execution it is because you didn't submit any job on the default env.

**Comment by jopasserat** [comment]
not on the default but the one I've created (first in the list) should have been updated right?

**Comment by romainreuillon** [comment]
I guess it is the second... how can you tell they have the same name?

**Comment by jopasserat** [comment]
Nope it was the first ;)

Should be 6 on `mylocal`'s line

![screenshot from 2017-06-26 13-49-38](https://user-images.githubusercontent.com/472083/27540051-a1876e40-5a76-11e7-86e8-127a6e1d8109.png)

**Comment by romainreuillon** [comment]
Indeed, that's weird....

**Comment by romainreuillon** [comment]
On dev?

**Comment by romainreuillon** [comment]
Ok it is almost certainly cause by the refactoring towards environment providers....

**Comment by romainreuillon** [comment]
Fixed in 77a173ef91a0cd8db02742aac79e42ed74c7ef94.
