### ISSUE TITLE
Repository over its data quota

### ISSUE THREAD

**Issue by julienperret** [openmole/openmole#222]
I have problems when pulling from the repository:
This repository is over its data quota. Purchase more data packs to restore access.

Apparently, there is a 50 GB limit on git-lfs data storage.
I am not a member of the openmole organization so I cannot check but here is how:
https://help.github.com/articles/viewing-storage-and-bandwidth-usage-for-an-organization/
There is also information here:
https://help.github.com/articles/about-storage-and-bandwidth-usage/

Do you have anything planned about this?
Split the repo?
Create a git-lfs repository at ISC-PIF?
Purchase data?

**Comment by jopasserat** [comment]
No worries we're on it 😉

On 4 July 2017 14:13:29 BST, Julien Perret <notifications@github.com> wrote:
>I have problems when pulling from the repository:
>This repository is over its data quota. Purchase more data packs to
>restore access.
>
>Apparently, there is a 50 GB limit on git-lfs data storage.
>I am not a member of the openmole organization so I cannot check but
>here is how:
>https://help.github.com/articles/viewing-storage-and-bandwidth-usage-for-an-organization/
>There is also information here:
>https://help.github.com/articles/about-storage-and-bandwidth-usage/
>
>Do you have anything planned about this?
>Split the repo?
>Create a git-lfs repository at ISC-PIF?
>Purchase data?
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openmole/openmole/issues/222

-- 
Jonathan Passerat-Palmbach, PhD
Research Associate
Department of Computing
Imperial College London

South Kensington Campus
Huxley Building - room 344
180 Queen's Gate
London SW7 2AZ

https://jopasser.at

**Comment by jopasserat** [comment]
Fixed in dev by 8b5e1e3214570ccd5c5048261d46d17271f28e5c

If you don't want to make a fresh clone, you'll need to update the variables in your local git repo.

`git config --local lfs.url https://gitlab.iscpif.fr/openmole/openmole.git/info/lfs`

Should do
