### ISSUE TITLE
PyQt application

### ISSUE THREAD

**Issue by julienperret** [openmole/openmole#223]
In order to distribute a code initially coded as a *QGIS plugin*, I created a *Python* application using roughly  the same code as the *QGIS plugin*. Unfortunately, that means that I have dependencies on *QGIS* modules and *PyQt(5)* modules.
*CARE* actually handled that quite beautifully (with an archive of 800MB though). Worked almost the first time locally but on a remote *openmole* instance it failed with a nasty error:
**QXcbConnection: Could not connect to display**
**proot terminated with signal 6**

The thing is that apparently, even though I can run a QGIS application without a GUI, it still, somehow, tries to connect to a display.
After a quick search, I found a [workaround](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037):
I just had to run my Python application inside *xvfb* (X virtual framebuffer) so my *CARE* command became:
`care -o myapp.tgz.bin xvfb-run python3 app.py data_in data_out`
(I removed the -r and -p parameters for clarity)

So my questions are: 
* did I miss something?
* do you have a better solution?
* if not, does it deserve to appear in the documentation somewhere?

PS: the code (the app, the plugin and the workflow) is [here](https://github.com/mbrasebin/UrbanFabricAnalysis/tree/master_splitcode)

**Comment by romainreuillon** [comment]
I didn't know this workarround, that's nice ! It totally deserves its
spot in the doc, could you add an entry in the FAQ (on the new doc)
about it ?

**Comment by julienperret** [comment]
OK, I'll get to it.
Should I infer that there is no better solution at hand?

**Comment by jopasserat** [comment]
It seems to be a bug from QGis trying to access the display server even if you didn't asked for a GUI (or is there no explicit way to run without GUI?).
I guess CARE captures the `DISPLAY` environment variable that is then reused when re-executing the archive. Of course, the execution environments are different so the value of `DISPLAY` on the computing node makes no sense in this context.

It seems that your workaround is a great one!
Only thing you could try is editing the `re-execute.sh` script within the CARE archive and see whether removing some env variables do the trick.

But it seems that you'll have to complain upstream to QGis if it's truly something they could avoid in their non-GUI mode :wink:

**Comment by julienperret** [comment]
There is an explicit way to run without a GUI in the [QgsApplication constructor](www.qgis.org/api/classQgsApplication.html) but it doesn't seem to do the trick. Maybe by also using the platformName parameter as "server"...

I'll try a few things before adding an entry in the FAQ.
Thanks for the input guys!
