### ISSUE TITLE
Inconsistent authentications management in Console and GUI mode

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#224]
I just noticed while going over the environments documentations that this kind of syntax to set up authentications in Console mode was syntactically valid:

```scala
EGIAuthentication() = P12Certificate(encrypted, "/path/to/your/certificate.p12")
```
but don't create the same entries in the workspace as the GUI would:

![screenshot from 2017-07-15 14-04-03](https://user-images.githubusercontent.com/472083/28239538-84bdc5b2-6966-11e7-9e6d-ebd4bfcf26d6.png)

Do we want to maintain the possibility to set up authentications via the Console?

**Comment by romainreuillon** [comment]
Fixed in a2982aaafc24f8511c59a774f725a14a0401a4ec
