### ISSUE TITLE
Add ExplorationTaks : Sensitivity Analysis One factor at a time

### ISSUE THREAD

**Issue by chapinux** [openmole/openmole#226]
the "one factor at a time" exploration  is a very common Experimental Setup of Sensitivity Analysis.
The setup is simple: 
You have n parameters
Each parameter p vary within  an interval  [pmin;pmax] and has a nominal value p0.

The exploration consists in making p vary within its domain, **every other parameter being kept as their nominal value**, and doing that for **every parameter**   (hence the name "one factor at a time")

The exploration task syntax could be something like 
```

ExplorationTaskOneAtATime (
    (i in (0 to 10 by 2), nominalValue = 8  ) x
    (j in (0.0 to 5.0 by 0.5), nominalValue = 3.2 )  ) 

```

**Comment by chapinux** [comment]
Maybe an exemple to be totally clear : 
the following task 
```
ExplorationTaskOneAtATime (
    (i in (0 to 4 by 2), nominalValue = 2  ) x
    (j in (0.0 to 2.0 by 0.5), nominalValue = 1.5 )  )

```
should produce the following parameters sets: 

_(i is fixed to nominalValue, j vary)_
i=2 , j=0.0
i=2 , j=0.5
i=2 , j=1.0
i=2 , j=1.5
i=2 , j=2
_(j is fixed to nominal value, i vary)_
i=0, j=1.5
i=2, j=1.5
i=4, j=1.5

**Comment by guillaumecherel** [comment]
It's simple but not a very good modelling practice, it misses entirely possible interaction effects between parameters. In Openmole we should promote good, rigorous modelling practices.
Global sensibility analysis (Saltelli) and Screening methods (Campolongo) are better suited for capturing effects on parameters on the model output, including interactions. We have already used Global sensitivity in openmole, but we still need to make it more easy to use. For example, we could design a "GlobalSensitivityAnalysis" task that, given a model and some parameters run the workflow necessary to perform the analysis from A to Z, returning the sensitivity indices for each parameter.

**Comment by romainreuillon** [comment]
I do agree, but it is still a common practice among modelers and presently hard to achieve in OpenMOLE. I think we should make it clear that it is not very rigorous in the doc.

**Comment by JusteRaimbault** [comment]
I think combining DirectSamplings should allow to do that easily ; adding this task would help the user to do it transparently ?
I agree with @guillaumecherel that it is quite dangerous to begin integrating bad practices into methods, with the justification that some communities do it, even with warnings in the documentation.
The proposition 1) of @chapinux would for me be interesting to indeed justify that we do not implement such methods, but it is a very tricky issue : how do we know that it "fails" ? when the interaction between parameters produces counter-intuitive results ? (necessitates expert knowledge on the model) or when they are inversions of the qualitative behavior along one parameter when other change ? They are many ways to formulate the problem and I'm afraid it may even depend on the field or on the model.

**Comment by samthiriot** [comment]
just to trace why we ended working on a method such as the Morris one. 
first of all, it is not said to be a sensitivity method, but rather a *screening* method. Let's quote someone to backup the validity of the term:
> Screening methods are preliminary numerical experiments whose purpose is to isolate the most important factors from amongst a large number that may affect a particular model response. By using screening methods, factors can be ranked in order of their importance. However, the percentage of the output variation that each factor is accounting for cannot be quantified. [Pappenberger and Vandenberghe, 2007. Sensitivity analysis, guidance manual. EU Harmoni-CA Project.]

**Comment by JusteRaimbault** [comment]
"Ironie du sort", I actually need to do the "one-factor-at-a-time" sampling proposed by @chapinux  and writing it as a sampling is rather dirty or cryptic - it would be indeed useful to have this primitive

**Comment by JusteRaimbault** [comment]
@chapinux your dreams came true, [553190e40](https://github.com/openmole/openmole/commit/553190e404b1649abd2c76bcc725ce938aaff7e2) implements this feature.
DSL syntax : 
OneFactorSampling(FACTOR1 nominal VALUE1, ..., FACTORn nominal VALUEn)
Still needs to be documented though, I'm opening an other issue for that
