### ISSUE TITLE
Site issues

### ISSUE THREAD

**Issue by AKTheKnight** [openmole/openmole#227]
Creating a single large issue for all the issues I have spotted on the site.

Bugs:
- [x] Screen width ~840px Header cuts over first H1 on page (Links drop below logo)
- [x] Screen width ~840px Footer headings and logo and text all become overlapped and misaligned
- [x] Screen width <768px Header and Footer links all disappear (Mobile nav not displaying?)
- [x] Screen width<1150px Sidebar overlapped with text (http://openmole.org/How+to+Contribute.html)

Cosmetic:
- [x] Run, Explore, Scale buttons do not line up vertically (http://openmole.org/index.html)

I will add to this any other things I find, and go through and mark off any I fix in a fork

**Comment by mathieuleclaire** [comment]
Commits 13818db76836f0525dfc0324886c1bcc6a2b2a22 to 80a7fa15970c332131804833185580478d75cdac fix it
