### ISSUE TITLE
UDocker Task

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#233]
Integrate and document udocker into an OpenMOLE task.

**Comment by jopasserat** [comment]
Solved in https://github.com/openmole/openmole/commit/b9d971689c28c2e4d7ebbd461f7f0ea3d24dbecb, https://github.com/openmole/openmole/commit/dca0f08e62a732fac685ecafba2165fa620b92d9 and https://github.com/openmole/openmole/commit/a3ffa688a228b00c9f7de6d9c5e7e51caab7b593
