### ISSUE TITLE
Improve FAQ

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#237]
- [x] automatically generate table of contents at the top of section
_(see http://www.lihaoyi.com/Scalatex/#GeneratingaTableofContents)_

- [x] improve layout (spacing between paragraphs in CSS?)

**Comment by mathieuleclaire** [comment]
#237 fixes it

**Comment by jopasserat** [comment]
commit ID? ;)

**Comment by mathieuleclaire** [comment]
sorry. Updated
