### ISSUE TITLE
Automatically generate side menus in documentation pages

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#240]
Similarly to #237 we should be able to automatically generate the entries of the side menus using [ScalaTex's table of contents](http://www.lihaoyi.com/Scalatex/#GeneratingaTableofContents).

This impacts the following files:
  - [SideMenu.scala](https://github.com/openmole/openmole/blob/master/openmole/bin/org.openmole.site/jvm/src/main/scala/org/openmole/site/SideMenu.scala)
  - [package/site.scala](https://github.com/openmole/openmole/blob/master/openmole/bin/org.openmole.site/shared/src/main/scala/org/openmole/site/package.scala)

**Comment by mathieuleclaire** [comment]
How do you think I can get ```sect```s of a Page from a scala code ?

**Comment by jopasserat** [comment]
I didn't check his solution in details but I guess the implementation @romainreuillon wrote to solve #239 provides some building blocks for that.

**Comment by romainreuillon** [comment]
I don't think it would make it easy. I think a better aproach would be to tag the header we want in the menu with some kind of attribute in the dom and then querry the dom for those header using js (scala.js) code to generate the menu.

**Comment by mathieuleclaire** [comment]
The problem is: the method ```sect``` can only return a ```structure```, which gives all ```sect```s in all pages but with no matching information between pages and its sects.

**Comment by mathieuleclaire** [comment]
@romainreuillon : or just parse each page and getting all ```sect```s and injecting this the same way we do now.

**Comment by mathieuleclaire** [comment]
It seems bcfc4546ee5bc6811f98a32ba93262ac1f6ceb77 fixes it, right ?

**Comment by romainreuillon** [comment]
Indeed
