### ISSUE TITLE
New sampling methods not documented

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#242]
Hi,
the new sampling methods, like DirectSampling or Replication are not documented in the current documentation. The ExplorationTask should peharp's be wipped out from documentation. 

It seems to be a critical issue since we teach these methods in OpenMOLE classes. So it should be in a coming 7.2 version.

**Comment by mathieuleclaire** [comment]
It seems to be documented now https://next.openmole.org/Direct+Sampling.html. Is the only stuff to do is to replace all occurrences to direct sampling workflows by DirectSampling builders ?

**Comment by JusteRaimbault** [comment]
Replication was just documented, and there is no more reference to ExplorationTask, so we're good on this ! :octocat: :octocat:
