### ISSUE TITLE
Netlogo Documentation lacks

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#243]
Some methods in the NetlogoTask are not documented enough. For instance, the libraries, plugins, resource, embedWorkspace mechanisms are not mentioned.

**Comment by mathieuleclaire** [comment]
The issue #196 is included in this one

**Comment by mathieuleclaire** [comment]
These keywords should be explicitly explained:

workspace
launchingCommands
netLogoInputs
netLogoOutputs
netLogoArrayOutputs
netLogoFactory

**Comment by JusteRaimbault** [comment]
Added doc for script, launchingCommands, embedWorkspace, seed, netLogoInputs, netLogoOutputs, netLogoArrayOutputs.
workspace and netLogoFactory are not directly used.

**Comment by chapinux** [comment]
seems ok to me, we close ? @mathieuleclaire  @JusteRaimbault  ?

**Comment by mathieuleclaire** [comment]
A refactoring of the page needs to be done too. For now it looks like a tutorial page and not formal description of the Netlogo Task as it is done for other Tasks.

**Comment by JusteRaimbault** [comment]
Yes indeed, and also give precisions on how to embed extension.
I'm also on it asap

**Comment by JusteRaimbault** [comment]
[43891fc12abe9e13fe8b9ce9717c0c7d958389df](https://github.com/openmole/openmole/commit/43891fc12abe9e13fe8b9ce9717c0c7d958389df) refactors and competes the NetLogoTask doc.
