### ISSUE TITLE
The jar paradox

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#244]
All languages running on the JVM are supposed to be the most portable codes. And yet embedding a jar in OpenMOLE is not straight forward at all: https://next.openmole.org/Plugins.html. Most of users today still need us to prepare their jar-like experiences.

Today, embedding a Netlogo code is much more easy than embedding a java code. And yet, they both rely on jvm. How could we reduce the adoption time for scala/java programers in OpenMOLE ?

**Comment by romainreuillon** [comment]
For me it is not that hard if you are using SBT. I think the doc should be updated, beside that I am not sure, what do you suggest?

**Comment by romainreuillon** [comment]
An idea may be, would be to publish a SBT plugin which parametrise the SBT OSGi plugin with better default values...

**Comment by mathieuleclaire** [comment]
The best (as a user point of view) would to provide the opportunity to provide any jar (osgified or not). Isn't it possible to run this jar in a container to isolate it from the OpenMOLE platform OSGI bus ?

**Comment by romainreuillon** [comment]
The jar has to be OSGified the other way of loading jar can not be made reliable enough.

**Comment by jopasserat** [comment]
both sbt and OSGi are a complexity
an sbt plugin might be a good idea, as we could also reuse it to package new libraries used in OpenMOLE ourselves right?

would it be possible to call sbt from the WebUI to package a jar on the fly?

**Comment by mathieuleclaire** [comment]
In this commits 26ccf1038713e45e12c7df5693c9971705c3987a, a help text is appended in the jar wizard to encourage users to build an OSGI bundle. A direct link to the Plugins page it provided. 

Previously, an automatic plugin loading  (and the appropriate code ```pluginsOf```) had been provided in the jar wizard in case of OSGI bundle; otherwise the appropriate ```libraries += xxx``` code is generated.

These 2 points seem to me enough to close the issue.
