### ISSUE TITLE
[Plugin] [Doc] [GamaTask] Gama-plugin Documentation lacks

### ISSUE THREAD

**Issue by ciberdiego123** [openmole/openmole#246]
The methods in the GamaTask are not documented enough. For instance, the libraries, plugins, resource, embedWorkspace mechanisms are not mentioned.

**Comment by romainreuillon** [comment]
Could you try this doc ? 
https://github.com/openmole/gama-plugin/tree/8-dev

**Comment by reyman** [comment]
I'm agree we need to document more.
Romain make a huge work to recreate a stable version for 7 version, i work on the doc during this week.

**Comment by mathieuleclaire** [comment]
Peharp's we could add a page Plugins in the website listing all "certified" plugins and refering to its own documentation. Here for instance, it could refer to the github README.

**Comment by reyman** [comment]
Yep i'm agree @mathieuleclaire , and we need to differentiate the README from 7-dev working with OpenMOLE 7.1 from the actual 8-dev version.

**Comment by romainreuillon** [comment]
I like it!

**Comment by mathieuleclaire** [comment]
- [ ] So, could you provide me with a short abstract describing the plugin ? 
- [ ] I will add it to the new plugin page on the website. 
- [ ] And could you add some stuff in your README to precise which code works with which OpenMOLE version ?

**Comment by reyman** [comment]
Yep i do that in the next days and i post information here.
