### ISSUE TITLE
V7 dev release on github ?

### ISSUE THREAD

**Issue by reyman** [openmole/openmole#247]
Hi,
Could you we create a release for the 7 version in Github ? 
We need this url for gama plugin which works with dev version of openmole.
Thx :)

**Comment by romainreuillon** [comment]
Do you mean a tag ?

**Comment by reyman** [comment]
Yep, a tag then after that a release (based on this tag) like that : https://github.com/openmole/openmole/releases

**Comment by reyman** [comment]
Not possible ?

**Comment by reyman** [comment]
See here : https://gitlab.iscpif.fr/openmole/openmole/tags/v7.1
