### ISSUE TITLE
Accept Option[File] for "resources +="

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#25]
Some of my workflow tasks read some constants from a configuration file. A default configuration is packed into the jar file of my OpenMOLE plugin. Among more system wide configuration overrides in e.g. the users home directory, they can use a local configuration file in the current working directory of OpenMOLE. If such local configuration file exists, it must be declared as resource of the tasks which need it. Otherwise not. Therefore I used a ```val configFile: Option[File]``` for the configuration file path. Now I would like to add this file to the ```resources``` list of my ```ScalaTask``` (or ```SystemExecTask```). The only possibility that I see at the moment to do this is:
```scala
val _task = ScalaTask("// task code here")

val task = (configFile match {
    case Some(file) => _task.addResource(file)
    case None       => _task
  }) set (
    name        := "taskName",
    imports     += "com.andreasschuh.repeat._",
    usedClasses += (GlobalSettings.getClass, IRTK.getClass),
    inputs      += (tgtId, srcId),
    inputFiles  += (tgtSeg, segPre + "${tgtId}" + segSuf, symLnk),
    inputFiles  += (srcSeg, segPre + "${srcId}" + segSuf, symLnk),
    inputFiles  += (outDof, "${tgtId},${srcId}" + dofSuf, symLnk),
    outputFiles += (segPre + "${srcId}-${tgtId}" + segSuf, outSeg),
    outputs     += (tgtId, tgtSeg, srcId, srcSeg)
  ) hook CopyFileHook(outSeg, outSegPath) on parEnv
```
To avoid having to split the definition of the task up into two parts, I have tried to add another overload of the ```resources.+=``` function which accepts an Option[File] argument, but this surprisingly didn't work. In particular, I changed the ```org.openmole.plugin.task.external``` package object to the following:
```scala
trait ExternalPackage {

    lazy val inputFiles = new {
      def +=(p: Prototype[File], name: String, link: Boolean = false, inWorkDir: Boolean = true) = (_: ExternalTaskBuilder).addInputFile(p, name, link, inWorkDir)
    }

    lazy val outputFiles = new {
      def +=(name: String, p: Prototype[File], inWorkDir: Boolean = true) = (_: ExternalTaskBuilder).addOutputFile(name, p, inWorkDir)
    }

    lazy val resources =
      new {
        def +=(file: File, name: Option[ExpandedString] = None, link: Boolean = false, inWorkDir: Boolean = false, os: OS = OS()) =
          (_: ExternalTaskBuilder).addResource(file, name, link, inWorkDir, os)
        def +=(file: Option[File], name: Option[ExpandedString], link: Boolean, inWorkDir: Boolean, os: OS) = file match {
          case Some(resource) ⇒ (_: ExternalTaskBuilder).addResource(resource, name, link, inWorkDir, os)
          case None           ⇒
        }
        def +=(file: Option[File]) = file match {
          case Some(resource) ⇒ (_: ExternalTaskBuilder).addResource(resource, None, false, false, OS())
          case None           ⇒
        }
      }
  }
```
(Note: I added the third overload with only one Option[File] argument just because adding the second one didn't seem to work yet and to see if it has anything to do with the missing default arguments. However, I've learned that for a very strange reason the Scala compiler doesn't allow default arguments on more than one overload...)

OpenMOLE console error:
```
<console>:175: error: type mismatch;
 found   : Option[java.io.File]
 required: java.io.File
    resources   += configFile,
```

**Comment by schuhschuh** [comment]
Actually I could have left all the ```set``` part before the call to ```addResource``` afterwards. Only the immediate installation of a ```hook``` and setting the environment mapping change the type from task to something else on which I can no longer call ```addResource```. Would still be nice if a Option[File] was a suitable argument to the ```resources +=``` function.

**Comment by romainreuillon** [comment]
This is really specific, so I would advise a specific solution:
```scala
val o: Option[File] = None
val s = ScalaTask("...") set ( b => o.foreach(resources += _), .... )
```

**Comment by schuhschuh** [comment]
Interesting, that will do as well.

**Comment by romainreuillon** [comment]
Actually I am not sure my code works.... looking into it.

**Comment by romainreuillon** [comment]
This works:
val s = ScalaTask("...") set ( b => o.foreach(b.addResource(_)) )

**Comment by schuhschuh** [comment]
Thanks, I think that was the last bit of my latest OpenMOLE script that bugged me.
