### ISSUE TITLE
[Doc] Document global sensitivity analysis methods - Saltelli and Morris

### ISSUE THREAD

**Issue by chapinux** [openmole/openmole#253]
The text of the sensitivity analysis is useless now that we aim at getting rid of the most Exploration Tasks mentions as possible.

The only cool  remaining stuff is the animation , but the example code and text is boring 

-> get rid of the section 
or 
-> make a real section with at least 2 strategies of sensitivity analysis  : 
one factor at a time and the non-crossed variation of several factors i.e. 
for param a and b , when a varies , b is fixed , when a varies, b is fixed, but a and b never conjointly vary

**Comment by JusteRaimbault** [comment]
I think this goes together with the implementation of new sensitivity analysis methods such as Morris, and with the discussion on "one factor at a time" we had in an other issue : this is thus a long term effort, so I postpone beyond milestone 8. :octocat: :octocat:

**Comment by JusteRaimbault** [comment]
Original issue is deprecated thanks to the new organisation of the doc by @helenea ; the issue is let open as new sensitivity analysis methods by @samthiriot must be documented, just renaming it

**Comment by JusteRaimbault** [comment]
Done during the CC by @chapinux - [34bf5ee](https://github.com/openmole/openmole/commit/34bf5ee3cf28984511976ddd886848fba2a15e09) implements this

**Comment by helenea** [comment]
Still need to specify the methods' parameters!!

**Comment by JusteRaimbault** [comment]
im on it

**Comment by JusteRaimbault** [comment]
[b41f30fd](https://github.com/openmole/openmole/commit/b41f30fdb4790c5f1318f63cc68c9eb4f67c34ae) implements this
