### ISSUE TITLE
File management in OpenMOLE doc is missing

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#254]
Manage files in OpenMOLE Task is crucial. And yet some key instructions are not in the doc. For instance I didn't find any reference to inputFiles / outputFiles functions.

**Comment by romainreuillon** [comment]
It is used in several places though: https://next.openmole.org/R+Script.html for instance..

**Comment by mathieuleclaire** [comment]
Sure, but someone developping in scala will not search in the R page ... it has to be described somewhere. Peharp's a page about Vals ?

**Comment by romainreuillon** [comment]
It is not implement nor useful for the ScalaTask since it can take Val[File] directly. May be some example should be provided if they are not already.

It should be explained here however:
https://next.openmole.org/Native+Packaging.html

**Comment by romainreuillon** [comment]
Done 1edbfddbd56a48bd15c7a3578462746db5ecfa62
