### ISSUE TITLE
Implement a per task execution view in GUi

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#255]
The total executed task doesn't make much sense now that we are using worflow builders. Refactor it to view a per task number of execution.

**Comment by romainreuillon** [comment]
The core part has been implemented in 4bbfdbb4c2559b965d329ab70363873014b0534b

The execution info by capsule in now accessible from the execution panel code.

**Comment by mathieuleclaire** [comment]
Is there still something to do in the GUI part ? It seems that every case class used in ExecutionPanel is based on capsules.

**Comment by romainreuillon** [comment]
The idea is to be able to visualise the running / done info on each capsule the execution panel instead of having a global count.

**Comment by mathieuleclaire** [comment]
merge with branch executions fixes it
