### ISSUE TITLE
Encoding problem in folders name

### ISSUE THREAD

**Issue by francoismaths** [openmole/openmole#256]
Dear OpenMole Team,
I’ve seen a bug concerning accent in folder names. 
I was working in a folder whose name contains an accent. In my workflow I use a hook to create a file to store a result, but the file was created in an other folder (whose name differs at the accent). 

To reproduce the bug :
create a folder with an accent (for example testé)
create a file (test.oms), with the following worflow  (it stores the variable i in a file named result). After execution, the result.txt file was stored in a folder name testÃ©.

val i = Val[Int]
val task= ScalaTask(
"""  val i = 2    """) set(
  inputs += (),
  outputs += (i), 
 )
val h = CSVHook( workDirectory / "result.txt" ,i )
task hook h

François.

**Comment by romainreuillon** [comment]
Fixed in https://github.com/openmole/openmole/issues/204
