### ISSUE TITLE
Regression on SSH based environments

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#261]
Exception logged to console 
`ERROR n.s.sshj.transport.TransportImpl - Received end of connection, but no identification received.`
and connections are multiplied.

Will investigate further.

**Comment by romainreuillon** [comment]
Any news about this bug? There is nothing obvious in the code.

**Comment by jopasserat** [comment]
I'll check it tomo. Only thing i could see in the history was the upgrade of sshj..

**Comment by mathieuleclaire** [comment]
Did you check it yester @jopasserat :) ?

**Comment by jopasserat** [comment]
Yep it should be ok now, I've fixed it in GridScale 804339d538b3de0a2faabdbaf96bd81b92f0fc40 and forgot to report it here ;)
