### ISSUE TITLE
[Doc] Refactor Method Documentation

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#263]
The exposed methods in documentation have heterogeneous abstraction levels. The methods should be exposed as main categories:
- Sensitivity analysis (with DirectSampling, Profiles),
- Diversity (with PSE),
- Optimization
- Calibration
- Data processing

**Comment by chapinux** [comment]
it appears that Calibration is optimization, and PSE is still single into the diversity Category.
We wait for Morris / Saltelli integration and OSE for closing

**Comment by helenea** [comment]
I proposed a different organization of the Explore section in the branch helene-dev, looks like this:

![image](https://user-images.githubusercontent.com/8794131/45034679-7157f300-b058-11e8-8b61-03c37a2229e3.png)

The old Direct Sampling page has been split into all the individual sampling pages, it's easier to visualize the existing options in my opinion.

**Comment by romainreuillon** [comment]
It seems integrated now. Shall we close this?

**Comment by JusteRaimbault** [comment]
closing this, refactoring done
