### ISSUE TITLE
Exception details

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#268]
Some exceptions are very verbose by default (EGI Errors, ScalaTask compilation errors...). Add a mechanism to display optional details on errors in the execution panel (in failed status and in env errors).

**Comment by mathieuleclaire** [comment]
Well, the verbose content comes from the ```message``` method from the Exception (https://github.com/openmole/openmole/blob/dev/openmole/gui/server/org.openmole.gui.server.core/src/main/scala/org/openmole/gui/server/core/ApiImpl.scala#L379). So how to shrink this ? By taking the first N elements of the message methods ? And what do we display optionaly ? The whole message AND the stack ?

**Comment by mathieuleclaire** [comment]
merge with branch executions fixes it
