### ISSUE TITLE
ScalaTask script compilation error "java.io.File with java.io.Serializable with java.langComparable"

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#27]
I have written a Scala function that constructs a puzzle piece for the copying of some files. Strangely, the Manifest type of the File prototype variables somehow changes during the data flow. The [first encounter](https://github.com/schuhschuh/REPEAT/blob/34d9f8eaf8ded8379ce865af815fd8b4232fa244/src/main/scala/com/andreasschuh/repeat/workflow/PreProcess.scala#L90) of my [CopyFilesTo](https://github.com/schuhschuh/REPEAT/blob/34d9f8eaf8ded8379ce865af815fd8b4232fa244/src/main/scala/com/andreasschuh/repeat/puzzle/CopyFilesTo.scala) constructed puzzle still compiles fine, but the second fails with an error because the type string is ```java.io.File with java.io.Serializable with java.langComparable``` with missing type parameter for the ```Comparable``` interface. I have linked the related source code of my OpenMOLE plugin for reference.

[A hack to fix this issue](https://github.com/schuhschuh/openmole/commit/19c670e21ae7e3fcf99f2bda71220d3a88f85331) is in my fork of OpenMOLE. Basically it just drops all the " with " parts from the type string, which should never be needed anyway. Just wondering what's the actual underlying cause for this issue and how to fix it properly and permanently.

**Comment by romainreuillon** [comment]
Could you link the workflow which is not working?

**Comment by romainreuillon** [comment]
It's already there, sorry...

**Comment by romainreuillon** [comment]
I cannot test you workflow, I getting some initialisation error. Could you try to check which task changes the `type` of the prototype?

**Comment by romainreuillon** [comment]
I think I've got a lead, in ClassUtils, when you do:
```
OpenMOLE>intersectionArray(Seq(classOf[File], classOf[File]))
res14: scala.reflect.Manifest[_] = java.io.File with java.io.Serializable with java.lang.Comparable
```

However this code is called in case of aggregation transition and convergent transition but I don't see any in you workflow....

**Comment by romainreuillon** [comment]
This produce the same thing:
```
intersection(Seq(classOf[File]))
res16: scala.reflect.Manifest[_] = java.io.File with java.io.Serializable with java.lang.Comparable
```

Which is computed by strainer capsule also. Do you use any strainer?

**Comment by romainreuillon** [comment]
I am not sure yet if we have to fix that on the type system side or on the scala task compilation one. Could you send the full compilation error you're having?

**Comment by romainreuillon** [comment]
Things start to be clearer. The pb should be fixed from both side. The intersection method should take into account the type arguments of the manifest and not strip it when possible. The scala compilation should take into account type arguments, but I am not sure how yet.

**Comment by schuhschuh** [comment]
Thanks for tracking it down so quickly. 

> Do you use any strainer?
Yes, the ```CopyFilesTo``` wraps the ScalaTask in a strainer capsule. Also, I was previously wrapping the ExplorationTask in a strainer capsule as well to pass through the single ```refIm``` that is copied before the exploration starts.

**Comment by romainreuillon** [comment]
It should be ok now. I got rid of some type magic inferring the least common super-type in OpenMOLE but it cannot be done thoroughly. Could you test it?

**Comment by schuhschuh** [comment]
Works perfectly, Thanks!
