### ISSUE TITLE
Move file to parent folder does'nt work anymore

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#273]
Moving a file to an parent folder doesn't worke anymore in the GUI.

**Comment by mathieuleclaire** [comment]
I cannot reproduce the bug. Moving a file or a directory into a directory (targeting a blue square representing a folder) works properly. It this you are talking about ?

**Comment by romainreuillon** [comment]
You may try to move it to a parent folder. Does it work?

**Comment by mathieuleclaire** [comment]
What are you graphically targeting ? A name in the path string on top of the file navigator or a blue square ?

**Comment by romainreuillon** [comment]
I can't see any blue square for the parent folder. I am targeting the super folder in on top: for instance fo in "foo | bla"
