### ISSUE TITLE
[Plugin] [RTask] RTask: optionaly run on local R installation?

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#276]
Hey,

currently the RTask is relying on docker containers - and that works very well with all the obvious benefits of it. 

Yet opening and closing the container at every run (a few hundreds of megabyte to open at every execution of the task) might slow down the execution of the task. 

In fact, when the target execution environment does support R with the required packages, running R directly instead of a container might be way more efficient.

Would it be possible to provide the possibility to run on a R installation instead of a container? Something like an optional argument to RTask which would be false by default? Do you think that would be relevant and/or easy to do?

Tks

**Comment by JusteRaimbault** [comment]
I guess in that case the best is to use a SystemExecTask ? but it's sure less ergonomic than the RTask.
I'm not sure if wrapping a SystemExecTask as a local RTask would be easy/relevant to do (and then add a "withDocker" option in the RTask, that switches between the current RTask and a simplified local one)

**Comment by jopasserat** [comment]
Yes agree with @JusteRaimbault you'd be better off with a `SystemExecTask` for this purpose.

@samthiriot I guess you don't need to reinstall any package on your local R? I see little value of customising it further apart to benefit from the `rInputs/rOutputs` but not sure how @romainreuillon did that and if it could be applied to an `RTask` built on top of a `SystemExecTask`.

**Comment by JusteRaimbault** [comment]
I think we agreed to keep the RTask as a docker task only ; local R scripts should be run with a SystemExecTask ; hence closing the issue.
