### ISSUE TITLE
[Doc] Uniformize Tasks description in documentation

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#277]
There are more or less details in the description of tasks in the documentation, and the approach taken may be slightly different (example, tuto-like, etc). What about uniformizing the description by first detailing the full syntax and arguments in a similar way for all tasks, and then proceed with the examples ?

**Comment by JusteRaimbault** [comment]
I propose the following standardization : 
  - short general overview of the Task and purpose (why, how, philosophy, which audience, etc.), including restrictions on systems e.g.
  - standard description of syntax : constructor arguments, with types, optional or mandatory, description ; and specific properties to be changed with set (idem).
  - examples / tuto / particularities / tip (what we already have for most tasks)

the R task has now this kind of structure, to give an example (with some scalatex typos, sorry) : https://next.openmole.org/R.html
(and also the NetLogo)

**Comment by guillaumecherel** [comment]
Good suggestion! We could put things like the system restrictions and other technical prerequisites in a section of there own called "Prerequisites" to make them more salient.

I would find handy to have the standard description of syntax of all tasks, hooks, etc. in a separate place, like an api doc. We would then have different docs for different purpose:
- The doc that explains the concepts for people who want to learn about them and how to use them. This would look like the current doc on openmole.org and show the short general overview of the concept (task, hook, etc.) and purpose, and examples / tuto / tips.
- The api doc that gives a shorter technical and standard description of each element for users who already know about the concepts but need to be reminded all the time of the types and arguments and technical details of each (I could use that!). This would look like the scala api doc contain obviously the name and types and also technical prerequisites (like system requirements). I think this one should be generated automatically with the scaladoc, such that we can write this information directly in the source code.

**Comment by jopasserat** [comment]
Agree with @guillaumecherel this is the perfect opportunity to make a distinction between user guide and documentation (API).
And :+1: for suggesting building on the `scaladoc` for that. 
Maybe a good opportunity to start planning the decommissioning of ScalaTex? (come on we all know it has to happen.. could this help to transition smoothly? https://github.com/47deg/sbt-microsites/issues/154)

**Comment by JusteRaimbault** [comment]
I remove that from the 8 milestone as it is a long term effort, that furthermore needs deeper reflexion.

**Comment by JusteRaimbault** [comment]
Documentation is rather uniform now, closing this old sea serpent
