### ISSUE TITLE
use JAVA_HOME in the openmole script

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#283]
Hey,

In the openmole script used to start openmole, the "java" command is hardcoded, so openmole always uses the default java command. 

I propose to detect the presence of the JAVA_HOME environment variable and, if it is defined, to rely on it.

**Comment by samthiriot** [comment]
If the principle is OK, I will submit a merge request

**Comment by romainreuillon** [comment]
Fair enough.

**Comment by jopasserat** [comment]
Are we sure it's valid for all systems? Like classic Mac issues you know...

**Comment by samthiriot** [comment]
good point... seems like the environment variable does exist: https://www.mkyong.com/java/how-to-set-java_home-environment-variable-on-mac-os-x/

if the bash syntax is the same, it should work then?

**Comment by samthiriot** [comment]
Ok; I was more thinking of using "java" as a default behaviour, and only if JAVA_HOME is defined, to use it

**Comment by romainreuillon** [comment]
Sounds conservative enough for me.
