### ISSUE TITLE
download docker containers over a proxy

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#284]
Hello !

Is there an option today to accept an http proxy for the docker container task? 

Tks !

S.

**Comment by romainreuillon** [comment]
No it is not yet coded. OpenMOLE uses udocker https://github.com/indigo-dc/udocker. If there is an option is this soft it wouldn't be terrible to add in OpenMOLE.

**Comment by samthiriot** [comment]
perfect, thanks; I'm investigating udocker.

**Comment by samthiriot** [comment]
There is not only udocker trying to connect the net. The ContainerTask itself does it to load the manifest (and other calls). So if I add support for a proxy, I've to make it in both the task and udocker. 

Are you ok with adding an openmole command line parameter for the proxy? 

tks

**Comment by romainreuillon** [comment]
Indeed you're right. OpenMOLE doesn't depend on udocker to download the image and layers it need. Therefore it can be fixed directly in the ContainerTask.

**Comment by romainreuillon** [comment]
No, I think you're idea of having a global setting is better. That's why I think we should add a new "service" in OpenMOLE regarding the network. Services are generally configured at the start of the application and are passed all along the stack to every components.

**Comment by samthiriot** [comment]
A very simple option might be to rely on environment variables.

http.proxyHost, http.proxyPort, https.proxyHost and https.proxyPort are supposed to do the job in Java. 

After that we might very easily configure all the apache HttpClient, either by calling 
`HttpClients.createSystem() ` instead of `HttpClients.custom()` (reads these system properties and configures proxy if necessary), or in any builder call the `useSystemProperties()` method, like `HttpClient httpClient = HttpClientBuilder.create().useSystemProperties().build();`. 

Then other components which require an access to the network would also read the enrivonment variable and react accordingly. 

That would we a minimalist patch to fix this issue. What do you think? Maybe there are other services you would like to implement in a NetworkService? 

tks !

sources:
* https://stackoverflow.com/questions/5165126/without-changing-code-how-to-force-httpclient-to-use-proxy-by-environment-varia
* https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClients.html#createSystem()
* http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html#useSystemProperties()

**Comment by romainreuillon** [comment]
I think we should avoid global variable in OpenMOLE. So I am really not keen on using environment variables. The best way is to pass the wanted behaviour as an argument where it is needed. The services are the way to achieve that in OpenMOLE. You can check for instance the service to create temporary files "NewFile" or the one to provide threads "ThreadProvider".

However it might seem to involve a bit of code (not that much so) to change that. If you don't feel comfortable giving it a try, I may sketch something to help you start with this.

**Comment by samthiriot** [comment]
I submitted an attempt to code the network service. 

To be honest, there were a few files to change ;-)
