### ISSUE TITLE
the failure of the installation of R packages is not detected 

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#286]
When R fails to install a package, the error is not detected, so the process continues with a wrong docker image. The error is only detected at execution time. But as the udocker image is cached, then all the subsequent trials will fail.

**Comment by samthiriot** [comment]
Seems like the R command `install.package` is not throwing an error but just issuing a warning when a package fails to be installed. 

source: https://stackoverflow.com/questions/26244530/how-do-i-make-install-packages-return-an-error-if-an-r-package-cannot-be-install

**Comment by JusteRaimbault** [comment]
I was wondering, but is intercepting R errors/warning in line with the scripting language philosophy ? (if you do a R -f ... it will break at runtime, but in an interactive mode you run sequentially your instructions whatever they do)

**Comment by samthiriot** [comment]
@JusteRaimbault it's possible to intercept in R the warning and change them into errors using try / catch or a hook. 

But it's not a good practice, as warnings are not supposed to mean anything else than warning - they might be issued for a lot of meaningless reasons. 

That's why I think it's better just to follow the proposal discussed here: independantly of warnings, what does matter is the possibility to ultimately load the library.

**Comment by samthiriot** [comment]
@JusteRaimbault  what I did in other projects was to intercept warnings and redirect them to the error stream of the caller application. Makes sense, and non intrusive (does not break the control flow of the appli)
