### ISSUE TITLE
udocker requires python 2.7 and not 3 => document requirement

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#288]
Hello,

Running the tasks relying on containers require udocker to work. In practice udocker is not working with a  python 3 installation, it's only working with python 2 (even if that's not yet explicitely documented, see issues https://github.com/indigo-dc/udocker/issues/131 and https://github.com/indigo-dc/udocker/issues/77) .
So it means a user who has "python" pointing on a python3 installation will face unclear technical errors .

I suggest to add this information clearly in the installation guide of openmole. 

S.

**Comment by romainreuillon** [comment]
Yes, that's a big limitation. I didn't find a way to make it work seamlessly with python 2 and 3.

@jopasserat and I were thinking about implementing a minimal udocker equivalent in Scala.

**Comment by samthiriot** [comment]
I guess, we should at least make it able to run in an environment in which "python" is not defaulting to "python3" but "python2". More and more environments will be configured like this.

It's about finding a workaround the first line of the udocker file which starts with `#!/usr/bin/env python` and should start with `#!/usr/bin/env python2` instead.

Options:
* fix in into the udocker repo: there is an issue and a merge request for that, but it's sitting there since forever
* fork the udocker repo and patch it into this fork
* patch this line when the plugin is built
* instead of calling "udocker <args>" at runtime, call "/usr/bin/env python2 udocker <args>" instead

I would tend to vote for the last one, maybe because that's something I can propose a merge request for; the other options are beyond by scope ^^

**Comment by romainreuillon** [comment]
I do vote for the last option as well.
