### ISSUE TITLE
[Enh] [Plugin] New CSVToMapSampling or alternatives

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#29]
In my plugin, I would like to read a number of key => value mappings from a CSV file. For each row of the file, one external task should be executed with the key placeholders in the command line string replaced by the actual arguments.

For example, the CSV file:

```
a,b
0,foo
1,bar
```

and given a command line template string `myprog -a ${a} -b ${b}`, read from a separate configuration file which influences the workflow that is constructed, the following two commands should be executed by a (Scala)Task:

```
myprog -a 0 -b foo
myprog -a 1 -b bar
```

With the current CSVSampling, I can only map known columns to workflow variables. In this case, however, I don't know the names and number of columns at compile time. I was thinking something such as the following would be suitable:

``` scala
val config = Val[Map[String, String]]
val template = Val[String]

val sampling = CSVToMapSampling("/path/to/config.csv", config)

val task = ScalaTask("interpolate(template, config).!") set (
    imports += ("scala.sys.process._", "myplugin.Utils.interpolate"),
    inputs += (template, config)
  )

val ex = ExplorationTask(sampling) -< task start
```

I had a look at the implementation of `CSVSampling`, `CSVToVariables`, and their respective builders. It looks not too complicated. However, I have some difficulties to implement it myself (see [here](https://github.com/schuhschuh/REPEAT/commit/3480840df5560923c3f1c0792a8a5505670c22ee)).

The compilation error I am getting with this is:

```
[error] /Users/as12312/Documents/Projects/REPEAT/src/main/scala/com/andreasschuh/repeat/core/CSVToMapSampling.scala:57: type mismatch;
[error]  found   : org.openmole.core.workflow.data.Variable[scala.collection.immutable.Map[String,String]]{val prototype: org.openmole.core.workflow.data.Prototype[scala.collection.immutable.Map[String,String]]; val value: scala.collection.immutable.Map[String,String]}
[error]  required: Iterable[org.openmole.core.workflow.data.Variable[_]]
[error]       line ⇒ Variable(p, line.view.zipWithIndex.map {
```

It seems the return type is not compatible with what I am creating. Any suggestions on how to go about realising this are welcome. My experience with Scala iterators is zero...

**Comment by schuhschuh** [comment]
Ah, I get it. If I put the single ```Variable``` into a container such as a ```List```, I have an iterable for the iterator...

**Comment by schuhschuh** [comment]
And seems to work fine:
```
OpenMOLE>import com.andreasschuh.repeat.core._
import com.andreasschuh.repeat.core._
OpenMOLE>val config = Val[Map[String,String]]
config: org.openmole.core.workflow.data.Prototype[Map[String,String]] = config: scala.collection.immutable.Map[java.lang.String, java.lang.String]
OpenMOLE>val sampling = CSVToMapSampling("Config/ireg-ffd.csv", config)
sampling: com.andreasschuh.repeat.core.CSVToMapSamplingBuilder = com.andreasschuh.repeat.core.CSVToMapSamplingBuilder@7680beac
OpenMOLE>val task = EmptyTask() set (inputs += config, outputs += config) hook ToStringHook()
task: org.openmole.core.workflow.puzzle.PuzzlePiece = PuzzlePiece(Slot hash 164983718 of emptyTask1,List(),List(org.openmole.plugin.hook.display.ToStringHook$$anon$2$$anon$1@62ccbd95),None,None)
OpenMOLE>val ex = ExplorationTask(sampling) -< task start
warning: there was one feature warning; re-run with -feature for details
ex: org.openmole.core.workflow.mole.MoleExecution = org.openmole.core.workflow.mole.MoleExecution@4aedac7f
OpenMOLE>{config=[(ds,2.5), (be,0.0)]}
{config=[(ds,2.5), (be,1.0E-4)]}
{config=[(ds,2.5), (be,5.0E-4)]}
{config=[(ds,2.5), (be,0.001)]}
{config=[(ds,2.5), (be,0.005)]}
{config=[(ds,2.5), (be,0.01)]}
{config=[(ds,2.5), (be,0.05)]}
```
Interested in adding this to OpenMOLE itself ? I'd send a PR then

**Comment by jopasserat** [comment]
That looks great! If you could ship it with a bit of documentation inserted in this file https://github.com/openmole/openmole/blob/master/openmole/bin/org.openmole.site/src/main/scalatex/org.openmole.site/documentation/console/Sampling.scalatex 
as a subsection of "Exploring Files", same level as "CSV files Sampling" that would be even better :)

**Comment by schuhschuh** [comment]
Yes, I thought so. I just wasn't gonna touch any doc file while your doing the complete overhaul. But now that this file isn't likely to change all over, I'll  edit it.

**Comment by romainreuillon** [comment]
Hi,

I think this sampling is specific since it can be used only by scala tasks. I would argue not to include it in the main OM distribution. But maybe I misunderstood, what would be the use of it in a general case?

Romain

**Comment by jopasserat** [comment]
It doesn't look specific to the ScalaTask, it deals with variables from the dataflow.
https://github.com/schuhschuh/REPEAT/blob/96c59cd98476eb619fa4386a2978341355678c75/src/main/scala/com/andreasschuh/repeat/core/CSVToMapSampling.scala
It's sort of an extension to the CSV file where you would only have two columns key -> value.

**Comment by romainreuillon** [comment]
But it uses a scala map which is accessible only in scala code.

**Comment by schuhschuh** [comment]
Yes, it's quite likely that it's only useful for a ScalaTask or other compiled JVMTask or non-compiled task (you could have a PythonTask or PerlTask too if you wanted to ;-) ). It certainly wouldn't be that useful for a SystemExecTask b/c in that case you will need to know the number of arguments.

But why would you not include basic tools in a OpenMOLE plugin shipping with OpenMOLE that is of general use ? The types of tasks used are anyway limited. In most cases it's either a ScalaTask or SystemExecTask. I don't see much other useful tasks.

Personally I am very fine having it just in my plugin.

**Comment by romainreuillon** [comment]
Actually we might use it in system exec task if we transform the scala map in a java map so we can use it directly in the groovy codes for variable expansion. If we change that it might be of general use.

Two questions though:
1/ Would it be disturbing for new-comers to have several way to use their CSV in OpenMOLE?
2/ It bypasses the OpenMOLE type system and exposes a more Pythonic way of accessing to variables (dictionary), is it a pb?

**Comment by jopasserat** [comment]
1/ I think it's not a problem as long as we make it clear that it's for a very specific type of CSVs (maybe even rename to something without CSV to stress on the Map aspect).

2/ Not quite sure to understand why it bypasses the OpenMOLE type system? I mean we have access to Maps in Scala already.

**Comment by schuhschuh** [comment]
My original problem is that I want to write a generic workflow that can be configured via CSV and config files. I don't want to restrict myself to a particular use case or external software which is being evaluated. The other option would be to actually write a OpenMOLE workflow for each expected experiment by hand, but this repetition I want to avoid and also remain flexible.

Also, I think type safety might be overrated here. Therefore I restricted it to string arguments. Anyway, any ScalaTask I write suffers from the fact that OpenMOLE can by no means verify that I use the types correctly within my task script. The errors only show up during runtime (which performs the compilation step then), but not before I actually execute the workflow... that sounds pretty Pythonic to me ;)

**Comment by schuhschuh** [comment]
> Actually we might use it in system exec task if we transform the scala map in a java map so we can use it directly in the groovy codes for variable expansion. If we change that it might be of general use.

I now understand how you meant to use it in a SystemExecTask this way. Indeed that would be useful, too. The general use should be to explicitly refer CSV columns with separate data flow variables for most workflows as is possible with CSVSampling. This new sampling that stores each CSV row in a Map (may well be of Java type) would be useful for writing configurable workflows, where parts of the command arguments are input from the user (always a String to be expanded) together with the corresponding CSV file storing the different variable expansions (which would naturally just be treated as Strings as well b/c of their use in a command-line).

But there may well be alternative solutions to my initial problem that could be realised with the existing sampling. For example,

1. Read CSV header
2. Create variable for each column
3. Instantiate CSVSampling
4. Use indexed list of column names within ScalaTask to assemble command to be executed

This was actually my first idea before even considering implementing a sampling myself. The problem I thought I was facing here is that I cannot programmatically create variables in a loop because they would all have the same ```name``` attribute and therefore conflict in the workflow.

But now I wonder if I could use a variable of type ```Array[String]``` instead of the map together with the list of column names from the header. But what I cannot do is assign the individual column to a certain entry in this array...  ok

I've played with this (demonstrative) snippet, but without success to get the functionality I need. I think I either require a new sampling such as CSVToMapSampling (which I have in my plugin, so fine) or a way to rename variables after declaration. In my plugin I anyway have to refer to them inside the ScalaTask's using ```${var.name}```.

```scala
val header = Seq("a", "b", "c")
val row = Val[Array[String]]

val sampling = CSVSampling("config.csv")
header.view.zipWithIndex.foreach((column, c) => sampling.addColumn(column, row(c)))

val columnName = Val[Array[String]]
val task = ScalaTask("""
val a = row(columnName.indexOf("a"))
val b = row(columnName.indexOf("b"))
val c = row(columnName.indexOf("c"))
""")
row.foreach(task.addInput(_))
```

**Comment by romainreuillon** [comment]
FYI: the syntax val v = Val[Int] is a syntactic sugar for val v = Val[Int]("v"). The parameter will be the actual name of the variable.

**Comment by schuhschuh** [comment]
Ha, good to know!

**Comment by schuhschuh** [comment]
So an alternative to ```CSVToMapSampling``` might be:

```scala
import org.openmole.core.workflow.data.Prototype
import scala.collection.mutable.ArrayBuffer

val header = Array("a", "b", "c") // Read from CSV file
var variables = ArrayBuffer[Prototype[String]]()

val sampling = CSVSampling("config.csv")
header.view.zipWithIndex.foreach { case (name, c) =>
  variables += Val[String](name)
  sampling.addColumn(name, variables.last)
}

val variableNames = Val[Array[String]]
val task = ScalaTask("/* */")
task.setDefault(variableNames, header)
variables.foreach(task.addInput(_))
```

**Comment by JusteRaimbault** [comment]
Current CSV sampling associates prototypes to columns in the csv, so we can close the issue.
