### ISSUE TITLE
[GUI] OpenMOLE process stops when launching with nohup --remote

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#297]
Here's the way to reproduce.

Start a fresh OM instance with `nohup openmole --remote &`.
The instance starts, you can login to your workspace.
Run a workflow, as soon as the workflow starts the process is suspended.

`jstack` cannot reach it: 

```
jpassera@hornbeam:~/playground/openmole$ jstack 1315
1315: Unable to open socket file: target process not responding or HotSpot VM not loaded
The -F option can be used when the target process is not responding
``` 

And prints an error when forcing:

```
jpassera@hornbeam:~/playground/openmole$ jstack -F 1315
Attaching to process ID 1315, please wait...
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process
```

However, if you bring it back to foreground (`fg`), stop it (`CTRL+Z`), and resume it to background (`bg`) it resumes smoothly:

```
jpassera@hornbeam:~/playground/openmole$ fg
nohup ./openmole --remote

[1]+  Stopped                 nohup ./openmole --remote

jpassera@hornbeam:~/playground/openmole$ bg
[1]+ nohup ./openmole --remote &
```

Funny thing: once resumed, "a" jstack (not sure what state it represents: before, during or after stopped?) is dumped to `nohup.out`! (attached
[jstack_remote.txt](https://github.com/openmole/openmole/files/2017655/jstack_remote.txt)
)

Harmless but annoying :)

**Comment by jopasserat** [comment]
just experienced it again so still present :)

**Comment by romainreuillon** [comment]
Work on my machine

**Comment by romainreuillon** [comment]
Try: https://localhost:port

**Comment by jopasserat** [comment]
it does start indeed but try running a workflow it'll be stopped on Compiling

**Comment by samthiriot** [comment]
Same problem here. 

The process stops on "Compiling" step. 

Using the command `jobs -l` indicates "stopped (tty output)" 
```
user@computer:~$ jobs -l
[1]+ 49130 Stopped (tty output)    nohup ./openmole --remote --port 55555
```

Using the utility `screen` instead of `nohup` works.

**Comment by romainreuillon** [comment]
I think that the pb arrise from an issue in the 2.12 scala compile. It seems to work appropriately with OpenMOLE 11 that is now base on scala 2.13.

Romain
