### ISSUE TITLE
classOf[myopenmoleplugin.Hello] does not compile

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#3]
The use of the [myopenmoleplugin](https://github.com/openmole/myopenmoleplugin) example as given in the [plugin development documentation](http://www.openmole.org/current/documentation_development_plugin.html) does not work. Is uses the predefined ```classOf[T]``` function on ```myopenmoleplugin.Hello```, which however is a Scala ```object```. Therefore it fails with the ```error: not found type myopenmoleplugin.Hello```. According to [this SO answer](http://stackoverflow.com/questions/9635563/how-the-get-the-classof-for-a-scala-object-type), in case of an object type, one has to call the ```getClass``` method. Therefore, the example in the documentation should probably read ```usedClasses += myopenmoleplugin.Hello.getClass()```.

**Comment by romainreuillon** [comment]
Thanks for the report!

I just fixed that by adding a Hello trait in the plugin.

**Comment by schuhschuh** [comment]
Does this mean an actual type (i.e., class or trait) is required for usedClasses to work ? Adding Hello.getClass() to usedClasses would not have the same effect ? I am asking because then I'll have to change my plugin accordingly.

**Comment by romainreuillon** [comment]
It has exactly the same effect. I just fixed it this way to be consistent with what most user would do in their own plugins.
