### ISSUE TITLE
Env error do not appear in the GUI

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#300]
Since the refactoring of the env panel no env error is ever displayed.

**Comment by romainreuillon** [comment]
I think the problem is cause by the lack of refresh and clear button. Isn't it?

**Comment by mathieuleclaire** [comment]
Are you talking about the commits in the execution branch? If yes, it is normal, I noticed this also. If not, I think the source of the error is somewhere else since I had not touch this part of the code yet.

**Comment by mathieuleclaire** [comment]
merge with branch executions fixes it
