### ISSUE TITLE
(minor) (tiny) Last element name in long files lists is partially hidden

### ISSUE THREAD

**Issue by chapinux** [openmole/openmole#302]
In the File Management left panel, 
when a lot of files are displayed, the last (and potentially penultimate) elements of the list is not reachable, or half displayed : the limit of the browser window cut it through, even with the scrollbar fully down.

This is not a bug or so, just a little bit annoying when you aim for the last file 
(and don't remember you can switch the sorting order of the list)
Happens on ubuntu 16.04 (unity as windowmanager so it may come from it) & Firefox 60.0.1 (64 bits)

**Comment by mathieuleclaire** [comment]
Is this commit fix the problem ?
e0f39ed4baa7ed557e1ef900d2c16f6f50d95d98

**Comment by mathieuleclaire** [comment]
a12d8e0287f51e781c855a42a9122a9a4b27cd41 fixes it
