### ISSUE TITLE
[Doc] Missing output description in NSGA2 task

### ISSUE THREAD

**Issue by chapinux** [openmole/openmole#305]
The doc doesn't say anything on the format nor meaning of the outputs of NSGA2 methods.

We should add something like :

The output is a directory with all the file corresponding to each step of the calibration algorithm (populationXX.csv) 
Each line of these files contains : 
- a dummy colon containing the generation number (similar to the XX in the file name)
- the values of  parameters of the execution, 
- the median value of the objective computed on the replications
- evolution$samples : the number of times ( replications)  this execution has been performed with this parameter set

**Comment by JusteRaimbault** [comment]
[5e7866ac](https://github.com/openmole/openmole/commit/5e7866ac07188cf0d067d2142a2775f3f461ce47) does this.
