### ISSUE TITLE
[WebSite]  Missing pre-print of "Urban Dynamics and Simulation Models" publication

### ISSUE THREAD

**Issue by mbrasebin** [openmole/openmole#306]
Hi,

the file of the preprint of the article  "Urban Dynamics and Simulation Models"  is missing on Hal. It is the same thing for the bibtex file.

The link that refers to this file is available at the end of this page : https://next.openmole.org/Communications.html

**Comment by chapinux** [comment]
you can do it for us :-D

**Comment by JusteRaimbault** [comment]
indeed ;)

**Comment by JusteRaimbault** [comment]
pdf now available

**Comment by mbrasebin** [comment]
Thank you :+1:
