### ISSUE TITLE
File management page is deprecated

### ISSUE THREAD

**Issue by chapinux** [openmole/openmole#309]
File management page is weird :)

Remove systemtask and scalatask from File Management doc pages (split and  make another page)

we should add schemes on file mapping / var mapping with names like my******* for user files and OM***** for OMfiles variables

**Comment by romainreuillon** [comment]
@mathieuleclaire found that really important that a page explained file management in a transversal manner...

What do you mean by wierd ? Is it because it doesn't fit into the model/method/env hierarchy ?

**Comment by chapinux** [comment]
weird because there is some systemTask , some scalatask , way too soon, 
there is no introduction, no pretty schemes in Inkscaape with carefully chosen colors .

I think what we need is an explanation of the concept of "file mapping" (and a link to its cousin Variable Mapping that remains to be created too...) , schemes of a task inserted in a workflow, better variable names (like myOutputFile.txt and OMoutputFile.txt), a distinction between input and inputFiles, and so on.

I/we still have a lot of refactoring to do on this page of the doc :muscle:

**Comment by JusteRaimbault** [comment]
Variable mapping was recently implemented.

**Comment by mathieuleclaire** [comment]
I have to add the mapping image in the File Management section

**Comment by JusteRaimbault** [comment]
We just discussed and this needs a longer term reflexion on possibly unifying inputs

**Comment by mathieuleclaire** [comment]
Fixed in d1dbf2bf24bbfce0932d5c2a7f9fb8e1be955b9d
