### ISSUE TITLE
Cleaning state for job deleted or "continue to clean" job on restart

### ISSUE THREAD

**Issue by reyman** [openmole/openmole#316]
Hi,
Discuted with Romain last day on phone.

When you click on cancel task, then delete, there is nothing that indicate you that this process is not immediate, or delegated to the grid/cluster. So it's really easy for a beginer who launch/kill multiple time the job or directly OpenMole to create lots of zombie jobs on the grid/cluster.

I see three solutions : 
- display a cleaning state during the task cancelling/cleaning
- like many software i suppose, stop/kill of Openmole process pause the cleaning process if exist, and when user relaunch, the cleaning continue.  
- delegate the kill to another server, or to the grid/cluster ?

**Comment by romainreuillon** [comment]
Implemented in 047670c9908b6544b8ef0a7d49ef771898638851
