### ISSUE TITLE
Simplify Netlogo Task input / output 

### ISSUE THREAD

**Issue by reyman** [openmole/openmole#317]
Hi,

There is some ambiguity with netlogoOutput/Output. Many users copy paste the netlogoOutput variable into output var of the task. 

The concatenation of the different output is implicit, so it's really hard for a beginer to understand this logic without reading the doc.

Perhaps we could simplify with only one input/output for the netlogo task ?

**Comment by romainreuillon** [comment]
Can you give an example ?

**Comment by JusteRaimbault** [comment]
I do not exactly get what you mean ? the problem would be that there are both output and netLogoOutputs ?
netLogoOutput is necessary to have the mapping between nl reporters and prototypes, and output can be used for variables not coming out of netlogo (parameters e.g.), so both are necessary to me.

**Comment by reyman** [comment]
Yep, i understand the principle of the double output and i'm ok with it, but beginer have some difficulties to understand this behavior. 

Perhaps we could remove the explicit mapping between Netlogo var and and openMOLE var, with an automatic detection of mapped variable (same name in Netlogo and OpenMOLE) or a mapping when you declare the variable (generic for all tasks who need some mapping, like R, etc.) .

Based on the example [of fire.nlogo](https://next.openmole.org/NetLogo.html) : 

```

val seed = Val[Int]
val density -> "density" = Val[Double]
val burned -> "burned-trees" = Val[Double]

val fireTask =
  NetLogo6Task(workDirectory / "Fire.nlogo", cmds) set (
    inputs += (seed, density)
    outputs += (density, seed, burned) 
  )
```
@ElCep , what do you think of this proposition ?

**Comment by mathieuleclaire** [comment]
I think it is dangerous to set implicit mappings. However, I planned to add a draw for files mapping, I can do the same thing for the netlogo mappings. A picture often speaks better than words.

**Comment by mathieuleclaire** [comment]
Something like this:
![mapping](https://user-images.githubusercontent.com/800035/41530446-8cd03b60-72f0-11e8-9854-27a27ecc9873.png)

**Comment by JusteRaimbault** [comment]
Nice picture @mathieuleclaire !
I close this issue concerning the NetLogoTask as we agree not to add implicit mappings.

**Comment by romainreuillon** [comment]
This input mapping seems a bit generic for many task: netLogo, scilab, R... I am thinking about poposing a unified keyword for specifying inputs and outputs for all these task.

May be:
```scala
val fireTask =
  NetLogo6Task(workDirectory / "Fire.nlogo", cmds) set (
    inputs += seed,
    mappedInputs += density,
    outputs += (density, seed, burned) 
  )
```

NB: mappedInputs is definitely not the final name :)
```

**Comment by romainreuillon** [comment]
After a bit of thoughts, that would not be that bad:
```scala
val fireTask =
  NetLogo6Task(workDirectory / "Fire.nlogo", cmds) set (
    inputs += seed,
    inputs += density mappedTo "density",
    outputs += (density, seed, burned) 
  )
```

**Comment by romainreuillon** [comment]
Might be:
```
val fireTask =
  NetLogo6Task(workDirectory / "Fire.nlogo", cmds) set (
    inputs += seed,
    inputs += density -> "density",
    outputs += (density, seed, burned) 
  )
```

**Comment by mathieuleclaire** [comment]
My favourite is the one with the arrow. Would we do the same for all mappings (files, R, Scilab, etc)?

**Comment by chapinux** [comment]
This kind of explicit statement is exactly what I dream of .
Slight preference for "mappedTo" because it can be highlighted in the code editor, but the arrow is ok too I guess

**Comment by mathieuleclaire** [comment]
I must admit that the explicit "mappedTo" has the advantage to be ... explicit ! Think about the older versions of sbt with so many unclear statements like: <<++ .

**Comment by helenea** [comment]
I agree with Paul, mappedTo is clearer than the arrow I think.

**Comment by chapinux** [comment]
I agree with the agreement

**Comment by romainreuillon** [comment]
This is now legit:
```scala
    NetLogo6Task(workDirectory / "Fire.nlogo", cmds) set (
      inputs += seed,
      inputs += density mapped "density",
      outputs += (density, seed),
      outputs += burned mapped "burned-trees"
    )
```

**Comment by JusteRaimbault** [comment]
Great ! I guess we can reopen the issue for modifying the documentation accordingly !

**Comment by JusteRaimbault** [comment]
NetLogoTask accordingly documented ; should open a new issue for documenting other tasks.
