### ISSUE TITLE
[NetLogoTask] Get LogoLists as Arrays in netLogoOutputs

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#319]
Currently, the netLogoArrayOutputs allows to retrieve a column of a LogoList and it works ; we should be able to retrieve full lists as Arrays in netLogoOutputs (similarly as we can pass some in input) - it currently fails as it seems that the runtime class is tested with isArray and no previous conversion from LogoList is done. We should also at this point add the recursive conversion to retrieve list of arbitrary depth.
I'm on it !

**Comment by JusteRaimbault** [comment]
that's dirty but I think there is no other way than converting Logolists to java arrays in java tools file where we access the NetLogo API, as we do not have access to LogoList in NetLogoTask and can not test if the output is actually one

**Comment by JusteRaimbault** [comment]
I had actually a wrong script, the conversion LogoList -> Array at depth 1 works ; but at deeper levels no, so the issue is still open for this recursive part.

**Comment by JusteRaimbault** [comment]
[314d7a10eb](https://github.com/openmole/openmole/commit/314d7a10eb072952de01f4637e846de057368cd9)  solves this

**Comment by JusteRaimbault** [comment]
(sorry for the traffic light pattern)

**Comment by JusteRaimbault** [comment]
It appears to be broken with the new mapping (I thought a moment it was because of the model, the feature was tested only on simple cases)

**Comment by JusteRaimbault** [comment]
strange because I though I had tested it for both NetLogo5 and NetLogo6 ; now the issue is only with NetLogo6, it does not manage to cast the LogoList to an abstract collection, should be a problem with the NetLogo API. @romainreuillon did you update the version of the API ?

**Comment by JusteRaimbault** [comment]
From NL API transition guide : 
"LogoList was moved from org.nlogo.api to org.nlogo.core. api.LogoList implemented java.util.AbstractSequentialList<AnyRef> while core.LogoList does not implement it. It is possible to turn a LogoList into an AbstractSequentialList by using toJava (see table below). LogoList now implements scala.collection.IndexedSeq[AnyRef], giving it access to a number of powerful features accessible from Scala extensions."
-> we can quickpatch using the `toJava` method after checking is it is a LogoList ; or we could switch everything to scala for NetLogo6 ?

**Comment by JusteRaimbault** [comment]
Did an ultra shitty patch which works :octocat: :octocat: , making an additional recursive conversion in the NetLogo6 tool ; should I commit to dev so the bug is patched until we find something cleaner ?

**Comment by romainreuillon** [comment]
It is better to stick to java classes only.

**Comment by JusteRaimbault** [comment]
so I should push the patch in NetLogo6.java to ensure we still have AbstractCollection when they come from a NetLogo6Task ?

**Comment by JusteRaimbault** [comment]
[7dc9a82537](https://github.com/openmole/openmole/commit/7dc9a82537ccad9a98f3651022114993fecb9fdb) fixes this (before eventual future deeper refactoring), closing the issue
