### ISSUE TITLE
createLink should handle specific IOException's

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#32]
The ```createLink``` function falls back to a full copy if the creation of links is not supported by the implementation/file system. At the moment, this is done whenever ```Files.createSymbolicLink``` throws an ```IOException```. In fact, it should only catch the ```UnsupportedOperationException``` and in that case fall back to creating a full copy instead. All other exceptions should be re-thrown to make the user aware of a problem. For example, ```FileAlreadyExistsException``` would occur if the user were to give two input file links the same name. As this is a user mistake, just silently replacing the first copy by the second is not desired.

**Comment by romainreuillon** [comment]
Totally agree. Could you submit a PR?

**Comment by schuhschuh** [comment]
I will. Still trying to find out why my resources links are causing my job submissions to "hang"... thought it was related that it actually would create a copy of the 40GB directory instead of just creating a link to it upon ```prepareInputFiles```, but so far I cannot confirm that's the issue. Changing the exception handling was not helping.

Anyway, I will replace ```IOException``` by ```UnsupportedOperationException``` and send the PR.

**Comment by schuhschuh** [comment]
(P.S.: After moving the 40GB and trying it with an empty directory the jobs are being submitted. Hence, for some reason OpenMOLE does either fail or not attempt to create a symbolic link from the ```workDir``` of the task to a "local" path on a shared drive. Different issue, though...)
