### ISSUE TITLE
Conditional hooks

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#320]
Sometimes, we just need to hook variables depending on a condition. Typically the GA generates tons of population.csv and not saving all of them can be usefull. A general mechanism allowing this could be a condition on hooks, which permits to trigger the hook whether the condition is true.

**Comment by romainreuillon** [comment]
It actually exist already, but it is not that useful. I think an option of the SavePopulationHook to save the last population only would be more suitable.

**Comment by JusteRaimbault** [comment]
[634295cb49](https://github.com/openmole/openmole/commit/634295cb49daa2640e0377dbdff5cf852977289a) solves the documentation of the ConditionalHook

**Comment by JusteRaimbault** [comment]
is the option on SavePopulationHook implemented ? (I guess it can be done with a `when evolution$generation == ...` but it is a bit different than letting the hook keep the last only himself )?

**Comment by JusteRaimbault** [comment]
Just discovered the `SaveLastPopulationHook` and the `frequency` option in `SavePopulationHook` :octocat:

**Comment by JusteRaimbault** [comment]
But it does not seem to be documented

**Comment by romainreuillon** [comment]
It's brand new, and it works ! Feel free to add it to the doc :scroll:

**Comment by JusteRaimbault** [comment]
Great, thanks !

**Comment by JusteRaimbault** [comment]
Done in [38c70ba27f9](https://github.com/openmole/openmole/commit/38c70ba27f9b8324af8a20afce34ab8207cc7bb1)

**Comment by romainreuillon** [comment]
:medal_sports:
