### ISSUE TITLE
Doc pages not properly indexed

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#321]
Some pages in the doc website do not seem to be stored at the right place. 2, non exhaustive, examples:
https://next.openmole.org/Resumable+Workflow.html
https://next.openmole.org/Hook.html

are stored in the _scale_ section.

**Comment by helenea** [comment]
It's fixed, but it's based on the old doc when there were only 3 sections, anything not in these sections doesn't have a header.
