### ISSUE TITLE
OpenMOLE should set inputFiles variables inside ExternalTask to destination path

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#34]
I have the following ScalaTask:
```scala
val regTask = ScalaTask(
      s"""
        | Config.parse(\"\"\"${Config()}\"\"\", "${Config().base}")
        | val ${dof.name} = FileUtil.join(workDir, "rootfs", s"$dofRelPath")
        | val ${log.name} = FileUtil.join(workDir, "rootfs", s"$logRelPath")
        | IRTK.ireg(${refIm.name}, ${srcIm.name}, None, ${dof.name}, Some(${log.name}),
        |   "Transformation model" -> "Rigid",
        |   "Background value" -> $bgVal
        | )
      """.stripMargin) set (
        name        := "ComputeRigidTemplateDofs",
        imports     += ("com.andreasschuh.repeat.core.{Config, FileUtil, IRTK}", "sys.process._"),
        usedClasses += (Config.getClass, FileUtil.getClass, IRTK.getClass),
        inputs      += srcId,
        inputFiles  += (refIm, refId + refSuf, Workspace.shared),
        inputFiles  += (srcIm, imgPre + "${srcId}" + imgSuf, Workspace.shared),
        outputs     += (refIm, srcId, srcIm),
        outputFiles += (join("rootfs", dofRelPath), dof),
        outputFiles += (join("rootfs", logRelPath), log)
      )
```

As can be seen, I have two input files which I specify to be copied (or linked if ```Workspace.shared```, i.e., files are located in shared NFS directory). The ```inputFiles += (refIm, "input.nii.gz")``` setting tells OpenMOLE to copy the file from the workflow to a file named ```input.nii.gz``` in the ```workDir``` of the task. Within the ScalaTask, I have to refer to this file. I can do so via
```scala
new java.io.File(workDir, "input.nii.gz")
```
which does work fine. However, I am wondering why can I not just use the variable ```refIm``` inside my ScalaTask ? This doesn't work because it contains some path used internally by OpenMOLE (or so) such as:
```
refIm=/homes/as12312/.openmole/.tmp/ssh/5255b992-aae3-
4fa6-8dce-a56079207f3d/tmp/1430438747488/ae8e1db6-55a6-4344-9c95-5817c46255bc/7ae89958-2468-4ed2-be34-56d082322f1c/.tmp/e571403f-2977-4c57-9c8d-9296564089b4/file6e3a10e0-7704-4ad5-a3fb-f4452
8ec3a3a.bin
```
What I would expect (and hereby encourage to consider as a change) is that the input variable ```refIm``` would be set to the destination to which the input files has been copied as a result of the ```inputFiles``` specification. Only within the ExternalTask. The path passed to the next task as part of the ```outputs += refIm``` should be unchanged.

Otherwise it is a bit redundant having to specify the file path within ```workDir``` once as part of ```inputFiles``` and another time when referring to it in the ScalaTask script (or SystemExecTask command line).

**Comment by romainreuillon** [comment]
It took a bit of time to wrap my head around it, but it make sense. It should work that way now.

**Comment by schuhschuh** [comment]
Great!
