### ISSUE TITLE
[Site] Document mapped input

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#345]
Document the new syntax `prototype mapped "variable"` in the RTask (and also ScilabTask ?)

**Comment by romainreuillon** [comment]
Yes, for now, with the netlogo task, that's all the task supporting mapping of the default openmole distrib. (let aside, GAMA and CORMAS which are implemented in external plugins)

**Comment by JusteRaimbault** [comment]
ok great !
just a remark, as we differentiate task inputs and mapped inputs using the mapped property, we must always use
`inputs += i mapped "i"`
and not `inputs += i` anymore even if variables have the same name.

**Comment by romainreuillon** [comment]
You can do ```inputs += i.mapped``` which is equivalent to  ```inputs += i mapped "i"```.

**Comment by JusteRaimbault** [comment]
[4e91c868](https://github.com/openmole/openmole/commit/4e91c86830f26bd4a904b8fa9ce46b42c446d035) modifies the doc
accordingly.

**Comment by JusteRaimbault** [comment]
ok indeed !
I add this option also

**Comment by JusteRaimbault** [comment]
[cd08c174c](https://github.com/openmole/openmole/commit/cd08c174c69c9744df3437349a6b68c3dc6c5b40) closes this.
