### ISSUE TITLE
OpenMOLE log file located in temporary directory which is deleted upon exit

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#35]
Whenever there is an error, a message indicates the location of a log file which the user should consult for more details regarding the issue. However, this log file gets deleted when OpenMOLE exists and can therefore not be accessed by the user.

```
An error has occurred. See the log file
/vol/medic01/users/as12312/OpenMOLE/.tmp/1430675182_17352/1430675183053.log.

as12312@merapi:/homes/as12312/Data/Temporary/OpenMOLEStorageSharedLocallyTest
> ls /vol/medic01/users/as12312/OpenMOLE/.tmp/1430675182_17352/1430675183053.log
ls: cannot access /vol/medic01/users/as12312/OpenMOLE/.tmp/1430675182_17352/1430675183053.log: No such file or directory
```

**Comment by romainreuillon** [comment]
This message it displayed by equinox. An option is activated so the content of this file is written on the standard output already.

**Comment by schuhschuh** [comment]
Any possibility to suppress the output of the "See the log file" message ? If yes, I would do so, otherwise just ignore this issue and feel free to close it again.
