### ISSUE TITLE
encode a Boolean Factor?

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#350]
Hello,

We can define many things as factors today, but I'm not sure how to define a Boolean factor, that is a factor describing that a prototype might take two values, either True or False. 

Does that already exists ? 

Tks !
S.

**Comment by JusteRaimbault** [comment]
Just use a Val[Boolean] ?
Also I think we should use github issues for real issues and not requests or questions, for which there is the dedicated discourse : https://discourse.iscpif.fr/c/openmole
(so the forum can live a bit ! :) )
cheers !
:octocat: :octocat:

**Comment by samthiriot** [comment]
mmm, sorry, but it is to me going to lead to a merge request, which does require a github issue.
But if you prefer, we can for sure start on the forum.

**Comment by romainreuillon** [comment]
Indeed it is not not documented but the `Val[Boolean]` itself is a factor with two values. You can do:

```
val i = Val[Int]
val b = Val[Boolean]

val sampling = i x b
```

A merge request for the doc on this topic would be much appreciated ;)
