### ISSUE TITLE
[Doc] Update changelog for version 8.

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#354]
https://github.com/openmole/openmole/blob/dev/openmole/bin/org.openmole.site/jvm/src/main/scalatex/openmole/download/PreviousVersions.scalatex
- [x] @mathieuleclaire
- [ ] @romainreuillon 
- [ ] @jopasserat 
- [ ] @chapinux 
- [x] @helenea 
- [x] @JusteRaimbault 
- [ ] @guillaumecherel

**Comment by JusteRaimbault** [comment]
[a76edc](https://github.com/openmole/openmole/commit/a76edc92bd0adc21d787e3a582e5a67df2f0a4aa) synthesizes main plugin changes since 7.1
