### ISSUE TITLE
Group environment errors

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#356]
It often occurs the same Environment errors is catched. However, they differs from a hash, so that they are not consider as different from the GUI. It would be nice to group them (keeping the cardinality) to avoid this kind of behavior:
![errors](https://user-images.githubusercontent.com/800035/42957955-6589cc36-8b84-11e8-980a-004abba0e80e.png)

**Comment by romainreuillon** [comment]
This is not solvable in a proper way in this version. It will be tackled in #362
