### ISSUE TITLE
[Site] Side menus unattainable

### ISSUE THREAD

**Issue by helenea** [openmole/openmole#358]
When there are too many items on the left side menu, the last ones are unattainable on smaller computer screens (14" for my laptop for instance).

![image](https://user-images.githubusercontent.com/8794131/43147793-277fa8e6-8f64-11e8-85a2-9a438dd5a3d4.png)

I think I can help with that but it would probably mean changing the appearance of the left side menu and I don't know where that can be done in the code. Any clue?

**Comment by mathieuleclaire** [comment]
Related to #359
