### ISSUE TITLE
Unfinished tutorials in site

### ISSUE THREAD

**Issue by mathieuleclaire** [openmole/openmole#361]
The first 3 tutorials in the website are not finished. It would be great to finish the "Step by step" one for the version 8 and to postpone Launch and Explore. What do you think ?

**Comment by chapinux** [comment]
sure it would be great , I was and should be on it , but I cannot promise to complete it until the milestone of version 8 :-/   
(btw when is it planned ?)

**Comment by mathieuleclaire** [comment]
September would be great for a RC without any issue anymore.

**Comment by helenea** [comment]
I'm working on the step by step tutorial, should have something to show you soon.

**Comment by helenea** [comment]
The tuto is [done](https://next.openmole.org/Step+By+Step+Intro.html).
There are 2 screen pictures missing: one of the model import wizard and one of the execution panel, both in the GUI. @mathieuleclaire could you add them please? Your screen is so much better than mine ;)

**Comment by mathieuleclaire** [comment]
Done. Concerning Explore and Launch tutorials, how are they different compared to what it is explained in "Step by step" one ? If they are different, could you set a warning sentence to explain what we need there and to call for participation ? Then, we'll close this issue.

**Comment by helenea** [comment]
Done in 0855033d2411efc6511bb432a8691da28b4f65e8.
I removed the Launch tutorial as it's all explained in the Step by Step, and asked for participation to write the Explore tuto.
