### ISSUE TITLE
[GUI] [Enh] Support more archive types

### ISSUE THREAD

**Issue by helenea** [openmole/openmole#364]
It would be nice to have more archive types supported in the GUI, like tar.xz for instance (default in Ubuntu 18.04).

**Comment by mathieuleclaire** [comment]
It does not exist any java or scala implementation as a library. [xz-java](https://git.tukaani.org/?p=xz-java.git;a=summary) should do the job but it is not packaged and published as a sbt dependency. So we should copy/paste the src as a third-party. It seems to me it is a lot of files to run/compile/maintain for a small (no offence) requirement. But, let's leave it open for now.

**Comment by mathieuleclaire** [comment]
We now support tar.gz, zip and tar.xz
