### ISSUE TITLE
[Doc] Grouping is hard to find and does'nt appear in the search bar

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#368]
Finding the way to group the job prior to remote execution in the doc is really challenging.

**Comment by mathieuleclaire** [comment]
Well, "grouping" is a section title in scale, so it comes first when searching in the search section. How do you think it could be better referenced ?

**Comment by romainreuillon** [comment]
I get no answer when I search for grouping:

![image](https://user-images.githubusercontent.com/1270995/44628444-0ca5e580-a940-11e8-9dc7-22d7a696e35a.png)

**Comment by JusteRaimbault** [comment]
website is fine now, closing this
