### ISSUE TITLE
SSHAuthentication += should do nothing or update existing one if already present

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#37]
I think it should be save to call ```SSHAuthentication += ...``` even if the login information or private key for a specific host is already present in ```~/.openmole/$(hostname)/persistent/authentications/org.openmole.plugin.environment.ssh.SSHAuthentication```. Right now it seems to add a new entry each time even if nothing changed, e.g., the private key file was not modified.

When developing an app that under the hood executes the OpenMOLE console, I don't want to require the user to first add the authentication methods within OpenMOLE before starting my app. I see that I can use ```SSHAuthentication(SSHAuthentication.address(login, host, port))``` myself to check if one is already present. But wouldn't it also make sense to modify the ```+=``` method to possibly remove an old entry and then add the new one at the top of the "stack" ? Or do nothing if the current entry is the top-most one used for the given target ?

**Comment by schuhschuh** [comment]
For a ```PrivateKey```, this would probably require to store also the modified time of the key file in order to detect when the file has changed.

**Comment by jopasserat** [comment]
@romainreuillon does 4129baaf479d988fdf5af09ec515f55d6a21a3b2 brings any input to this?

**Comment by romainreuillon** [comment]
That's on EGI. But now the SSHAuthentication matching doesn't work the same way. Match is exact on login@machine so there is no order anymore. We should update the doc accordingly.

**Comment by romainreuillon** [comment]
However, the replacement of existing key, when login@machine is the same is not implemented yet.

**Comment by romainreuillon** [comment]
+= now replace existing keys matching on login and machine name.
