### ISSUE TITLE
[Doc] Minor changes to make before v8

### ISSUE THREAD

**Issue by helenea** [openmole/openmole#371]
Below are some minor changes I'd like to make to the doc before the next release, help is welcomed :)
Just write in the comments which one you're working on, to avoid concurrent changes!

Reorganize the structure of these pages to have sensible h2 titles in the "Contents" part:

- [x] Doc/Run/R
- [x] Doc/Run/Packaged
- [x] Doc/Explore/DirectSampling
- [x] Doc/Explore/Calibration
- [x] Doc/Language/Hooks
- [x] Doc/Language/Transition
- [x] Doc/Developers/PluginDevelopment
- [x] Community/HowToContribute

Update the written content, rewrite, or suppress these pages:

- [x] Doc/AdvancedConcepts this head page doesn't make sense with what is inside the section
- [x] Doc/Developers this head page is useless as it is, write something useful or suppress it
- [x] Market most of the content is already presented in Tutorials head page, remove duplicate by keeping only one page about the market?

**Comment by JusteRaimbault** [comment]
There is also the NetLogo page to clean a bit, I'm on it.
Just to be clear, we commit and push to 8-dev or master ?

**Comment by helenea** [comment]
Master!

I'm on Calibration right now.

**Comment by helenea** [comment]
Transition page done, but there is an issue in [this section](https://next.openmole.org/Transition.html#Combiningseveralworkflowpartswith) because it's about the "+" operator and the example doesn't use "+" but "&". Is "+" deprecated ? @romainreuillon

**Comment by romainreuillon** [comment]
@helenea I improved the hook documentation

For the second point, indeed the + operator is deprecated and is replaced by &

**Comment by helenea** [comment]
I'm done with my changes.
@JusteRaimbault did you do what you wanted to do with the NetLogo page?

**Comment by JusteRaimbault** [comment]
[4ff34092b533](https://github.com/openmole/openmole/commit/4ff34092b533d149abe176f3c3baea4018ee47e7) fixes the netlogo doc. Closing the issue as all required changes have been done.
