### ISSUE TITLE
[Enh] Towards meta-modeling experiments ?

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#374]
I'm currently dealing with a painful-to-configure model, for which some structure in the exploration script must be hardcoded (variable names, configuration files path) but which can change with a new version of the model.
I improvised some kind of (**ultra-dirty** - maybe as much as the model setting) on-the-fly script generation from a template of the experience plan: an openmole script generates an other openmole script which can then be run for the actual experiment.
This is also linked to multi-modeling ; let say one has several models to compare, this may not be directly straightforward to have a single script for the "meta-experiment", as similarly some hardcoding may be required.
And this is only the first level of reflexivity, we could imagine experiments launching experiments launching experiments... etc. (as Roger White put it at ectqg17, this may be the future of modeling in the case of territorial systems, i.e. autonomous intelligent and evolutive meta-models).

What about meta-modeling in OpenMOLE, has anyone already thought about it, could we foresee it in a close future ?

**Comment by JusteRaimbault** [comment]
This question does not seem to rouse crowds; any insight anyone ?

**Comment by chapinux** [comment]
Theoretically, I love it , technically I hate it .

Writing oms scripts is already painful and complex. 
Writing scripts-that-write-scripts will be too much intricacy for my little cortex.

Although I totally agree with the long term vision ( meta modeling / meta-experiment is totally what we want ! )  
I cannot help but think the technical paywall is far too high, at least to me. Just thinking about a hard coupling of simple models make my brain melt.

If I had to, I would focus on the low-level experiment and model modules first, hardcoding all the rest with my bare hands, for really tiny  couplings
You know, as Stupeflip once said : "prendre des petits bouts de trucs et puis les assembler ensemble et écouter le résultat tranquille, dans ma chambre" 

This needs time to be played with (which I have not these days) , but is exciting  !

**Comment by romainreuillon** [comment]
My 2 cents, I think that an aspect of multi-modeling that we will teach in eX Modelo will be hybrid discrete-continuous optimisation.... This is a really basic and might fit in Paul's brain :)

**Comment by JusteRaimbault** [comment]
I talked with Franck Varenne yesterday, and he mentioned a project by Ziegler and the DEVS team aiming at some kind of universal modeling, I will try to have a look into that.
Also he told me that ecologists had the same kind of problems as we begin to encounter to benchmark models which do not have the same structure and no common implementation (for now multi-modeling simpuzzle etc is at fixed structure and requires a single implementation) ; we need to find how to relax meta-levels without getting into terrible technical and conceptual stuff giving headaches (maybe it is just a change of perspective, maybe it is impossible).
Furthermore [this paper](https://e-space.mmu.ac.uk/615007/6/OEE_main_20160502_header.pdf) points that a reflexive language would be necessary for simulating true open-ended evolution ; so these issues are also linked with the development of open-ended exploration methods (e.g. open-ended model construction).

**Comment by JusteRaimbault** [comment]
Closing this as it seems **totally** out of current reach
