### ISSUE TITLE
[git] git lfs useless?

### ISSUE THREAD

**Issue by simoncarrignon** [openmole/openmole#382]
I just installed from openmole on my debian 9 from the source.
I haven't used `git lfs` at all and it looks it's working.
Not sure if it's normal or if at some point everything will crash but so far the netlogo program I am trying is working great.  

If it's not useful anymore wouldn't it be great to remove it from the doc? it'll be one package from a non-debian third party repository that we don't need to install anymore :)

**Comment by romainreuillon** [comment]
LFS is still useful. It compiles successfully without pulling the files from the LFS but you'll miss some file in the built artefact. For instance the execution of your tasks on a remote environment wont work. 

There is an issue on this topic: https://github.com/openmole/openmole/issues/177.

**Comment by simoncarrignon** [comment]
Oh, ok. I am just trying right now to setup all to run in on a remote SLURM grid, I guess I should meet this #177 soon.  Does it means openmole use git to its local and remote environments?

**Comment by jopasserat** [comment]
no, but in order to build a full fledged OM that can run on remote workers, you'll need the items in the LFS (main one being a JVM that the OpenMOLE instance on the worker node uses, so we guarantee there is A- a JVM installed, and B- the version we're expecting

**Comment by simoncarrignon** [comment]
got it! thanks for the explanation.
