### ISSUE TITLE
[Plugin][Evolution][NSGA2] Inconsistent capsule level

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#387]
I am trying to launch a NSGA2 calibration ; it works well when using Islands distributed on the grid, but fails when removing the `distribution` argument and running on local (running the Islands on local works). The top of the error stack is
org.openmole.core.exception.UserBadDataError: Inconsistent level found for capsule capsule@298057986:scalingGenomeTask@-663471404
The issue must have been introduced "recently" as an openmole version compiled end of september works on the exact same script.

**Comment by romainreuillon** [comment]
I cannot reproduce this issue. May you provide a minimal script?

**Comment by JusteRaimbault** [comment]
Full script :

val countrycode = "BR"

import java.util.Date
import java.text.SimpleDateFormat

logger.level("FINE")

val growthRate = Val[Double]
val gravityWeight = Val[Double]
val gravityGamma = Val[Double]
val gravityDecay = Val[Double]
val gravityAlpha = Val[Double]

val id = Val[Int]

// Reporters
val logmse=Val[Double]
val mselog=Val[Double]

// config files
val popFile=Val[File]
val distFile=Val[File]
val dateFile=Val[File]

// Model
val model = ScalaTask(
    """
      |import urbangrowth.models.coevolution._
      |import urbangrowth.indicators._
      | val res = Coevolution(input.popFile, input.distFile,null, input.dateFile,input.growthRate,input.gravityWeight, input.gravityGamma, input.gravityDecay, 0.0, 1.0, 1.0).run()
      | val logmse = res.logmse
      | val mselog = res.mselog
    """.stripMargin
  ) set (
    plugins += pluginsOf(urbangrowth.models.coevolution.Coevolution),
    inputs += (popFile,distFile,dateFile,growthRate,gravityWeight,gravityGamma,gravityDecay,id),
    outputs += (growthRate,gravityWeight,gravityGamma,gravityDecay,id),
    outputs += (logmse,mselog)
  )
val modelCapsule = Capsule(model)

val fileSetting = ExplorationTask(
  (popFile in Seq( workDirectory / "data"/ "processed" / (countrycode+"_pops.csv"))) x
  (distFile in Seq(workDirectory / "data"/  "processed" / (countrycode+"_dist.csv"))) x
  (dateFile in Seq(workDirectory / "data" /  "processed" / (countrycode+"_dates.csv"))) x
  (id in Seq(1))
) set(
  inputs += (growthRate,gravityWeight,gravityGamma,gravityDecay),
  outputs += (growthRate,gravityWeight,gravityGamma,gravityDecay)
)

val eval = fileSetting -< model


val modelname = "intgib"
val datestr = (new SimpleDateFormat("yyyyMMdd_HHmmss")).format(new Date()).toString
//val purpose = "CALIB_GRID"
val purpose = "CALIB"
val resdir = purpose+"_"+modelname+"_"+countrycode+"_"+datestr

//val grid = EGIEnvironment("vo.complex-systems.eu")
//val local = LocalEnvironment(50)


val evolution =
  NSGA2Evolution(
    genome =
      Seq(
        growthRate in Range(0.0, 0.05),
        gravityWeight in Range(0.0,0.05),
        gravityGamma in Range(0.0,10.0),
        gravityDecay in Range(0.1,100000.0)
      ),
    mu=400,
    objectives = Seq(mselog,logmse),
    evaluation = eval,
    termination = 40000,
    parallelism = 50
)


val savePopulation = SavePopulationHook(evolution, workDirectory / "calib" / resdir)

(evolution hook savePopulation on LocalEnvironment(50))
//(evolution on grid hook savePopulation)

**Comment by JusteRaimbault** [comment]
but it needs a plugin and data files to run.
I try to see if I have the issue with a more basic script

**Comment by romainreuillon** [comment]
You must aggregate after the model: ```val eval = fileSetting -< model```

**Comment by JusteRaimbault** [comment]
I'm closing the issue as it was finally a problem in my script (or an actual issue in a former version of openmole) ; it is not clear why the island scheme works, an aggregation is added in it ?
Also I'm not sure that the concept of "capsule level" is well explained in the doc, we should keep that in mind and todos.
