### ISSUE TITLE
Exposure of private SSH key

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#39]
While studying the files replicated by OpenMOLE for the execution of a test workflow, I noticed that the "persistent" directory of the session contains a TAR archive which itself contains a file with my private SSH key in it. As all files and directories are readable by everybody, this poses a security risk. The ```.rep``` file contains the serialisation of the environment object with accompanying files.

**Comment by romainreuillon** [comment]
This is really not supposed to be. It was caused by a change I did this weekend, I should have been really tired to do that. Hopefully this is fixed now.

**Comment by schuhschuh** [comment]
I assume this is fixed. Last time I checked the archive files, they didn't contain any SSH key file.
