### ISSUE TITLE
[GUI] the editor becomes very slow

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#392]
Working on some OpenMOLE files for a some time (may be 10 minutes) make the editor unusable. I have to reload the application to make it work. The fist functionality impacted is the completion which become very slow and then the whole editor become unusable.

No sure how to reproduce that fast for now. But it is systematic after working a bit with the editor.

**Comment by mathieuleclaire** [comment]
Do you have running simulations in the same time ?

**Comment by romainreuillon** [comment]
Nop, no running simulations.

**Comment by mathieuleclaire** [comment]
only in 0.9-SNAPSHOT ?

**Comment by romainreuillon** [comment]
I don't know I am using this version exclusively.

**Comment by JusteRaimbault** [comment]
I also experienced freezing issues in the gui for different versions, several times. Thought it was bad connection or too large folders to explore, may have had an editor window opened nevertherless. Will peruse and report as best as possible the configuration next time.
