### ISSUE TITLE
[GUI] Link to documentation needs an update

### ISSUE THREAD

**Issue by helenea** [openmole/openmole#394]
In the GUI, the link to the doc in the menu on the right should be updated to "https://next.openmole.org/GUI.html" instead of "[...]/GUI+guide.html" currently.

**Comment by mathieuleclaire** [comment]
Sure ! No objection at all. Do you make it ?

**Comment by helenea** [comment]
I'd rather you do it, I'm kinda lost in the GUI files :/

**Comment by romainreuillon** [comment]
It should be next in the dev version. You can test it buy using build info.
