### ISSUE TITLE
[Doc] Talk about model wizard in NetLogo task description

### ISSUE THREAD

**Issue by helenea** [openmole/openmole#395]
I think the model wizard should be mentioned in the NetLogoTask description, as it is particularly helpful for importing NetLogo models.
If there are no objections I will add a few lines to do so.

**Comment by mathieuleclaire** [comment]
Well, I misread your 2 issues, so: yes, do it ;) !

**Comment by JusteRaimbault** [comment]
[89e313b7a](https://github.com/openmole/openmole/commit/89e313b7a4d6f8910cb0af5a916a71b72accdefb) does this.
