### ISSUE TITLE
[Core] Removing Replicas is extremely slow and stalls the process

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#396]
For some reason, I have to successively run several openmole scripts in console mode ; in each the computation has a scheduled execution time and the next begins when the previous is finished - the thing is that openmole does not terminate as long as replicas are not removed from the database, what is ultra slow (for a 2h calibration on 1000 islands finished yesterday, it took all night and running).
Could it be possible to add an option telling not to clean at the end of the run ? (or to make it much faster ?)

**Comment by JusteRaimbault** [comment]
I remember doing something similar in September and did not encountered this issue ; I guess there were some modifications on the way cleaning is handled ?

**Comment by romainreuillon** [comment]
Indeed cleaning is now synchronous and the mole is not considered terminated as long as it's being cleaned. I think it shouldn't be a problem to create a parameter disabling this behaviour.

**Comment by romainreuillon** [comment]
d6c195d60cb816d174bba0e9b88afbf4ba9d3619 solves it.

You can now do this:
```scala
    val emptyT = EmptyTask()
    val me = emptyT.start()
    me.hangOn(cleaned = false)
```

**Comment by JusteRaimbault** [comment]
Great thanks ! Should I add this at the end or the beginning of the script ?
