### ISSUE TITLE
UnknownHostException: Was not able to get local host name (OS X)

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#4]
```
WARNING: Was not able to get local host name.
java.net.UnknownHostException: cotopaxi: cotopaxi: nodename nor servname provided, or not known
```

Not actually an issue, just FYI and if others may search for a similar issue resolution. This was easily fixed by adding the line ```127.0.0.1 cotopaxi``` to my ```/etc/hosts``` file ([cf. this article](http://javarecipes.com/2013/11/12/java-net-unknownhostexception-on-mac-os-x/)).

**Comment by jopasserat** [comment]
Yep I found that too but that would be great to find a proper alternative not involving the user to modify its /etc/hosts.

Do you have a JRE 8 at hand to check if it's still present?

**Comment by schuhschuh** [comment]
Hi Jonathan,

I’ve got Oracle JRE 8 installed and had the issue with this version.

Andreas

**Comment by schuhschuh** [comment]
Hold on, I might be wrong about this. Does the following mean I am actually using JRE 7 ?

```
> java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```

Because in my system preferences, it tells me Java JRE 8.

**Comment by schuhschuh** [comment]
Running the commands given in [this article](https://www.java.com/en/download/help/version_manual.xml#cmdline), it turns out I have JRE 8, but the default JDK used by applications run in the Terminal is version 7.0.

```
> /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by jopasserat** [comment]
Would something like [this](http://myshittycode.com/2014/03/17/mac-os-x-setting-default-java-version/) or [that](http://skyreacher.net/?p=90) help you set your default Java to 8?

**Comment by schuhschuh** [comment]
I'll check it out, but I think I just have to install the SDK 8. Right now, I have only the JRE 8 + JDK 7. 
```
> ls /Library/Java/JavaVirtualMachines
jdk1.7.0_51.jdk
```
Makes sense to have both at the same version. I am downloading JDK 8 right now.

**Comment by schuhschuh** [comment]
The hostname lookup issue is gone with JDK 8 (I removed the entry from /etc/hosts before trying).

**Comment by jopasserat** [comment]
Great! Then I don't think it's worth a fix which could be problematic on other platforms.
We'll try to mention that on the website though.

Thx for the help debugging this.
