### ISSUE TITLE
"Submission successful" and yet no jobs show up in queue

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#40]
One of the recent changes seems to have messed with the job submission. Even though OpenMOLE reports that the submission was successful, no job shows ever up in the SLURM or Condor queue... I already tried to rebuild OpenMOLE after "sbt clean".

It works still with commit cbee060, but not fbd6bb17.

**Comment by romainreuillon** [comment]
It was linked to 2 pb of symlink toward files to tmp files, which were removed. It is fixed now.

**Comment by schuhschuh** [comment]
I can confirm this issue should be fixed.
