### ISSUE TITLE
[Core] [Enh] Fail when a library is missing before trying to compile

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#400]
I would find it relevant for a `ScalaTask` with a `libraries` property set but for which the jar cannot be found to fail *before* trying to compile the task ? I know in the end it is exactly the same and the error in the compilation is easy to interpret in that case - but I would find it cleaner ; I do not know how it is regarding the genericity of `inputOutputCheck` ?

**Comment by JusteRaimbault** [comment]
Oh, my bad, the `InputOutputCheck` is on prototypes only. Is there a checking of other tasks properties at some points ?

**Comment by romainreuillon** [comment]
fixed in b412b8fbfbc3844c5c5eb82d972086351f9d75c6

**Comment by JusteRaimbault** [comment]
Great ! did not realize it could be done that simply !

**Comment by JusteRaimbault** [comment]
Because I looked at the generic Task only and forgot ValidateTask
