### ISSUE TITLE
Avoid copy of output file in shared storage environment

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#41]
Currently it seems the task output files must be written to either the ```tmpDir``` or ```workDir``` of the task:

```scala
protected def outputFileVariables(context: Context, tmpDir: File, workDirPath: String) = {
    val workDir = new File(tmpDir, workDirPath)

    outputFiles.map {
      case OutputFile(name, prototype, inWorkDir) ⇒
        val fileName = name.from(context)
        val file = if (inWorkDir) new File(workDir, fileName) else new File(tmpDir, fileName)
        Variable(prototype, file)
    }
  }
```

There is no option to write directly to a shared storage location outside the tasks' temporary directory. This requires thus an additional copy of the output file using a ```CopyFileHook```. Given an output file that is written by an external executable to a shared storage location which otherwise contains the linked input files, this extra copy could be avoided.

In my case, I have the following task (modified after our recent discussion tonight):
```scala
    val dofAbsPath = join(dofRig,        dofPre + refId + s",$${${srcId.name}}" + dofSuf).getAbsolutePath
    val logAbsPath = join(logDir, dofRig.getName, refId + s",$${${srcId.name}}" + logSuf).getAbsolutePath

    val dofOutPath = if (Workspace.shared) dofAbsPath else relativize(Workspace.dir, dofAbsPath)
    val logOutPath = if (Workspace.shared) logAbsPath else relativize(Workspace.dir, logAbsPath)

    val reg = ScalaTask(
      s"""
        | Config.parse(\"\"\"${Config()}\"\"\", "${Config().base}")
        | val ${dof.name} = FileUtil.join(workDir, s"$dofOutPath")
        | val ${log.name} = FileUtil.join(workDir, s"$logOutPath")
        | IRTK.ireg(${refIm.name}, ${srcIm.name}, None, ${dof.name}, Some(${log.name}),
        |   "Transformation model" -> "Rigid",
        |   "Background value" -> $bgVal
        | )
      """.stripMargin) set (
        name        := "ComputeRigidTemplateDofs",
        imports     += "com.andreasschuh.repeat.core.{Config, FileUtil, IRTK}",
        usedClasses += (Config.getClass, FileUtil.getClass, IRTK.getClass),
        inputs      += srcId,
        inputFiles  += (refIm, refId + refSuf, link = Workspace.shared),
        inputFiles  += (srcIm, imgPre + "${srcId}" + imgSuf, link = Workspace.shared),
        outputs     += (refIm, srcId, srcIm),
        outputFiles += (dofOutPath, dof),
        outputFiles += (logOutPath, log)
      ) hook (
        CopyFileHook(dof, dofAbsPath),
        CopyFileHook(log, logAbsPath)
      )
```
where the ```*OutPath``` path strings are absolute paths (i.e., equal the ```*AbsPath```) if the "Workspace.dir" is located on shared storage and a relative path otherwise. My ```FileUtil.join``` behaves similar to Python's ```os.path.join```. If the second argument is an absolute path, this absolute path is returned and the first argument ignored. I think the same should be done by the ```ExternalTask.outputFileVariables``` function. Note that if ```Workspace.shared == true```, the ```CopyFileHook``` would then just do nothing because source and destination path/file are identical. 

I suggest the following modification:

```scala
protected def outputFileVariables(context: Context, tmpDir: File, workDirPath: String) = {
    val workDir = new File(tmpDir, workDirPath)

    outputFiles.map {
      case OutputFile(name, prototype, inWorkDir) ⇒
        val fileName = name.from(context)
        val baseDir = if (inWorkDir) workDir else tmpDir
        Variable(prototype, baseDir.toPath.resolve(fileName).toFile)
    }
  }
```

**Comment by schuhschuh** [comment]
It seems that the output file is then however removed after the task finished... apparently needs some further changes to work as intended.

**Comment by romainreuillon** [comment]
This would not be portable from env to env, would it? I added a move option to the CopyFileHook, would it do the trick?

**Comment by schuhschuh** [comment]
> I added a move option to the CopyFileHook, would it do the trick?

Thanks, I will try it and see how efficient the move is. Setting the ```workDirectory```, I can ensure that the source and target directory are on the same NFS mounted file system and thus a move should be fine, even if not my preferred solution.

> This would not be portable from env to env, would it?

I think it mainly shifts responsibility to the workflow designer. Already when I write my workflow I have to specify explicitly which environment the task shall be run in (using the ```on``` keyword). Only by writing a script that is generic/configurable via command arguments or a configuration file I can make it more generic as I do in my plugin. In the given example, relative paths are used instead of absolute ones if the environment demands (configuration option ```Workspace.shared``` which corresponds to the OpenMOLE environment option ```storageSharedLocally```).

Another (less important) advantage of being able to write the program log directly to my shared workspace is that I can monitor the program execution based on these non-temporary files. Also I don't have to navigate cryptic automatically named directories and hidden ```.tmp``` directories.

The task input and output files are organised such that there are no unwanted overwrites or unnecessary task re-executions if the results already exist. All this is part of my specific workflow design, which cannot be directly realised with OpenMOLE as long as it doesn't allow me to write task output files to any location of my shared storage (unless I hide the fact that it is dealing with file paths...). Of course I am responsible then to ensure that different execution nodes can write and read from that very same location. In a shared storage environment, I just prefer more transparency and control over the data flow... OpenMOLE should mainly worry about task execution and dependencies, while I take care of where the input and output files are read from and written to.

Lastly, being able to use an absolute path in ```outputFiles``` just makes OpenMOLE more flexible, but it could still be used as it is using a ```CopyFileHook``` instead.

**Comment by schuhschuh** [comment]
On a different but related note, can the ```workDirectory``` be a local directory which is different on each execution node ? For example a directory specified in an environment variable ```TMPDIR``` which is set by the system administrator and is specific to the user/job ? Can it be something like ```workDirectory = "${TMPDIR}"``` ? Or does it have to be a directory shared by the head node of the cluster and its execution nodes ?

**Comment by romainreuillon** [comment]
I included you patch since it seems only to extends the capacity of the outputFiles system.

The workDirectory is poorly named, and is more a shared directory. I think having a real workDirectory option is easy enough to code... I am giving it a try.

**Comment by romainreuillon** [comment]
Done and tested (using /tmp/ on slurm). The sematic of the workDirectory now is actually the workDirectory on the execution node and a new arg, sharedDirectory, is used to set the path of the communication directory between the master and the execution nodes.

**Comment by romainreuillon** [comment]
I used:
```scala
 val env =
  SLURMEnvironment(
    "jpassera",
    "predict5",
    workDirectory = "/tmp/",
    storageSharedLocally = true
  )
```

**Comment by schuhschuh** [comment]
Nice, and would it also be possible to use an environment variable reference in the string value ? Such as ```workDirectory = "${TMPDIR}"``` ? This would have to be resolved on the execution node. Not sure at which point this is feasible, though. I imagine that one would use it normally within the PBS submission script passed to ```qsub```. I could test this on our college cluster (not our group internal SLURM cluster you used).

**Comment by romainreuillon** [comment]
The string is written as it is into the bash script, so I see no problem for using environment variable.

**Comment by schuhschuh** [comment]
Excellent!

**Comment by schuhschuh** [comment]
One question relating to the new ```move``` option of ```CopyFileHook```. Will the following task which has the output file of a task as input file then use the moved file from its new destination ?

**Comment by schuhschuh** [comment]
Also, the modification I had suggested initially of allowing absolute output file paths can yet not be used it seems. The problem is that OpenMOLE apparently automatically cleans up the output files... Hence, the files are written by my task, but soon after it finished they are being deleted (or moved?) without using any CopyFileHook. The following tasks consume the files just fine which means that the files are just moved by OpenMOLE somewhere else (e.g., either inside the workDirectory or sharedDirectory of the environment).

**Comment by romainreuillon** [comment]
Yes it is the expected behaviour when using the logical link system. It is allowed to move those files since there are supposed to be created by the task execution. In the general case a task uses input files to create output files. To avoid unnecessary transfers the created file are move from the workdir to the communication directory and the workdir is wiped out.

**Comment by schuhschuh** [comment]
But would it be possible to change that behavior ? To not move the file if it is actually not within the ```workDir```/```tmpDir``` of the execution task ? Because otherwise I cannot actually save any file copy. And the move operation gives me a FileNotFoundException. I am not clear how what OpenMOLE does saves transfers, but leaving the files in my final shared destination wouldn't... Because this is where I want all output files to be written to and to be perserved. They will be the input files for the following tasks, no need to copy anything because of the shared storage environment.

**Comment by schuhschuh** [comment]
> To avoid unnecessary transfers the created file are move from the workdir to the communication directory and the workdir is wiped out.

In other words, I have my very own primary "communication directory" different from the ```sharedDirectory``` and whose layout and file locations I manage myself.

**Comment by schuhschuh** [comment]
For reference, the initial request of avoiding output files to be copied on a shared storage cluster should either be dealt with by the user using ```Path``` as  variable type instead of File (cf. #46) or they should use a CopyFileHook with ```move = true```.

Before this issue can be closed, however, there is still a problem with using the move option:
```
May 06, 2015 4:54:57 PM org.openmole.core.batch.refresh.JobManager $bang
FINE: Error in job refresh
java.io.FileNotFoundException: /homes/as12312/.openmole/merapi.doc.ic.ac.uk/.tmp/dce9fe91-67da-44fd-832a-867fd829eeba/file227d5f3b-26b5-47e7-905d-55663cc86056.bin (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.openmole.tool.hash.package$.computeHash(package.scala:39)
	at org.openmole.core.fileservice.FileService$$anonfun$hash$1.apply(FileService.scala:51)
	at org.openmole.core.fileservice.FileService$$anonfun$hash$1.apply(FileService.scala:51)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at org.openmole.core.tools.cache.AssociativeCache$$anonfun$cacheMap$1$$anon$2.scala$collection$mutable$SynchronizedMap$$super$getOrElseUpdate(AssociativeCache.scala:46)
	at scala.collection.mutable.SynchronizedMap$class.getOrElseUpdate(SynchronizedMap.scala:40)
	at org.openmole.core.tools.cache.AssociativeCache$$anonfun$cacheMap$1$$anon$2.getOrElseUpdate(AssociativeCache.scala:46)
	at org.openmole.core.tools.cache.AssociativeCache.cache(AssociativeCache.scala:42)
	at org.openmole.core.fileservice.FileService$.hash(FileService.scala:48)
	at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1$$anonfun$1.apply(UploadActor.scala:75)
	at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1$$anonfun$1.apply(UploadActor.scala:75)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:108)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:108)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:108)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:108)
	at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
	at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:154)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.TreeSet.scala$collection$SetLike$$super$map(TreeSet.scala:53)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.immutable.TreeSet.map(TreeSet.scala:53)
	at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1.apply(UploadActor.scala:75)
	at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1.apply(UploadActor.scala:65)
	at org.openmole.core.workspace.Workspace.withTmpFile(Workspace.scala:211)
	at org.openmole.core.batch.refresh.UploadActor.org$openmole$core$batch$refresh$UploadActor$$initCommunication(UploadActor.scala:65)
	at org.openmole.core.batch.refresh.UploadActor$$anonfun$receive$1.apply$mcV$sp(UploadActor.scala:54)
	at org.openmole.core.batch.refresh.UploadActor$$anonfun$receive$1.apply(UploadActor.scala:50)
	at org.openmole.core.batch.refresh.UploadActor$$anonfun$receive$1.apply(UploadActor.scala:50)
	at org.openmole.core.batch.refresh.package$.withRunFinalization(package.scala:23)
	at org.openmole.core.batch.refresh.UploadActor.receive(UploadActor.scala:50)
	at org.openmole.core.batch.refresh.JobManager$DispatcherActor$.receive(JobManager.scala:81)
	at org.openmole.core.batch.refresh.JobManager$$anonfun$1$$anon$1.run(JobManager.scala:63)
```

**Comment by romainreuillon** [comment]
I think it is because subsequent tasks use this file. I updated the behaviour of the copy file hook so it inject a variable with the moved file in the context.

**Comment by schuhschuh** [comment]
Yes, I thought so. I'll give it a shot.

**Comment by schuhschuh** [comment]
I don't receive an exception, but the files are also no longer moved to the specified location.

**Comment by romainreuillon** [comment]
Could they by any chance be moved, and moved again?

**Comment by schuhschuh** [comment]
I don't think so because not even the output directory is being created (unless it's removed right after as well again).

**Comment by romainreuillon** [comment]
Could you try to add some println in the copyfilehook to check what happens.

**Comment by schuhschuh** [comment]
Ok, no this is odd. I added a println to the file hook. After recompiling, the files are moved as before but I get the FileNotFoundException again... I am recompiling now making sure I clean all build files before and will try again.

**Comment by schuhschuh** [comment]
Sorry, my bad before, I apparently didn't actually pull the changes from upstream... the FileNotFoundException is still present :( I recompiled several times after "clean" just to make sure.

Gotta go now, though.

**Comment by romainreuillon** [comment]
I just pushed a fix, it should work now.

**Comment by schuhschuh** [comment]
Perfect timing! I was just going to give it another try.

**Comment by schuhschuh** [comment]
It's working!
