### ISSUE TITLE
[Plugin] [UDocker] Issue with quote escaping

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#411]
I fail running a container with a command implying quote, escaping or not etc. it appears that what we give to udocker in the end is not the expected string (maybe with an extra level of escaping ?). this may have to do with the `blockChars` in `UDockerTask`, or with the command parser ; I try to investigate.
@romainreuillon you think this is worth spending time on this as the new scala library for containers should be integrated at the coding camp ? (but since I need to run my stuff immediately so anyway will try to fix it)

**Comment by romainreuillon** [comment]
It is worth, the parser will still be in used after the migration.

**Comment by JusteRaimbault** [comment]
ok I investigate this then ! @openmolebot counting on your help ;)

**Comment by JusteRaimbault** [comment]
Thanks to @openmolebot , more info : with the same exact openmole (commit 540b7e0fd38eda841622b5ed2d1fc3bafd70d4ba ), same python2, same udocker tarball, same OS (ubuntu 18.04), behavior with quotes differs : with the latest ubuntu docker image, the hello world task

```
val task = UDockerTask(
image = workDirectory / "ubuntu.tgz",
      run = "echo \"hello world\""
)
task
```

produces in output
`hello world`
on one machine and
`"hello world"`
on the other.

I guess the second behavior is wrong and we have to find the default environment variables to trick to avoid this

**Comment by JusteRaimbault** [comment]
Previous comment is not exact on the fact that it was the same openmole commit (I did not see that one build failed on one machine and it was still an old version).
So this difference in behavior is between the current version and an older from January or February

**Comment by JusteRaimbault** [comment]
More puzzling : 
```
val task = UDockerTask(
image = workDirectory / "ubuntu.tgz",
   run = "sh -c \"ls -a\""
)
task
```
fails with an unterminated quoted string

**Comment by JusteRaimbault** [comment]
` run = "sh -c \"ls\""` works so we may have a problem with the parser for the space in the escaped string (could not be considering being inside a string and cutting at the space)

**Comment by JusteRaimbault** [comment]
issue with space in quoted string confirmed, as the first parses to `List(/usr/bin/env, python2, /home/raimbault/.openmole/iscpif-201741-dell-XPS-13-9360/.tmp/685aeb9b-e900-4e38-ba89-0cfcf04f86cd/executionffc50b28-a801-4b83-afae-9cacbdf117a5/udocker/udocker, run, --workdir=/, d5da8ca8-80a3-3bd6-9381-15c2d0959faf, bash, -c, "ls")`
while the second to `List(/usr/bin/env, python2, /home/raimbault/.openmole/iscpif-201741-dell-XPS-13-9360/.tmp/685aeb9b-e900-4e38-ba89-0cfcf04f86cd/execution04d688dc-e91c-480d-9c55-127086527936/udocker/udocker, run, --workdir=/, 0aabcb1c-5ef4-3898-a500-8307bf3a7f7a, bash, -c, "ls, -a")`

**Comment by JusteRaimbault** [comment]
commit 2050432310139d698a7284ffa2f3e75eaad4d0c1 introduced blockchars for udocker - this seems to be incompatble with the systemexec parser ; let's modifiy it to add an option to keep quotes or not to comply with docker or not

**Comment by JusteRaimbault** [comment]
4017c3464b9b6c7ff73c4dd30d03ff7c2e5786e9 fixes this (and prepared my night for the escape of the quote escaping nightmares)
