### ISSUE TITLE
[Website] Search feature

### ISSUE THREAD

**Issue by helenea** [openmole/openmole#414]
In the search bar, when typing, the first item of the suggestion list has grey background and is selected if you hit Enter, but it is not possible to navigate among the other items on the suggestion list.
Would it be possible to navigate with the arrow keys in the suggestion list? If not I think it would be better to remove the grey background of the first item as it is misleading.

**Comment by mathieuleclaire** [comment]
It is still developped, but indeed it does not work any more.
