### ISSUE TITLE
[Plugin] [NetLogoTask] Use scala NetLogo API

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#417]
NetLogo 6 has a scala api working with scala 2.12 ; however NetLogo 5 scala api is only compatible with scala 2.9. Is it possible to use a specific version of scala for one module ?
Then we could get rid of the java interface and classes. Otherwise using 6 api is not worth it as the task would no longer be generic between 5 and 6.
Anyway I think we go towards a imminent deprecation of NL5 task I guess, the rule is now NL6 since several years. (but ok as we discussed it's good to keep it for reproducibility, but maintaining :/ )

**Comment by romainreuillon** [comment]
We should keep the java classes. OpenMOLE will be migrate to scala 2.13 in a few month and NetLogo will stay on 2.12 for some time. The java classes will still be required for some years, until TASTY is a common thing in the scala ecosystem.

**Comment by JusteRaimbault** [comment]
ah yes I did not think of this, and furthermore if we switch to dotty soon after ; closing the issue then.
