### ISSUE TITLE
Problem with python -c in udocker

### ISSUE THREAD

**Issue by julienperret** [openmole/openmole#422]
I'm running into a problem while executing python commands inside a docker image.

Python command : 
"""python3 -c 'from simurba import Simulation; s=Simulation("openmole", "inputs/${pixRes} output ${growth} ${finalYear} ${scenario} ${pluPriority} ${buildNonRes} ${exclusionRatio} ${maxBuiltRatio} ${maxUsedSrfPla} ${densifyOld} ${winSize} ${minContig} ${maxContig} ${roadRatio} ${fitTo} ${seed} ${ecoWeight} ${roadWeight} ${sirWeight} ${traWeight} ${tiff} ${snaps} ${verbose}");s.run();'"""

yields an error :
  File "<string>", line 1
    'from
        ^
SyntaxError: EOL while scanning string literal

MWE:
val pixRes = Val[String]
val growth = Val[Double]
val finalYear = Val[Int]
val scenario = Val[Double]
val pluPriority = Val[Double]
val buildNonRes= Val[Double]
val exclusionRatio = Val[Double]
val maxBuiltRatio = Val[Double]
val maxUsedSrfPla = Val[Double]
val densifyOld = Val[Double]
val winSize = Val[Double]
val minContig = Val[Double]
val maxContig  = Val[Double]
val roadRatio = Val[Double]
val fitTo = Val[String]
val ecoWeight = Val[Double]
val roadWeight = Val[Double]
val sirWeight = Val[Double]
val traWeight = Val[Double]
val tiff = Val[String]
val snaps = Val[String]
val verbose = Val[String]
val seed = Val[Int]

val dataDir = Val[File]
val outputDir = Val[File]
val output = Val[File]
val measures = Val[File]

val restePop = Val[Int]
val resteSrf = Val[Double]
val peuplementMoyen = Val[Double]
val artifNouvSum = Val[Double]
val srfBatiSolNouvSum = Val[Double]
val srfBatiPlaNouvSum = Val[Double]
val expansionSum = Val[Int]
val cumImpact = Val[Double]
val txArtifMoyen = Val[Double]
val dsfBatiSolSum = Val[Int]
val dsfBatiPlaSum = Val[Int]
val m2SolHabFinal = Val[Double]

val pyCareTask = UDockerTask(
DockerImage(image = "vidlb/pysimurba", tag = "latest", registry = "https://registry.gitlab.com"),
"""python3 -c 'from simurba import Simulation; s=Simulation("openmole", "inputs/${pixRes} output ${growth} ${finalYear} ${scenario} ${pluPriority} ${buildNonRes} ${exclusionRatio} ${maxBuiltRatio} ${maxUsedSrfPla} ${densifyOld} ${winSize} ${minContig} ${maxContig} ${roadRatio} ${fitTo} ${seed} ${ecoWeight} ${roadWeight} ${sirWeight} ${traWeight} ${tiff} ${snaps} ${verbose}");s.run();'"""
) set (
    pixRes := "100m",
    dataDir := workDirectory / "inputs",
    finalYear := 2040,
    maxUsedSrfPla := 200.0,
    maxContig := 1.0,
    roadRatio := 0,
    fitTo := "zone",
    seed := 5,
    ecoWeight := 1.0,
    roadWeight := 2.0,
    sirWeight := 4.0,
    traWeight := 3.0,
    tiff := "False",
    snaps := "False",
    verbose := "False",
    growth := 0.01,
    scenario := 0.0,
    pluPriority := 0.0,
    buildNonRes := 0.0,
    exclusionRatio := 0.0,
    maxBuiltRatio := 50.0,
    densifyOld := 0.0,
    winSize := 3.0,
    minContig := 0.0,
    maxContig := 0.6,
    inputs += (growth, scenario, pluPriority, buildNonRes, exclusionRatio, maxBuiltRatio, densifyOld, winSize, minContig, maxContig),
    outputs += (growth, finalYear, scenario, pluPriority, buildNonRes, exclusionRatio, maxBuiltRatio, maxUsedSrfPla, densifyOld, winSize, minContig, maxContig, roadRatio, fitTo, seed, ecoWeight, roadWeight, sirWeight, traWeight),
    inputFiles += (dataDir, "inputs"),
    outputFiles += ("output/measures.csv", measures)
)
pyCareTask

**Comment by JusteRaimbault** [comment]
😿 😿 😿 😭 this summons my worse nightmares of escaping the escaping the escaping the ........ the escaping of quotes [STACKOVERFLOW ERROR] - sell maybe stopping escaping this nightmare will make me escape other nightmares - I may see what happens, the thing is for the docker task to pass the system command we need an array of strings, so we had to tell to not split "user commands" (see [issue 411](https://github.com/openmole/openmole/issues/411) ) - I remember doing it for double quote but may have forgotten the single quote in that - I check that and tell you asap

**Comment by JusteRaimbault** [comment]
ok I see exactly where the problem is (in `systemexec` parser) but I do not know why it occurs as we treat single and double quotes exactly the same way 🤕

**Comment by JusteRaimbault** [comment]
or we do not handle properly the state `inDoubleQuote` when already inside a single quote

**Comment by JusteRaimbault** [comment]
your command parses to 
`Vector(python3, -c, 'from simurba import Simulation; s=Simulation("openmole", "inputs/${pixRes} output ${growth} ${finalYear} ${scenario} ${pluPriority} ${buildNonRes} ${exclusionRatio} ${maxBuiltRatio} ${maxUsedSrfPla} ${densifyOld} ${winSize} ${minContig} ${maxContig} ${roadRatio} ${fitTo} ${seed} ${ecoWeight} ${roadWeight} ${sirWeight} ${traWeight} ${tiff} ${snaps} ${verbose}");s.run();')` in the version where the issue with user command was corrected, so the parsing is good and it should work.
Could you please tell me if you're openmole includes [this commit 4017c3464](https://github.com/openmole/openmole/commit/4017c3464b9b6c7ff73c4dd30d03ff7c2e5786e9) which was the one correcting this issue ? (which was introduced a bit less than one year ago, what would be consistent if your task was working one year ago)

**Comment by JusteRaimbault** [comment]
it should be that, as without the fix you end up trying to execute
`python3 -c from simurba import Simulation; ...` with quotes removed, what gives the error you get.
imbricated quotes are not a problem indeed

**Comment by julienperret** [comment]
I use the snapshot built on 22/04/2019.
I can try and update it though.
It seems to act as if I ran `python -c "from"` (precisely the same error)
I'm lost.
We found a workaround (put everything in a python file), but I think we should still try to understand what happens here...

**Comment by julienperret** [comment]
If you think this is too specific, we can close it though.

**Comment by JusteRaimbault** [comment]
no its not specific its exactly the generic "keep quote or not in user command" problem we also had with shell commands for example.
the fix was on 30th April so my 50 cents it will work after an update ;)

**Comment by julienperret** [comment]
It works!
You rock @JusteRaimbault :muscle: :heart:
Thanks

**Comment by JusteRaimbault** [comment]
nice ! ^_^
