### ISSUE TITLE
[Doc] Typed signatures of Profile and PSE seems broken

### ISSUE THREAD

**Issue by chapinux** [openmole/openmole#424]
Typed signatures seems weird, e.g. some symbols in the description text do not match the type expression elements. 
Suggestion :  write them in LateX formulas converted in pictures to replace the nasty scalatex formulas ?
I can handle the picture integration in the website

**Comment by JusteRaimbault** [comment]
could we use mathjax for this or is it too complicated to integrate with scalatex ?
also are method signatures appropriate on methods principal page ? maybe a separate page for "methods as typed function" could be easier for beginners to grasp methods without getting into that complicated approach ?

**Comment by JusteRaimbault** [comment]
@chapinux is it crucial for release 9 ? or can we put this the the v10 milestone ?

**Comment by helenea** [comment]
Should not take too long, I would leave it for v9 if someone feels up to it.

**Comment by JusteRaimbault** [comment]
we just discussed this and integrating mathjax shouldnt be too hard but hard enough to be integratable in 10 and not 9

**Comment by helenea** [comment]
Sorry I was not clear, I was talking about fixing the broken formulas with images for v9, to not let something obviously wrong in the doc ;)

**Comment by romainreuillon** [comment]
For me, we can even remove the mathematical expressions.... I am not sure that it helps the understanding. What do you think on this matter?

**Comment by helenea** [comment]
Agreed, we should remove it for v9.
A separate page with more mathematical details on all methods could be nice for v10, as Juste suggested. Same as GA details for instance.

**Comment by helenea** [comment]
I removed the typed signatures from the methods. However, I put them in another file (in the same folder) which doesn't appear on the website, in case we want to put them back in (MethodsTypedSignatures.scalatex).

**Comment by JusteRaimbault** [comment]
perfect, the issue is closed then !
