### ISSUE TITLE
[Plugin][PythonTask] take into account python2

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#428]
python2 script will fail for now - only python3 is implemented

**Comment by JusteRaimbault** [comment]
[2696dea5a](https://github.com/openmole/openmole/commit/2696dea5a5791671a3226283c957bf8899e861ec) implements this

**Comment by jopasserat** [comment]
If it's too much of a hassle i'd say we shouldn't bother: python2 will be deprecated next year.

Default behaviour should always be python3 and maybe have two aliases: python3 and python2 with default to 3.

On 27 May 2019 11:24:49 CEST, Juste Raimbault <notifications@github.com> wrote:
>python2 script will fail for now - only python3 is implemented
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openmole/openmole/issues/428

-- 
Jonathan Passerat-Palmbach, PhD
Research Associate
Department of Computing
Imperial College London

South Kensington Campus
Huxley Building
180 Queen's Gate
London SW7 2AZ

https://jopasser.at

**Comment by JusteRaimbault** [comment]
it was quite straigthforward so no pb, and yes the default behavior of the pythontask is python 3, there is an optional argument for the user to explcitly run python2 or break everything by trying to run python1 or 4 ^-^
