### ISSUE TITLE
[GUI] Download files from URL

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#429]
Make it possible to download file from a url in the GUI (import).

Optionally the user can choose to extract the file after the download using a checkbox.

**Comment by mathieuleclaire** [comment]
Note that since the downloadHttp method returns Unit, it is not possible for now to manage possible problems when downloading (error 404 for instance).

**Comment by romainreuillon** [comment]
I'll make this return return an error in case it fails this week....

**Comment by romainreuillon** [comment]
Fixed in : af9a9d3c41d2154af768354301828adc6c976d2a

**Comment by mathieuleclaire** [comment]
Well, it is not managed from client side yet.

**Comment by mathieuleclaire** [comment]
Actually you did, sorry. We'll need to refactor this error message too.
