### ISSUE TITLE
Write Release Notes for v9

### ISSUE THREAD

**Issue by helenea** [openmole/openmole#433]
All in the title :wink: 
https://openmole.org/Release+Notes.html

**Comment by romainreuillon** [comment]
* Change version number
* Change name

**Comment by JusteRaimbault** [comment]
do we really need to write everything that changed ? (would take way too long, no ?)

**Comment by helenea** [comment]
Maybe just "big" things or categories of things?

**Comment by JusteRaimbault** [comment]
yes seems fair ! (now lets remember the big things ;) )
also there is still no name for version 8 on the website ^-^

**Comment by helenea** [comment]
Yes there is if someone accepts my merge request :innocent:
