### ISSUE TITLE
[Plugin][SaltelliSensitivity] Provisory estimators for sensitivity indices

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#435]
It seems that Saltelli indices are computed only when all samples have been run; in the case of a high number of samples and hazardous computation environments, it would be nice to have "provisory estimators", computing the current state of indices let say at 50%, 75%, etc. of samples achieved (so we have already an honest result without waiting forever the stalled jobs to finish)

**Comment by romainreuillon** [comment]
You cannot make sure that the results you get are not biased in some way (linked to a longer execution time for the mode in some part of the space of parameter).

And technically this would be hard to achieve in OpenMOLE. Working on making the execution run more smoothly seem more promising, than a workaround as this one....

**Comment by JusteRaimbault** [comment]
Indeed this could introduce significant bias if the model fails/take longer in a particular region of the parameter space - this could be checked by verifying the "lhs-itude" of successful runs but not sure to what extent this would be enough.
If it's furthermore technically complicated, let's close the issue then, and run Saltelli with reasonable number of sampled ^-^
(what could be useful though would be convergence measures - specific central limit theorems are not provided in Saltelli paper, maybe a standard thing could do)
