### ISSUE TITLE
Documentation Plugin Development

### ISSUE THREAD

**Issue by francoismaths** [openmole/openmole#449]
Dear OpenMole Team,

In the plugin development documentation page, (https://next.openmole.org/Plugin+Development.html), the object «Hello» is used in the example. 
I had an execution failed when I imported a JAR and adding the following line in the OpenMOLE script: 
plugins += pluginsOf(myopenmoleplugin.ObjectName), 
whereas it runs with a class:
plugins += pluginsOf(myopenmoleplugin.ClassName).

François

Here are the firsts lines of the error I got:

> Java.lang.LinkageError: loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @17b016ac wants to load interface scalaz.Functor. A different interface with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @517a2b0. (scalaz.Functor is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @517a2b0, parent loader 'platform')
> at org.openmole.core.console.ScalaREPL$ErrorPosition$$anon$7.modifyF(ScalaREPL.scala:69)
> 	at org.openmole.core.console.ScalaREPL$ErrorPosition$$anon$7.modifyF(ScalaREPL.scala:69)
> 	at monocle.PLens$$anon$5.modifyF(Lens.scala:191)
> 	at monocle.PTraversal$$anon$2.$anonfun$modifyF$3(Traversal.scala:122)
> 	at monocle.PPrism.$anonfun$modifyF$3(Prism.scala:49) ...

**Comment by JusteRaimbault** [comment]
If you look at how the method `pluginsOf` is defined in the jvm task plugin (`org.openmole.plugin.task.jvm`), you can either do `pluginsOf(o: Any)` - this should work for an object as it is a class with a single instance; or `pluginsOf[T]` where you need an implicit manifest for the type T, or `pluginsOf(clazz: Class[_])` where you provide explicitly the `java.lang.Class`.
I guess you are in the first case, but not sure why it does not work.
From your error it looks like you already loaded `scalaz` from elsewhere and that you are trying to load it again, but I can not understand more.
Do you get this bug with the plugin example or with your own code ?

**Comment by francoismaths** [comment]
Thank you Juste for your answer.
I am indeed in the first case, I get this error with my own code.

**Comment by JusteRaimbault** [comment]
Ok found the problem: you are using `pluginsOf[T]` and not `pluginsOf(object)` in your script, so it should be trying to transform the object in a type and calling monocle and missing scalaz.Applicative (no idea why exactly the last points though)
Replacing the brackets with parenthesis makes it work.
