### ISSUE TITLE
Introduce user to concept of "File" vs "Path" variable type

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#46]
Thanks to @romainreuillon clarifications, the `java.io.File` type should be used for a variable representing a file content rather than the file path only. Where this content is stored temporarily in order to provide it as input to a task is up to OpenMOLE and hidden from the user. The `java.nio.Path` type can be used, on the other hand, to treat the variable value as descriptor of a file location on a shared storage. OpenMOLE does not modify this path or touch the files referred to by it.

This issue is a reminder to document this in the online manual. I am happy to provide a PR for it.

**Comment by jopasserat** [comment]
We were thinking of it maybe as an advanced tutorial gathering all the good practice on clusters.

**Comment by jopasserat** [comment]
fixed in aa32cd39e0f30fd336f7152a88d7d7305abbfc7b
