### ISSUE TITLE
simulation on cluster fails with "run.sh syntax error" with openmole 12 snapshot

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#460]
Dear belove OpenMole community,

when using OpenMole 12 - snapshot, any run (including with simple examples working locally such as Ants) ends with failures in the cluster environment, with the error message:
```
OpenMOLE job execution failed on remote environment
org.openmole.core.exception.InternalProcessingError: Job status is FAILED
DETAILS:
Stdout was:

stderr was:
run.sh: 39: run.sh: Syntax error: word unexpected (expecting ")")
```

I'll test again with version 11 and 9.2 to ensure it's not a problem on our cluster, but this is unlikely.
I'll try to read what is in this `run.sh` file. 

Sam

**Comment by samthiriot** [comment]
Same problem with version 11.

the line of interest in `run.sh` is 39:
```
 36
 37 for a in $@
 38 do
 39   if [[ $a == "--debug" ]]; then FLAG+=("-XX:-OmitStackTraceInFastThrow"); fi
 40 done
 41
 42
```

**Comment by romainreuillon** [comment]
That's a bit of code I added not long ago. My guess is that it is not a legit /bin/sh syntax...

**Comment by samthiriot** [comment]
Is it possible the `--debug` flag is added when running Openmole in docker containers but not with a regular install?

**Comment by romainreuillon** [comment]
No it is an option of the environment. We could get rid of this piece of code, it is not near from essential.

**Comment by samthiriot** [comment]
> 
> 
> That's a bit of code I added not long ago. My guess is that it is not a legit /bin/sh syntax...

Maybe this syntax is more POSIX?
```
  if [[ $a == "--debug" ]]; then FLAG="$FLAG -XX:-OmitStackTraceInFastThrow"; fi
````

(Notice the space before `-XX` which was missing)

**Comment by romainreuillon** [comment]
Okay lets try

**Comment by romainreuillon** [comment]
I just pushed a new 12.0-SNAPSHOT docker image.

**Comment by samthiriot** [comment]
I try it now, thanks.

**Comment by samthiriot** [comment]
Problem fixed with your patch, awesome, thanks!
