### ISSUE TITLE
Cannot find bash on NixOS when running openmole

### ISSUE THREAD

**Issue by guillaumecherel** [openmole/openmole#462]
I just switched to NixOS and am setting up my environment to build openmole.

I'm getting there, but after a fresh build, running openmole gives:

```
[nix-shell:~/Work/Dev/all/openmole]$ openmole/bin/openmole/target/assemble/openmole
bash: openmole/bin/openmole/target/assemble/openmole: /bin/bash: bad interpreter: No such file or directory
```

An easy way to fix this would be to replace the shebang `#!/bin/bash` by `#!/usr/bin/env bash` in the generated executable `openmole/bin/openmole/target/assemble/openmole`. It would still work on any linux distro (I think env is POSIX).

Would this be possible?

(NixOS doesn't put the executables, libs, etc in the standard directories, such that for example multiple versions of a software can be installed, each in a unique path, and other softwares can always refer to them unambiguously.)

**Comment by romainreuillon** [comment]
This seems fine to me. Fixed in d92c3ddf963603d33649b2d154c9de2b022dfc08.
