### ISSUE TITLE
Why do outputFiles variables need to be set in ScalaTask?

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#47]
Currently it is required to set each File path of a variable in the ```outputFiles``` list within the ScalaTask. However, I cannot see a reason why this should be necessary. The value of these variables is specified already as part of the outputFiles declaration:

```scala
val f = Val[File]
val task = ScalaTask(" ... ") set (outputFiles += ("path/to/output/file", f))
```

Further, I think that similar to the change of the inputFiles variables (cf. #34), the outputFiles variable should be available within the ScalaTask with a path preset to be ```java.io.File(workDir, "path/to/output/file")```. If the output file should be written to the ```tmpDir``` instead, there could also be a ```inWorkDir``` option as for input files.

So as example, instead of:

```scala
val task = ScalaTask(
  """
    | val f = new java.io.File(workDir, "path/to/output/file")
    | val w = new java.io.FileWriter(f)
    | w.write("Why not preset f ?")
    | w.close()
  """.stripMargin) set (
    outputFiles += ("path/to/output/file", f)
  )
```
which requires me to twice specify the same path, I would like to simplify this to:
```scala
val task = ScalaTask(
  """
    | val w = new java.io.FileWriter(f)
    | w.write("Now I just specify the path once, as argument of ExternalTaskBuilder.addOutputFile!")
    | w.close()
  """.stripMargin) set (
    outputFiles += ("path/to/output/file", f)
  )
```
if you want to support writing to the ```tmpDir``` instead of ```workDir```, I would do:
```scala
val task = ScalaTask(
  """
    | val w = new java.io.FileWriter(f)
    | w.write("Now I just specify the path once, as argument of ExternalTaskBuilder.addOutputFile!")
    | w.close()
  """.stripMargin) set (
    outputFiles += ("path/to/output/file", f, inWorkDir = false)
  )
```

**Comment by romainreuillon** [comment]
Actually you can use:
```scala
val task = ScalaTask(
  """
    | val w = new java.io.FileWriter(f)
    | w.write("Now I just specify the path once, as argument of ExternalTaskBuilder.addOutputFile!")
    | w.close()
  """.stripMargin) set (
    outputs += f
```

So you don't need to specify the path for the file in output.

**Comment by romainreuillon** [comment]
I edited the code, now is looks more correct.

**Comment by schuhschuh** [comment]
Well, but that doesn't work for me as long as I cannot control the extension of the ```newFile``` because the programs we use depends on it to know what type of file it is dealing with.

**Comment by romainreuillon** [comment]
You can use:
```scala
val f = new File(workDir, "blabla.bla")
```
and output += f, it will work.

**Comment by schuhschuh** [comment]
Fair enough!
