### ISSUE TITLE
NSGA2 with only one objective is still exploring a 2D Pareto front on a stochastic model

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#473]
Dear beloved OpenMole and mgo communities,

if we run NSGA2 with only one objective, on a stochastic model, several results are still returned. In theory with only one objective in a PAreto front, we would only expect one best result. 

Can you confirm my understanding? 
I bet in the case of stochastic models, the count of samples is also used as an objective by NSGA2. 
This is probably a way not to exclude a past result which had many samples (so, with a high confidence) to replace it with a new solution which is only better by chance. 
So your implementation also deals with stochasticity by using the count of sample (related to our level of confidence in the solution) as a goal. 

Is this right? 
In this case I'll update the doc. 

Thanks,

Sam

**Comment by romainreuillon** [comment]
Dear Sam,

you got it right. The number of samples it added as a goal to maximize. It means that you'll get a compromise between good fitnesses with low number of samples and and less good fitnesses with high number of samples.

you're welcome,
Romain

**Comment by samthiriot** [comment]
Perfect, thanks. I'll propose an update of the doc package to mention that.

**Comment by JusteRaimbault** [comment]
There's already a dedicated page in the doc for this, which is linked from the GA page: https://next.openmole.org/Stochasticity+Management.html
