### ISSUE TITLE
SavePopulationHook: headers are not always written in CSV files

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#478]
Hello,

a little bug without huge consequence: when SavePopulationHook is ran for the first time, when the file it should write does not yet exists, it writes the headers of the CSV file. 

Then if it is ran a second time and finds an existing CSV file, it overwrite this file, but does not write the header any more. 

I took me a bit of time to understand why I was loosing headers sometimes and getting them sometimes ;-)

Sam

**Comment by romainreuillon** [comment]
Dear Sam,
this 66f34e29df198139b13eca9d7284542b67b562e3 should fix it,
thx for the report !
