### ISSUE TITLE
No jobs run after successful submission due to failed runtime installation

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#48]
When I set the ```sharedDirectory``` of the SLURMEnvironment to a custom path located on storage shared by submission, head, and compute nodes, no jobs show up in the queue and are executed even though OpenMOLE reports that the submission was successful. When ```sharedDirectory = None``` it works fine.

**Comment by romainreuillon** [comment]
When it does that, it means that the jobs crash very quickly. Could you tell me, how can I reproduce that on predict?

**Comment by schuhschuh** [comment]
I'll prepare a test workflow

**Comment by schuhschuh** [comment]
I remember that when I encountered this first yesterday, I saw a Java related error. That some java command argument (-X...) was not recognised.

You can try yourself by running the Bash script ```/homes/as12312/Data/Registrations/openmole-sharedDirectory-issue.sh``` in a directory you have write permission for. It will create a subdirectory named ```OpenMOLESharedDirectoryTest``` and change to it before adding symbolic links to the required binaries and input data files. It then runs OpenMOLE (must be on the PATH) with my plugin loaded. You can start the workflow using
```scala
import com.andreasschuh.repeat.workflow._
val ex = PreRegistration().start
```

Within this subdirectory, the sharedDirectory of the environment is ```Workspace/.openmole``` and the workDirectory is unchanged (```None```).

The relevant source files of my plugin if needed are in /homes/as12312/Code/REPEAT/src/main/scala/com/andreasschuh/repeat/
- core/Environment.scala
- puzzle/RegisterToTemplateRigid.scala
- workflow/PreRegistrations.scala

**Comment by romainreuillon** [comment]
It submit and run the job from Joe's account however your code doesn't run:
```-----------------Output on remote host-----------------
> "/homes/jpassera/romain/testshu/OpenMOLESharedDirectoryTest/Bin/IRTK/ireg" "/tmp/3b90773e-a610-4746-b627-dd7da1e4f1b3/.tmp/b2f17b1a-20cb-4122-9df9-54ba5168267d/category4f780835-e5eb-4d5b-a71c-7c9f8dba72db/mni305.nii.gz" "/tmp/3b90773e-a610-4746-b627-dd7da1e4f1b3/.tmp/b2f17b1a-20cb-4122-9df9-54ba5168267d/category4f780835-e5eb-4d5b-a71c-7c9f8dba72db/1000_3.nii.gz" "-threads" "1" "-dofout" "/tmp/3b90773e-a610-4746-b627-dd7da1e4f1b3/.tmp/b2f17b1a-20cb-4122-9df9-54ba5168267d/category4f780835-e5eb-4d5b-a71c-7c9f8dba72db/result.dof.gz" "-par" "Transformation model = Rigid" "-par" "Background value = 0"

/homes/jpassera/romain/testshu/OpenMOLESharedDirectoryTest/Bin/IRTK/ireg: error while loading shared libraries: libarpack.so.2: cannot open shared object file: No such file or directory

> "/homes/jpassera/romain/testshu/OpenMOLESharedDirectoryTest/Bin/IRTK/ireg" "/tmp/3b90773e-a610-4746-b627-dd7da1e4f1b3/.tmp/b2f17b1a-20cb-4122-9df9-54ba5168267d/category86523bdf-0278-422e-96d0-e1e70126018e/mni305.nii.gz" "/tmp/3b90773e-a610-4746-b627-dd7da1e4f1b3/.tmp/b2f17b1a-20cb-4122-9df9-54ba5168267d/category86523bdf-0278-422e-96d0-e1e70126018e/1002_3.nii.gz" "-threads" "1" "-dofout" "/tmp/3b90773e-a610-4746-b627-dd7da1e4f1b3/.tmp/b2f17b1a-20cb-4122-9df9-54ba5168267d/category86523bdf-0278-422e-96d0-e1e70126018e/result.dof.gz" "-par" "Transformation model = Rigid" "-par" "Background value = 0"

/homes/jpassera/romain/testshu/OpenMOLESharedDirectoryTest/Bin/IRTK/ireg: error while loading shared libraries: libarpack.so.2: cannot open shared object file: No such file or directory

> "/homes/jpassera/romain/testshu/OpenMOLESharedDirectoryTest/Bin/IRTK/ireg" "/tmp/3b90773e-a610-4746-b627-dd7da1e4f1b3/.tmp/b2f17b1a-20cb-4122-9df9-54ba5168267d/category2289b492-be3a-4bb4-b50b-38446cba4d87/mni305.nii.gz" "/tmp/3b90773e-a610-4746-b627-dd7da1e4f1b3/.tmp/b2f17b1a-20cb-4122-9df9-54ba5168267d/category2289b492-be3a-4bb4-b50b-38446cba4d87/1001_3.nii.gz" "-threads" "1" "-dofout" "/tmp/3b90773e-a610-4746-b627-dd7da1e4f1b3/.tmp/b2f17b1a-20cb-4122-9df9-54ba5168267d/category2289b492-be3a-4bb4-b50b-38446cba4d87/result.dof.gz" "-par" "Transformation model = Rigid" "-par" "Background value = 0"

/homes/jpassera/romain/testshu/OpenMOLESharedDirectoryTest/Bin/IRTK/ireg: error while loading shared libraries: libarpack.so.2: cannot open shared object file: No such file or directory
```

**Comment by schuhschuh** [comment]
I expected that the shared libraries will not be found, you might need to add the library path given in the Bash script to the .bashrc. But it's not really important for this issue.

I had an instance before when it was running the jobs also in my account, but then it didn't again...

**Comment by jopasserat** [comment]
Yep it probably doesn't work because of the way we're running bash in 
OpenMOLE.
@schuhschuh is write, it should work by editing .bashrc (just done it in 
my account)

On 07/05/15 12:53, Andreas Schuh wrote:
>
> I expected that the shared libraries will not be found, you might need 
> to add the library path given in the Bash script to the .bashrc. But 
> it's not really important for this issue.
>
> I had an instance before when it was running the jobs also in my 
> account, but then it didn't again...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openmole/openmole/issues/48#issuecomment-99831472>.
>

-- 
Jonathan Passerat-Palmbach, PhD
Research Associate
Department of Computing
Imperial College London

South Kensington Campus
Huxley Building - room 344
180 Queen's Gate
London SW7 2AZ

**Comment by schuhschuh** [comment]
I copied the SLURM job error output before it get deleted:
```
> cat 64798f57-e8df-476b-a9e9-c318aa2a9725.err 
slurmd[predict1]: task/cgroup: plugin not compiled with hwloc support, skipping affinity.
sh: 0: Can't open run.sh
```

**Comment by schuhschuh** [comment]
And this directory:  Workspace/.openmole/install/b6a903dd-ee14-4059-8d2e-093bd51876c4_install is I believe missing some files. There is only the shell script ```install_c8316063-2ca5-44b3-bcbf-7a133808ebfc.sh```, but the subdirectories are empty.

**Comment by schuhschuh** [comment]
Further, the ```persistent``` directory only contains a link to my plugin .jar file. If I remember correctly it used to contain links to also the OpenMOLE .jar files before.

**Comment by schuhschuh** [comment]
Here's the output of ```tree Workspace/.openmole``` right after the submission successful message:
```
.openmole/
├── b6a903dd-ee14-4059-8d2e-093bd51876c4
│   ├── persistent
│   │   └── 1431000668846_3ba35645-699c-43af-8791-092702f2373c.rep
│   └── tmp
│       └── 1431000668368
│           └── 722e6217-67a3-41d2-9747-93467f820508
│               ├── 6e771833-26c3-4443-bf29-bd7a888cdca4.err
│               ├── 6e771833-26c3-4443-bf29-bd7a888cdca4.out
│               ├── 6e771833-26c3-4443-bf29-bd7a888cdca4.slurm
│               ├── job_83131ab3-af0d-410d-97f0-59632884c988.in
│               ├── job_d53042e1-6f11-47ec-ad36-bde9badf21a7.tgz
│               └── run_d0754cee-7145-40ac-849f-314fd968ba65.sh
└── install
    └── b6a903dd-ee14-4059-8d2e-093bd51876c4_install
        └── runtime9c8e0a6f984f597e4afc7e1cdeb3272f992a1b09
            └── envplugins
```

**Comment by romainreuillon** [comment]
It seem to be a pb with your runtime installation. Did you remove the openmole shared folder manually at some point? I yes, it is probably a caching pb, you should wipe out the db or it will check if the file have been deleted after 1h.

**Comment by schuhschuh** [comment]
Ah, that sounds like it. Every time before I run OpenMOLE, I wipe out the ```Workspace``` directory, hence, also the sharedDirectory of the environment. So I guess I'm not supposed to do that...

**Comment by schuhschuh** [comment]
So I killed the dbserver and deleted the .openmole/merapi.doc.ic.ac.uk/db folder. When I run the WF then, it uploaded way more replica again. However, the runtime is still not properly installed.

**Comment by romainreuillon** [comment]
To test I will clear Joe's account free of OpenMOLE file and retry...

**Comment by schuhschuh** [comment]
Ok, just make sure to use the previous built of my plugin .jar file in ```/homes/as12312/Data/Registrations/Bin/repeat_2.11-0.1.jar``` as used by ```/homes/as12312/Data/Registrations/openmole-sharedDirectory-issue.sh``` b/c I recompiled the plugin in Code/REPEAT with ```sharedDirectory=None```.

**Comment by romainreuillon** [comment]
I got some results:
```

-----------------Output on remote host-----------------

> "/homes/jpassera/romain/OpenMOLESharedDirectoryTest/Bin/IRTK/ireg" "/tmp/d58368a5-b299-4c12-a773-141777b2d7db/.tmp/132798b0-a4ef-4dd4-8347-f3d9e75489cd/categoryce525f5f-02ca-4d36-b1e1-
3ebafa8f5c53/mni305.nii.gz" "/tmp/d58368a5-b299-4c12-a773-141777b2d7db/.tmp/132798b0-a4ef-4dd4-8347-f3d9e75489cd/categoryce525f5f-02ca-4d36-b1e1-3ebafa8f5c53/1000_3.nii.gz" "-threads" "1
" "-dofout" "/tmp/d58368a5-b299-4c12-a773-141777b2d7db/.tmp/132798b0-a4ef-4dd4-8347-f3d9e75489cd/categoryce525f5f-02ca-4d36-b1e1-3ebafa8f5c53/result.dof.gz" "-par" "Transformation model 
= Rigid" "-par" "Background value = 0"

ireg 3.2 (rev 96681ba7, built on Apr 20 2015)

Resolution level 4

          Energy            Image dissimilarity
   1      1.00000     =  1.00000 (     1.04904    )
   2      0.94387     =  0.94387 (     1.10241    )

Resolution level 3

          Energy            Image dissimilarity
   1      1.00000     =  1.00000 (     1.07410    )
   2      0.98426     =  0.98426 (     1.08867    )
   3      0.97692     =  0.97692 (     1.09547    )
   4      0.97080     =  0.97080 (     1.10114    )
   5      0.96283     =  0.96283 (     1.10852    )
   6      0.96258     =  0.96258 (     1.10874    )
   7      0.96236     =  0.96236 (     1.10895    )
   8      0.96221     =  0.96221 (     1.10908    )
   9      0.96103     =  0.96103 (     1.11018    )
  10      0.96052     =  0.96052 (     1.11065    )

Resolution level 2

          Energy            Image dissimilarity
   1      1.00000     =  1.00000 (     1.09980    )
   2      0.99995     =  0.99995 (     1.09985    )
...
```

At some point in the log you have the runtime installation script, could you try to run it locally so you can have a look at the exception? *you should run it in an empty directory since it contains an aggressive rm -rf*

**Comment by schuhschuh** [comment]
When I run the installation script, the runtime directory contains all the required files.

**Comment by schuhschuh** [comment]
For a split second I saw the following files, had no chance to see the content:
```
as12312@predict5:/homes/as12312/Data/Registrations/Workspace/.openmole/install/b6a903dd-ee14-4059-8d2e-093bd51876c4_install
> ls
runtimedfd2c543-7458-4ec7-ab86-fb3c7eed14aa  5e326991-25e5-4f2c-9e8a-4e085822587e.err  5e326991-25e5-4f2c-9e8a-4e085822587e.out  install_4b96c500-dff7-4da5-a852-85470ba4a643.sh

as12312@predict5:/homes/as12312/Data/Registrations/Workspace/.openmole/install/b6a903dd-ee14-4059-8d2e-093bd51876c4_install
> ll
total 3.0K
drwxr-xr-x 6 as12312 vip 7 May  7 13:52 runtime9c8e0a6f984f597e4afc7e1cdeb3272f992a1b09
```

Notice the .err and .out file.

**Comment by schuhschuh** [comment]
And actually the runtime was now installed correctly. What I've done, I just killed the observer again on both merapi and predict5 this time and removed the db directories for both hosts.

**Comment by schuhschuh** [comment]
Seems it really was just a caching problem resulting from deleting the sharedDirectory manually. Because after I removed it again, it wasn't working. Then I killed the dbserver (as before actually) and removed the db directory and it worked again. No idea why this didn't help before right away when you pointed it out.

Would it maybe reasonable to check at least if basic directories in the custom sharedDirectory still exist to avoid such user mistakes ?

**Comment by romainreuillon** [comment]
I think the main pb is that the runtime installation fails silently, I'll try to correct that.

**Comment by romainreuillon** [comment]
There was a bug in the generation of the install script, I just fixed it.

**Comment by schuhschuh** [comment]
Thanks, was wondering already. So was OpenMOLE supposed to report the failure to run the install script? Or has such change not been made yet? Because as far as I could tell it just went on to submit 3 jobs to Condor (which I noticed b/c they were in the queue for some time). I wasn't made aware of a problem during the installation. Not that I noticed at least...

**Comment by romainreuillon** [comment]
I modified the script so it should return a non zero return code in case of failure of the runtime installation. Therefore it should throw an exception when it doesn't complete successfully and lead to a systematic error before job submission in case the runtime cannot be installed.

**Comment by schuhschuh** [comment]
Maybe I just missed the output of the exception. Would it not make sense to abort the execution all together ? At least in batch mode. This probably doesn't play well with the console mode :(. But what could be possible is to throw an exception each time a job would be submitted with a message stating that the runtime needs to be installed successfully first ?

**Comment by schuhschuh** [comment]
But just some thought, not something that's important to me at this point as I now can recognise this problem by its symptoms.

**Comment by romainreuillon** [comment]
That's what it is supposed to do now but I may be there is a bug... I wrapped the exception so it is clearer that the runtime installation failed.

**Comment by jopasserat** [comment]
@romainreuillon could you please mention the commit that solves that in the discussion and eventually cherry-pick it to 4-dev? I've had the problem on the stable 4.0 yesterday.

**Comment by romainreuillon** [comment]
I should have done that when mentioning it but now it is a bit late now. We are working full time on OpenMOLE 5 right now. The RC might be for the end of next week, so I won't have/take time to work on a back port to the version 4.
