### ISSUE TITLE
bug in the table display of CSV file containing non numeric values

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#482]
Dear beloved OpenMOLE developers,

I'm running version 12 snapshot. 

I  have the following CSV file 
```
evolution$generation,houseArea,workSituation,subscriptionBase,hotWaterElec,isMale,ageGroup,totalDiff,diff,evolution$samples
1000,1,1,false,true,true,2,23.0,1810.630553149924,1
1000,2,2,false,true,false,2,289.0,1151.9769962981031,5
1000,3,2,false,true,true,2,126.0,1411.3312864101044,1
1000,3,0,false,true,true,4,169.0,1730.2970843181815,5
1000,2,2,false,true,false,1,184.0,1586.278979246715,5
1000,0,2,false,true,true,2,214.0,1538.152803861434,2
```
When I try to display it, its giving me a weird display as shown in the attached screenshot; it seems like it does not displays non numeric values. 

![capture](https://user-images.githubusercontent.com/2084275/92122279-890b1300-edfb-11ea-886d-7fd7780c989c.png)

No urge of any kiny ;-)

Sam

**Comment by mathieuleclaire** [comment]
Hi Sam,
The booleans are not taken into account in my regex. I fix this.

Mathieu

**Comment by mathieuleclaire** [comment]
66a51f80584899fef797069b1fad9aa841245eb1 fixes it
