### ISSUE TITLE
[Enh] Run OpenMOLE without password

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#485]
I am trying to run OpenMOLE on a cloud computation environment in which you need to upload tgz docker images and you cannot set the `docker run` options when you run the model (everything is done through a GUI) - so I built a docker image from the openmole one with:
```
FROM openmole/openmole:latest
COPY Script.oms /Script.oms
CMD ["openmole", "--script","/Script.oms"]
```
But the issue is then the password that you cannot set nor enter if you are not in interactive mode (and the docker host dynamically change each time if you do not specify it, so setting it manuallly and committing does not work).
One solution is to run this image with `--hostname myhost` and the command `sh`, run OpenMOLE inside in console mode to set manually the password, then commit the container changes to a new image (resetting the command also CMD ["openmole", "--script","/Script.oms","--password","password"]) - running the new image with the correct hostname will work. But I cannot use the hostname option on the cloud platform. I tried to add some manual modifications of /etc/hosts and /bin/hostname in the command just before openmole but it did not work.

Is there a way to just skip password prompt (or set a default value without asking) ?

**Comment by JusteRaimbault** [comment]
I found a dirty workaround by providing two similar lines of stdin to the openmole command in the docker - closing the issue as the suggestion of running without password is not a good idea.

**Comment by romainreuillon** [comment]
Hi Juste,

I think the way out of there is to fix the workspace location manually, so it doesn't contain the host name: [--workspace directory] run openmole with an alternative workspace location

cheers,
Romain

**Comment by JusteRaimbault** [comment]
Thanks for this! I don't know I completely overlooked this option - this makes my issue even more irrelevant!
