### ISSUE TITLE
compilation 12-dev: error not found: type ProcessHandle

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#486]
Dear beloved OpenMOLE developers,

I'm trying to compile OpenMOLE in order to produce the org-openmole-core-dsl package, so I can develop my own plugin which requires it as a dependancy. 

On the course of simulation on the 12-dev branch (same on master btw) I have the following compilation errors:
```
[error] /data/sam/workspaces/workspace-openmole/openmole/openmole/core/org.openmole.core.tools/src/main/scala/org/openmole/core/tools/service/ProcessUtil.scala:39:23: not found: type ProcessHandle
[error]           def kill(p: ProcessHandle) = p.destroyForcibly()
[error]                       ^
[error] /data/sam/workspaces/workspace-openmole/openmole/openmole/core/org.openmole.core.tools/src/main/scala/org/openmole/core/tools/service/ProcessUtil.scala:40:19: value descendants is not a member of Process
[error]           process.descendants().forEach(kill)
[error]                   ^
[error] /data/sam/workspaces/workspace-openmole/openmole/openmole/core/org.openmole.core.tools/src/main/scala/org/openmole/core/tools/service/ProcessUtil.scala:40:41: missing argument list for method kill
[error] Unapplied methods are only converted to functions when a function type is expected.
[error] You can make this conversion explicit by writing `kill _` or `kill(_)` instead of `kill`.
[error]           process.descendants().forEach(kill)
[error]                                         ^
[error] /data/sam/workspaces/workspace-openmole/openmole/openmole/core/org.openmole.core.tools/src/main/scala/org/openmole/core/tools/service/ProcessUtil.scala:41:24: value toHandle is not a member of Process
[error]           kill(process.toHandle)
[error]                        ^
```

It sounds a lot like the usage of a class which was only added in java 9: https://docs.oracle.com/javase/9/docs/api/java/lang/ProcessHandle.html

Should I compile against java 9 instead of 8? So should I change the target java version in build.sbt? 

Thanks a lot! 

Sam

**Comment by romainreuillon** [comment]
Dear Sam,

you got it right, jdk 9 is required. Indeed, changing the version of the target JVM bytecode could be more coherent (if this is a specific target for scalac).

In the docker OpenMOLE runs on jdk 11, on my laptop I develop it over java 13.

cheers,
Romain

**Comment by samthiriot** [comment]
Perfect, thanks @romainreuillon  !
I propose a micro pull request to update the version in build.sbt so fetching the code can immediatly lead to compilation. 
It's up to you to see if we should target 9 or 11. 
Merci :-)
Sam

**Comment by romainreuillon** [comment]
I think that 9 would work, but in practice we use 11 :-)
