### ISSUE TITLE
file ConfigurationLocationRegistry in org.openmole.core.preference not yet commited/pushed

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#488]
Dear beloved OpenMOLE developers,

when compiling a code on current 12-dev, I get the following compilation error:
```object ConfigurationLocationRegistry is not a member of package org.openmole.core.preference```

It is true this file does not exist: https://github.com/openmole/openmole/tree/12-dev/openmole/core/org.openmole.core.preference/src/main/scala/org/openmole/core/preference

Yet it should according to commit 73651093d0c988909c29c8f4bbdf4e53442554ab 

Maybe it was just not yet commited / push to the repo? 

Sam

**Comment by samthiriot** [comment]
mmm sounds like it was removed later. My bad, sorry

**Comment by romainreuillon** [comment]
Dear Sam,

FYI: OpenMOLE is compiled from scratch on each commit by a CI here: https://gitlab.openmole.org/openmole/openmole, it checks whether the compilation is ok,

cheers,
Romain
