### ISSUE TITLE
Error in job refresh

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#49]
Using the CondorEnvironment, I see plenty of the following error messages in the FINE log output before the actual job submission. The jobs are submitted properly and run fine. To not pollute the log output, would it be possible to handle these errors properly or avoid whatever causes them ?

```
May 07, 2015 8:33:08 PM org.openmole.plugin.environment.ssh.SharedStorage$$anonfun$5 apply
FINE: Script: export PATH=/vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/install/b6a903dd-ee14-4059-8d2e-093bd51876c4_install/runtime9c8e0a6f984f597e4afc7e1cdeb32
72f992a1b09/jre/bin/:$PATH; cd /vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/install/b6a903dd-ee14-4059-8d2e-093bd51876c4_install/runtime9c8e0a6f984f597e4afc7e1c
deb3272f992a1b09; mkdir -p /vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412b-b895-180cb3b01
3fd/01abf529-2bf7-4eb0-ad0f-5acdc87f7d5d; export OPENMOLE_HOME=/vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/14310271735
01/416e7c0e-99f1-412b-b895-180cb3b013fd/9775e035-e3ed-4df7-afd1-e0734e8314ed ; mkdir -p $OPENMOLE_HOME ; sh run.sh 256m /vol/medic01/users/as12312/Data/Registrations/Workspace/.open
mole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412b-b895-180cb3b013fd/01abf529-2bf7-4eb0-ad0f-5acdc87f7d5d -s /vol/medic01/users/as12312/Data/Registration
s/Workspace/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/persistent/1431027179399_ae559ad3-a084-4502-b32d-d73874a444d8.rep -c /vol/medic01/users/as12312/Data/Registrations/Workspa
ce/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412b-b895-180cb3b013fd -p envplugins/ -i /vol/medic01/users/as12312/Data/Registrations/Workspace/.o
penmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412b-b895-180cb3b013fd/job_2f94c5ba-542d-4001-b3d6-2e4f12683b26.in -o /vol/medic01/users/as12312/Data/Re
gistrations/Workspace/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412b-b895-180cb3b013fd/result_90c19f29-df39-4232-a474-f017acd3d68c.bin -t 1; RET
URNCODE=$?; rm -rf $OPENMOLE_HOME ; rm -rf /vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412
b-b895-180cb3b013fd/01abf529-2bf7-4eb0-ad0f-5acdc87f7d5d ; exit $RETURNCODE;
20:33:08.730 [Thread-135] ERROR net.schmizz.concurrent.Promise - <<chan#1738 / open>> woke to: Opening `session` channel failed: open failed
May 07, 2015 8:33:08 PM org.openmole.core.batch.refresh.JobManager $bang
FINE: Error in job refresh
Opening `session` channel failed: open failed
        at net.schmizz.sshj.connection.channel.direct.AbstractDirectChannel.gotOpenFailure(AbstractDirectChannel.java:64)
        at net.schmizz.sshj.connection.channel.direct.AbstractDirectChannel.gotUnknown(AbstractDirectChannel.java:89)
        at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:193)
        at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:128)
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:455)
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:107)
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:175)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:61)
```

**Comment by jopasserat** [comment]
Thanks for reporting we're aware of this error.

There's nothing harmful in there, just the ssh lib we're using being very talkative whenever an ssh connection fails (OpenMOLE handles these problems).

I'll try to make it more silent though :)

On 7 May 2015 21:36:25 CEST, Andreas Schuh <notifications@github.com> wrote:
>Using the CondorEnvironment, I see plenty of the following error
>messages in the FINE log output before the actual job submission. The
>jobs are submitted properly and run fine. To not pollute the log
>output, would it be possible to handle these errors properly or avoid
>whatever causes them ?
>
>```
>May 07, 2015 8:33:08 PM
>org.openmole.plugin.environment.ssh.SharedStorage$$anonfun$5 apply
>FINE: Script: export
>PATH=/vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/install/b6a903dd-ee14-4059-8d2e-093bd51876c4_install/runtime9c8e0a6f984f597e4afc7e1cdeb32
>72f992a1b09/jre/bin/:$PATH; cd
>/vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/install/b6a903dd-ee14-4059-8d2e-093bd51876c4_install/runtime9c8e0a6f984f597e4afc7e1c
>deb3272f992a1b09; mkdir -p
>/vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412b-b895-180cb3b01
>3fd/01abf529-2bf7-4eb0-ad0f-5acdc87f7d5d; export
>OPENMOLE_HOME=/vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/14310271735
>01/416e7c0e-99f1-412b-b895-180cb3b013fd/9775e035-e3ed-4df7-afd1-e0734e8314ed
>; mkdir -p $OPENMOLE_HOME ; sh run.sh 256m
>/vol/medic01/users/as12312/Data/Registrations/Workspace/.open
>mole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412b-b895-180cb3b013fd/01abf529-2bf7-4eb0-ad0f-5acdc87f7d5d
>-s /vol/medic01/users/as12312/Data/Registration
>s/Workspace/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/persistent/1431027179399_ae559ad3-a084-4502-b32d-d73874a444d8.rep
>-c /vol/medic01/users/as12312/Data/Registrations/Workspa
>ce/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412b-b895-180cb3b013fd
>-p envplugins/ -i
>/vol/medic01/users/as12312/Data/Registrations/Workspace/.o
>penmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412b-b895-180cb3b013fd/job_2f94c5ba-542d-4001-b3d6-2e4f12683b26.in
>-o /vol/medic01/users/as12312/Data/Re
>gistrations/Workspace/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412b-b895-180cb3b013fd/result_90c19f29-df39-4232-a474-f017acd3d68c.bin
>-t 1; RET
>URNCODE=$?; rm -rf $OPENMOLE_HOME ; rm -rf
>/vol/medic01/users/as12312/Data/Registrations/Workspace/.openmole/b6a903dd-ee14-4059-8d2e-093bd51876c4/tmp/1431027173501/416e7c0e-99f1-412
>b-b895-180cb3b013fd/01abf529-2bf7-4eb0-ad0f-5acdc87f7d5d ; exit
>$RETURNCODE;
>20:33:08.730 [Thread-135] ERROR net.schmizz.concurrent.Promise -
><<chan#1738 / open>> woke to: Opening `session` channel failed: open
>failed
>May 07, 2015 8:33:08 PM org.openmole.core.batch.refresh.JobManager
>$bang
>FINE: Error in job refresh
>Opening `session` channel failed: open failed
>at
>net.schmizz.sshj.connection.channel.direct.AbstractDirectChannel.gotOpenFailure(AbstractDirectChannel.java:64)
>at
>net.schmizz.sshj.connection.channel.direct.AbstractDirectChannel.gotUnknown(AbstractDirectChannel.java:89)
>at
>net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:193)
>at
>net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:128)
>at
>net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:455)
>        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:107)
>       at net.schmizz.sshj.transport.Decoder.received(Decoder.java:175)
>        at net.schmizz.sshj.transport.Reader.run(Reader.java:61)
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openmole/openmole/issues/49

--
Jonathan Passerat-Palmbach, PhD
Research Associate
Department of Computing
Imperial College London

South Kensigton Campus
Huxley Building - room 344
180 Queen's Gate
London SW7 2AZ

**Comment by schuhschuh** [comment]
Definitely would be good if it could be silenced. Most of the output I see in OpenMOLE is the following. The timestamps show that I get several of these per second with tens of thousands of jobs in the queue... I doesn't really matter if these are harmless, the problem is that they on one hand suggest a problem and on the other in particular make it really difficult to find the actual job output or error messages which are relevant.
```
08:35:47.149 [Thread-133] ERROR net.schmizz.concurrent.Promise - <<chan#3842091 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.152 [Thread-139] ERROR net.schmizz.concurrent.Promise - <<chan#3842092 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.156 [Thread-123] ERROR net.schmizz.concurrent.Promise - <<chan#3842093 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.159 [Thread-160] ERROR net.schmizz.concurrent.Promise - <<chan#3842094 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.162 [Thread-154] ERROR net.schmizz.concurrent.Promise - <<chan#3842095 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.166 [Thread-126] ERROR net.schmizz.concurrent.Promise - <<chan#3842096 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.169 [Thread-103] ERROR net.schmizz.concurrent.Promise - <<chan#3842097 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.172 [Thread-152] ERROR net.schmizz.concurrent.Promise - <<chan#3842098 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.176 [Thread-204] ERROR net.schmizz.concurrent.Promise - <<chan#3842099 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.179 [Thread-18] ERROR net.schmizz.concurrent.Promise - <<chan#3842100 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.182 [Thread-120] ERROR net.schmizz.concurrent.Promise - <<chan#3842101 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.185 [Thread-202] ERROR net.schmizz.concurrent.Promise - <<chan#3842102 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.188 [Thread-138] ERROR net.schmizz.concurrent.Promise - <<chan#3842103 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.192 [Thread-176] ERROR net.schmizz.concurrent.Promise - <<chan#3842104 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.195 [Thread-84] ERROR net.schmizz.concurrent.Promise - <<chan#3842105 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.198 [Thread-53] ERROR net.schmizz.concurrent.Promise - <<chan#3842106 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.201 [Thread-164] ERROR net.schmizz.concurrent.Promise - <<chan#3842107 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.204 [Thread-95] ERROR net.schmizz.concurrent.Promise - <<chan#3842108 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.207 [Thread-131] ERROR net.schmizz.concurrent.Promise - <<chan#3842109 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.211 [Thread-44] ERROR net.schmizz.concurrent.Promise - <<chan#3842110 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.214 [Thread-68] ERROR net.schmizz.concurrent.Promise - <<chan#3842111 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.217 [Thread-89] ERROR net.schmizz.concurrent.Promise - <<chan#3842112 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.221 [Thread-191] ERROR net.schmizz.concurrent.Promise - <<chan#3842113 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.224 [Thread-150] ERROR net.schmizz.concurrent.Promise - <<chan#3842114 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.227 [Thread-113] ERROR net.schmizz.concurrent.Promise - <<chan#3842115 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.265 [Thread-48] ERROR net.schmizz.concurrent.Promise - <<chan#3842126 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.366 [Thread-166] ERROR net.schmizz.concurrent.Promise - <<chan#3842130 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.617 [Thread-60] ERROR net.schmizz.concurrent.Promise - <<chan#3842136 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.823 [Thread-29] ERROR net.schmizz.concurrent.Promise - <<chan#3842138 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.881 [Thread-96] ERROR net.schmizz.concurrent.Promise - <<chan#3842139 / open>> woke to: Opening `session` channel failed: open failed
08:35:47.913 [Thread-24] ERROR net.schmizz.concurrent.Promise - <<chan#3842140 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.010 [Thread-173] ERROR net.schmizz.concurrent.Promise - <<chan#3842141 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.012 [Thread-23] ERROR net.schmizz.concurrent.Promise - <<chan#3842142 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.015 [Thread-87] ERROR net.schmizz.concurrent.Promise - <<chan#3842143 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.140 [Thread-142] ERROR net.schmizz.concurrent.Promise - <<chan#3842144 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.143 [Thread-75] ERROR net.schmizz.concurrent.Promise - <<chan#3842145 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.146 [Thread-50] ERROR net.schmizz.concurrent.Promise - <<chan#3842146 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.271 [Thread-163] ERROR net.schmizz.concurrent.Promise - <<chan#3842147 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.305 [Thread-34] ERROR net.schmizz.concurrent.Promise - <<chan#3842148 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.356 [Thread-170] ERROR net.schmizz.concurrent.Promise - <<chan#3842149 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.359 [Thread-33] ERROR net.schmizz.concurrent.Promise - <<chan#3842150 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.370 [Thread-94] ERROR net.schmizz.concurrent.Promise - <<chan#3842151 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.372 [Thread-114] ERROR net.schmizz.concurrent.Promise - <<chan#3842152 / open>> woke to: Opening `session` channel failed: open failed
08:35:48.372 [Thread-80] ERROR net.schmizz.concurrent.Promise - <<chan#3842153 / open>> woke to: Opening `session` channel failed: open failed
```

**Comment by romainreuillon** [comment]
I don't know exactly how to silent that logger. If you find a way I'll be happy to merge it!

Alternatively you could try to submit a ticket to get the level brought down in the lib, that we are using: 
https://github.com/shikhar/sshj/blob/master/src/main/java/net/schmizz/concurrent/Promise.java

**Comment by schuhschuh** [comment]
Do you use the slf4j logging interface yourself anywhere ? Because one simple way to get rid of the log output of that library could be to use ```slf4j-nop``` as SBT dependency. In this case the logger implementation should be a ```NOPLogger```, i.e., one which ignores all logging calls.

If that is not feasible or if some other dependency of OpenMOLE uses slf4j, it is possible to set the log level of each individual logger (name of the logger we want to silence is ```net.schmizz.concurrent.Promise```) using a system property. However, it seems the log level must be at least ```ERROR``` which isn't quite helpful in this case... but if we choose a particular logger implementation which does support an ```OFF``` log level (e.g., log4j), we should be able to set it to this.

**Comment by schuhschuh** [comment]
Or better, I found a configuration/logback.xml file in the OpenMOLE source tree. So using the slf4j-logback implementation and adding an entry to this configuration file for the above named logger might do the trick.

**Comment by schuhschuh** [comment]
It seems that's already the case, isn't it ? I found the following in libraries/project/src/main/OSGi.scala:
```scala
  lazy val logback = OsgiProject("ch.qos.logback", exports = Seq("ch.qos.logback.*", "org.slf4j.impl")) settings
    (libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.0.9", version := "1.0.9")

  lazy val slf4j = OsgiProject("org.slf4j") settings(
    libraryDependencies += "org.slf4j" % "slf4j-api" % "1.7.10",
    version := "1.7.10"
    )
```

**Comment by schuhschuh** [comment]
It seems the logback.xml configuration file is not actually used by the OpenMOLE console? Because when I add [debug="true"](http://logback.qos.ch/manual/configuration.html#automaticStatusPrinting) to the root element, it prints nothing. After I add
```
-Dlogback.configurationFile=/path/to/openmole/bin/openmole/src/main/resources/configuration/logback.xml
```
 to the java command in the ```openmole``` shell script, the configuration is loaded and the debug information printed upon startup of the console:

```
> openmole -c
15:01:55,090 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [/homes/as12312/Code/OpenMOLE/openmole/bin/openmole/src/main/resources/configuration/logback.xml] at [file:/homes/as12312/Code/OpenMOLE/openmole/bin/openmole/src/main/resources/configuration/logback.xml]
15:01:55,195 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:01:55,197 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:01:55,221 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:01:55,241 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.openmole.web] to DEBUG
15:01:55,241 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.mchange.v2.c3p0] to ALL
15:01:55,241 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.schmizz.concurrent.Promise] to OFF
15:01:55,241 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
15:01:55,241 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
15:01:55,242 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:01:55,242 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@42593848 - Registering current configuration as safe fallback point
```
where I added
```
<logger name="net.schmizz.concurrent.Promise" level="OFF" />
```

Right now I cannot test if that disabled the log output of this library due to Condor issues on our end...

**Comment by schuhschuh** [comment]
Another possibility might be the following code:
```scala
val logger = org.slf4j.LoggerFactory.getLogger("net.schmizz.concurrent.Promise").asInstanceOf[ch.qos.logback.classic.Logger]
logger.setLevel(org.slf4j.Level.OFF)
```

**Comment by jopasserat** [comment]
That's probably a better option in case users want to play with it, they 
don't have to edit XML and we can wrap it in something.

On 12/05/15 15:15, Andreas Schuh wrote:
>
> Another possibility might be the following code:
>
> val  logger  =  org.slf4j.LoggerFactory.getLogger("net.schmizz.concurrent.Promise").asInstanceOf[ch.qos.logback.classic.Logger]
> logger.setLevel(org.slf4j.Level.OFF)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openmole/openmole/issues/49#issuecomment-101297168>.
>

-- 
Jonathan Passerat-Palmbach, PhD
Research Associate
Department of Computing
Imperial College London

South Kensington Campus
Huxley Building - room 344
180 Queen's Gate
London SW7 2AZ

**Comment by schuhschuh** [comment]
If both would work, I'd set the default level to OFF in the configuration file (which at the moment seems unused, however). If you wanted to turn on the logger again, you can do so using above code snippet. Thing is that I don't think this error message is of any use to the user. Only OpenMOLE developers might care about it to see which exceptions they have to deal with.

**Comment by schuhschuh** [comment]
(resp. all exceptions can be caught by the code using net.schmizz.concurrent.Promise and logged via the OpenMOLE logger as FINE message or so. Because this logger's level is easily changed by setting ```logger.level("FINE")``` in the console)

**Comment by jopasserat** [comment]
That's what we'd like to achieve.
I think you've put us on the right track. I'll dig in the documentation but I'm quite confident we can sort it out.

**Comment by schuhschuh** [comment]
I tried it with the logback.xml setting and it seemed to work.

**Comment by schuhschuh** [comment]
I can now also confirm that adding the following code to my OpenMOLE script suppresses the output of the net.schmizz.concurrent.Promise.log logger:
```scala
val promiseLogger = org.slf4j.LoggerFactory.getLogger("net.schmizz.concurrent.Promise").asInstanceOf[ch.qos.logback.classic.Logger]
promiseLogger.setLevel(ch.qos.logback.classic.Level.OFF)
```

**Comment by jopasserat** [comment]
I'm close to have something working to capture the log and relog it back with OpenMOLE's logger.

**Comment by jopasserat** [comment]
Just created #54 that should solve the problem.
Have a look at it before we merge into the main branch as the code is quite ugly (lots of mutable since I copy-pasted the base example in Java).

**Comment by jopasserat** [comment]
@schuhschuh Please note that this only fixes this kind of messages:

   `08:35:47.149 [Thread-133] ERROR net.schmizz.concurrent.Promise - <<chan#3842091 / open>> woke to: Opening `session` channel failed: open failed`

The message your report in your first post is different since it's caught from a proper exception. I assume it's due to the number of SSH connections in your preferences which is higher that what the remote server accepts from the same user.

This is handled by OpenMOLE that will print the error in FINE but will try to submit the job again.

**Comment by schuhschuh** [comment]
Right, that's fine. Those messages that were not controlled by the OpenMOLE log level were more of an issue. Thanks!

**Comment by schuhschuh** [comment]
I guess the resolution of this error, i.e., reducing the ```SSHEnvironment.MaxConnections``` preference should be documented in some kind of FAQ for common errors encountered...

**Comment by jopasserat** [comment]
The FAQ will appear with the next release ;)
https://github.com/openmole/openmole/blob/master/openmole/bin/org.openmole.site/src/main/scalatex/org.openmole.site/documentation/FAQ.scalatex

We'll add a whole section about SSH troubleshooting.
