### ISSUE TITLE
web interface: display of table skips columns on scientific notation

### ISSUE THREAD

**Issue by samthiriot** [openmole/openmole#490]
Dear beloved developers of the OpenMOLE web UI,

When using the "table" display of a CSV file with version 12-snapshot, we observe a strange behavior when the csv file contains scientific notation.

For a CSV file such as:
```
Time,T_ext,Tsol3m,Gain_kWh
1.296e+07,13.7,12.335111,0
1.29636e+07,13.4,12.335111,0.0009080809
1.29672e+07,12.999999,12.335108,0.0015379229
1.29708e+07,12.599999,12.335099,0.0019181772
1.29744e+07,12.199999,12.335073,0.0020590648
1.2978e+07,11.800001,12.3349695,0.002344617
1.29816e+07,12.000004,12.334821,0.0025812907
1.29852e+07,12.700002,12.334606,0.0029193514
1.29888e+07,13.000005,12.334242,0.0039750272
1.29924e+07,13.800008,12.3337755,0.005404025
1.2996e+07,14.900007,12.333199,0.0072679166
1.29996e+07,15.800004,12.3324995,0.009697775
1.30032e+07,16.300001,12.331685,0.012612174
1.30068e+07,16.4,12.330833,0.015784262
```

The displayed result is 
![bug_table_scientific_notation](https://user-images.githubusercontent.com/2084275/94536253-d637a480-0242-11eb-8d3b-ea8d8abd3e39.jpg)

It seems like "e" leads to the break with a subcolumn.

Thanks!

Sam

**Comment by mathieuleclaire** [comment]
Dear Sam,
this bug has been fixed a month ago. I am surprised you still have it. And I just tested on my machine (see the version in the bottom right hand side), it works fine with your data. Did you pull recently ?

![image](https://user-images.githubusercontent.com/800035/94542776-7e506c00-0249-11eb-81f3-ba3f6929e95a.png)

**Comment by romainreuillon** [comment]
It might be caused by the docker image on docker hub being outdated. I'll update it this afternoon.

Cheers,
Romain

**Comment by samthiriot** [comment]
Thanks Romain & Mathieu,
Indeed I'm using the docker image, so maybe I did not got this update, sorry :-/
Sam
