### ISSUE TITLE
Missing redirection on website

### ISSUE THREAD

**Issue by NicolasCARPi** [openmole/openmole#495]
You might want to redirect www.openmole.org to openmole.org. Currently the www one doesn't load anything.

**Comment by romainreuillon** [comment]
I just did it. Thanks for the report!

**Comment by NicolasCARPi** [comment]
You only did the http redirection, not https ;)

**Comment by romainreuillon** [comment]
I can't find this link? Where is it? In the README.md?

**Comment by NicolasCARPi** [comment]
I'm talking about the server. You have HSTS header. So if I visit openmole.org, the browser remembers to visit the https version. But if I type www.openmole.org, and hit the https page, nothing is shown.

`curl -I https://www.openmole.org`
