### ISSUE TITLE
Option MaxPermSize=128M support was removed in 8.0

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#5]
When running the ```openmole``` shell script with JDK 8, the following warning is printed:
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
```
Would be preferable if the ```MaxPermSize``` option was not added to the ```java``` command if the JKD >= 8 is used rather than version 7.

**Comment by romainreuillon** [comment]
It has been fixed in the dev version.

**Comment by jopasserat** [comment]
Problem is Java 8 dropped the management of the Permanent Generation in favour of the native memory.  

Passing the option is harmless to Java 8 but we can't remove it because out user base is still using older versions of Java.

**Comment by romainreuillon** [comment]
It has been fixed already :)
