### ISSUE TITLE
Report also name of remote host

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#50]
On our Condor cluster my jobs fail due to missing shared libraries on some of the nodes. In order to be able to identify differences between nodes on which the execution succeeds compared to those where it fails it would be useful to know the names of the hosts. I could probably figure this out using some Condor commands and go through the history of jobs, but I thought it would also be sensible if OpenMOLE would report the name of the host along the job output, e.g.,

```
-------------------------Output on remote host grasmoor.doc.ic.ac.uk-----------------------
[...]
-------------------------Error output on remote host grasmoor.doc.ic.ac.uk-----------------
```

**Comment by schuhschuh** [comment]
I'd have a PR for this ready...

**Comment by romainreuillon** [comment]
:) I am working it....

**Comment by romainreuillon** [comment]
Sorry, I should have told.

**Comment by schuhschuh** [comment]
No problem. Besides this, I also slightly changed the GetResultActor display function to print equally length markers:

```scala
System.out.synchronized {
              val hostName = java.net.InetAddress.getLocalHost.getHostName
              val header = ("-" * 10) + description + " on remote host " + hostName + ("-" * 10)
              System.out.println(header)
              val fis = new FileInputStream(tmpFile)
              try fis.copy(System.out) finally fis.close()
              System.out.println("-" * header.length)
            }
```

**Comment by romainreuillon** [comment]
Neat, I didn't know this string multiplication operation!

I just pushed the feature. This display operation happens of the submission machine and the host name should be gathered from the execution machine. So it should pass through the messaging system between the submission machine and the execution ones. 

I created a generic HostInfo container so we can gather many more info about the execution machines.

**Comment by schuhschuh** [comment]
> Neat, I didn't know this string multiplication operation!

;) Google + Rosetta told me

> I created a generic HostInfo container so we can gather many more info about the execution machines.

I knew you'd come up with a better / more generic solution. Not just a quick hack like mine. Thanks!

**Comment by schuhschuh** [comment]
Output looks good.
