### ISSUE TITLE
[GAMATask] Missing memory option

### ISSUE THREAD

**Issue by RoiArthurB** [openmole/openmole#511]
As explained in the title, it's not possible to change the GAMA's JVM memory (available with the `-m` command in headless mode) in the GAMATask.

In my context, it makes me using a Slurm environment with 20Go of RAM available, but only 4Go (headless default) are used...

**Comment by romainreuillon** [comment]
Hi @RoiArthurB, could you post an example of calling the headless with a memory setting?

**Comment by romainreuillon** [comment]
Solved: 397df4d6d388ffb0266447411b55c26638e98102

**Comment by romainreuillon** [comment]
You can use memoy = 20 gigabytes or memory = 3000 megabytes
