### ISSUE TITLE
[Plugin][Bug] Arrays in ScilabTask

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#523]
When using large arrays and matrices as outputs of the scilab task, the task fails or truncates the data - not that large actually:
 - a 1D array fails with size > 15
 - a 2D array fails with more than 15 columns
 - a 2D array with less than 15 columns but more than 99 rows will truncate the data to the first 99 rows

This has to deal with using the primitive `print` which displays arrays in diverse formats not necessarily machine readable (with more than 15 columns, it splits into several rows with additional info "columns 1 to 15" etc.).
We should use `fprintfMat` or `write` instead.

Minimal working example (change array dimensions):
```
val x = Val[Double]
val dArray = Val[Array[Double]]
//val dArray = Val[Array[Array[Double]]]

val scilab = ScilabTask("disp(size(dArray));dArray = dArray * x") set (
    inputs += x mapped "x",
    inputs += dArray mapped "dArray",
    outputs += dArray mapped "dArray",
    dArray := Array.fill(16)(1.0)//Array.fill(200, 2)(1.0)//Array(9.0, 8.0)
  )

val aggr = ScalaTask("println(input.dArray.size); //println(input.dArray.map(_.size))") set (inputs += (dArray))

val env = LocalEnvironment(2)

DirectSampling(
  evaluation = scilab -- aggr,
  sampling = x is 2.0//x in (0.0 to 10.0 by 0.2)
) on env

```

**Comment by JusteRaimbault** [comment]
`fprintfMat` is indeed the quick fix we need. Still won't be able to support hypermatrices as outputs - we should fix this one day

**Comment by JusteRaimbault** [comment]
Well only for numeric matrices and arrays, for strings and boolean we should use `write`

**Comment by romainreuillon** [comment]
I guess this is fixed in this commit : https://gitlab.openmole.org/openmole/openmole/-/commit/07b8a48860c434b86d9b2c76b961d01c70fa6bb5
