### ISSUE TITLE
[Doc] dead link for plugin development 

### ISSUE THREAD

**Issue by chapinux** [openmole/openmole#524]
The Plugin Development page refers to a dead repository : git clone git://github.com/openmole/myopenmoleplugin.git

Can't find the location of it for now @chapinux

**Comment by JusteRaimbault** [comment]
The repo still exists here: https://github.com/openmole/myopenmoleplugin
It may appear dead if you are using the git protocol without having write access to the repo?
I think it would be better to change the link in the doc with:
https://github.com/openmole/myopenmoleplugin.git

**Comment by JusteRaimbault** [comment]
[0406e2919e](https://github.com/openmole/openmole/commit/0406e2919ecdce04f81eaa55844c6161e44ae38d)
