### ISSUE TITLE
[GUI][Enh] Download plugins

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#537]
When selecting uploaded plugins in the GUI, it is not possible to download the jar. It can be useful in some cases - a workaround in a previous version was to get it through the url `../plugins/plugin.jar` but this does not seem to work anymore.
Could be useful to have this download option in the new gui.

**Comment by mathieuleclaire** [comment]
It will be possible in the coming version. A plugin will just be a file like any others.
