### ISSUE TITLE
[Plugin][Bug] ContainerTask: output encoding

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#554]
There seems to be an issue when retrieving container output (strange characters when installing python packages, messed up outputs in other cases) - this may be a problem with encoding? It seems to affect only the beginning of the output

**Comment by romainreuillon** [comment]
It is due to an ANSI console encoding that program use. 

https://en.wikipedia.org/wiki/ANSI_escape_code

I worked on it already, but I had no time yet coming up with a fully working version on ANSI esc char interpretation in the GUI.

**Comment by JusteRaimbault** [comment]
Do you mean that a specific scala reimplementation of this char interpretation is done for the GUI? :/
In some cases it's the error message which is messed up so it can be a problem

**Comment by romainreuillon** [comment]
SHould be solved by: 2b654243a86ee3f548e8ca780738e73ad4fa40bb
