### ISSUE TITLE
[GUI][Bug] Frozen container task at preparation can not be removed from executions list

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#555]
If a command of the `install` argument in a container freezes without failing (for example a `grep` waiting forever for an input), the execution will remain in the "preparing" state forever, and it can not be removed from the execution list

**Comment by romainreuillon** [comment]
This is fixed by 0f0d50751fb2bdd5e169794a1859c0505a51fd06

**Comment by JusteRaimbault** [comment]
Great, thanks !
