### ISSUE TITLE
[Plugin][Enh] ContainerTask: raise an error when a resource directory is used as output

### ISSUE THREAD

**Issue by JusteRaimbault** [openmole/openmole#557]
In this case, and for other tasks using containers, the output directory will be empty (because it is unmounted before getting the outputs - furthermore the mounted resources is shared across distributed copies of the task, so writing in it leads to concurrency issue) => this configuration should not occur, and output directories should always be different from resources => raise an error is such a configuration is detected at task validation.

**Comment by chapinux** [comment]
Documentation is urgent about that case, since a lot of models use their own subdirectory as resources to store data, intermediate results AND outputs as well , which is totally understandable from their pov.

**Comment by romainreuillon** [comment]
Looking at the code, this case should actually be working. The resource is copied if not specified otherwise and should be resloved correctly. However this is just a bug, fixing this bug should solve the issue.

**Comment by romainreuillon** [comment]
Should be fixed by: 
https://github.com/openmole/openmole/commit/670eb44cb670460d399e8d3ffdf2ccc449ec07cc

**Comment by JusteRaimbault** [comment]
:clap: :pray:
