### ISSUE TITLE
Task following "when" if-else task not being executed

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#6]
I am using the new "when" keyword of the OpenMOLE DSL (i.e., 5.0-SNAPSHOT) to run an ["if" task](https://github.com/schuhschuh/REPEAT/blob/fd69fe92791dbdcc3f6b80559d10c5ee7b697d36/src/mole/Normalize.scala#L36) when a certain condition is met and an empty ["else" task](https://github.com/schuhschuh/REPEAT/blob/fd69fe92791dbdcc3f6b80559d10c5ee7b697d36/src/mole/Normalize.scala#L48) otherwise. My workflow uses ScalaTask's with a [custom OpenMOLE plugin](https://github.com/schuhschuh/REPEAT) to [run external programs](https://github.com/schuhschuh/REPEAT/blob/fd69fe92791dbdcc3f6b80559d10c5ee7b697d36/src/main/scala/com/andreasschuh/repeat/IRTK.scala) from the [IRTK](https://github.com/biomedia/irtk). I think this structure works well for my application. The only remaining issue I have is that the task which follows either the "if" or the "else" task is never being executed and the workflow prematurely terminated instead. In my particular pipeline, I have a rigid image registration followed by an affine image registration. The [rigid registration mole](https://github.com/schuhschuh/REPEAT/blob/fd69fe92791dbdcc3f6b80559d10c5ee7b697d36/src/mole/Normalize.scala#L62) is performed upon first execution as intended, but the [affine registration mole](https://github.com/schuhschuh/REPEAT/blob/fd69fe92791dbdcc3f6b80559d10c5ee7b697d36/src/mole/Normalize.scala#L99) is never being executed (or anything that would follow).

Excerpt from my OpenMOLE script to illustrate the "if"-"else" pattern (rigid registration mole):
```scala
val rigidOutputFile = FileSource(dofDir + "/rigid/"  + refId + ",${srcId}" + dofSuf, dof6)

val rigidBegin = EmptyTask() set(
    inputs  += (srcId, srcIm),
    outputs += (srcId, srcIm, dof6)
  ) source rigidOutputFile

val rigidIf = ScalaTask(
  """IRTK.ireg(Settings.refIm, srcIm, None, dof6,
    |  "Transformation model" -> "Rigid",
    |  "Background value"     -> 0
    |)
  """.stripMargin) set(
    imports     += "com.andreasschuh.repeat._",
    usedClasses += (Settings.getClass(), IRTK.getClass()),
    inputs      += (srcId, srcIm, dof6),
    outputs     += (srcId, srcIm, dof6)
  )

val rigidElse = EmptyTask() set(
    inputs  += (srcId, srcIm, dof6),
    outputs += (srcId, srcIm, dof6)
  )

// THIS TASK IS NEVER BEING EXECUTED
val rigidEnd = ScalaTask(
  """val srcId = input.srcId.head
    |val srcIm = input.srcIm.head
    |val dof6  = input.dof6 .head
  """.stripMargin) set(
    inputs  += (srcId.toArray, srcIm.toArray, dof6.toArray),
    outputs += (srcId,         srcIm,         dof6)
  )

val rigidReg = rigidBegin -- (rigidIf on env when "!dof6.exists()", rigidElse when "dof6.exists()") -- rigidEnd
```

**Comment by schuhschuh** [comment]
P.S.: Either a further addition to the DSL to allow for a convenient if-else branching of the workflow or the addition of an example illustrating this if-else pattern to the [transition documentation](http://www.openmole.org/current/documentation_console_transition.html) would be great.

**Comment by romainreuillon** [comment]
A task is executed when all the transition reaching a slot have been crossed. In your case it never happens because of the conditions. Actually what you want to do can be express like that:

```
val ifpart = (rigidIf on env) -- rigidEnd
val rigidReg = rigidBegin -- (ifpart when "!dof6.exists()", rigidEnd when "dof6.exists()") 
```

In that configuration 2 slots are implicitelly created for the rigidEnd task (capsule actually but let skip the details). If you want more insight on this slot / capsule things it has been explained in the following paper: http://www.openmole.org/files/FGCS2013.pdf

You should also adapt the inputs of rigidEnd, it doesn't needs to take arrays as input anymore. Sorry I didn't thought of that when we discussed with Jo last Friday.

**Comment by schuhschuh** [comment]
So ```rigidEnd``` just needs to be an ```EmptyTask``` then and is only required to connect both the ```rigidBegin``` and ```rigidIf``` tasks to a common capsule ? I thought there must be a way to do all this with slots and capsules, but the Loop example in the documentation wasn't clear enough to me. I'll check out the article to learn more about these concepts in OpenMOLE.

**Comment by romainreuillon** [comment]
rigidEnd is you present ScalaTask, only the wiring changes. rigidElse is not needed anymore so I got rid of it. A better mole would actually be:

```
val rigidEndCaps = Capsule(rigidEnd)
val ifpart = (rigidIf on env) -- rigidEndCaps
val rigidReg = rigidBegin -- (ifpart when "!dof6.exists()", rigidEndCaps when "dof6.exists()") 
```
To be fully explicit this is exactly the same as:
```
val rigidEndCaps = Capsule(rigidEnd)
val rigidEndCapsS1 = Slot(rigidEndCaps)
val rigidEndCapsS2 = Slot(rigidEndCaps)
val ifpart = (rigidIf on env) -- rigidEndCapsS1
val rigidReg = rigidBegin -- (ifpart when "!dof6.exists()", rigidEndCapsS2 when "dof6.exists()") 
```

So you can chain the remaining of you workflow after rigidEndCaps. It would look like:
```
val mole = rigidReg + rigidEndCaps -- othercaps -- othercaps ....
```

**Comment by romainreuillon** [comment]
If you are interested in improving the doc, you are very welcome!

**Comment by schuhschuh** [comment]
Thanks! Actually, the meaning of the "+" transition is what I didn't quite get from the Loop example and it's not explained anywhere.

**Comment by schuhschuh** [comment]
I'm not quite able to realise this new pattern in my workflow. The error I get when chaining the rigid with the affine registration mole is:
```
org.openmole.core.exception.UserBadDataError: Formal validation of your mole has failed, several errors have been found: Wrong type received at Slot hash 73348416 of emptyTask5, data srcId: Int is expected but srcId: Array[int] is provided.
Wrong type received at Slot hash 73348416 of emptyTask5, data srcIm: java.io.File is expected but srcIm: Array[java.io.File with java.io.Serializable with java.lang.Comparable] is provided.
Wrong type received at Slot hash 73348416 of emptyTask5, data dof6: java.io.File is expected but dof6: Array[java.io.File with java.io.Serializable with java.lang.Comparable] is provided.
Input Data dof6: java.io.File with mode None is missing when reaching the Slot hash 1419982552 of emptyTask6.
DuplicatedTransition: from emptyTask3 to emptyTask5 has been found 2 times.
```
See [REPEAT commit 7b7de4a](https://github.com/schuhschuh/REPEAT/commit/7b7de4afab9af540d668bcffd9e6882215212459) for details on my attempted modifications.

I've tried a few other configurations with and without the "demux"ing, but I either get an error that an Array was expected but a single value is given or vice versa. Also, in either case I end up with a duplicated transition.

**Comment by schuhschuh** [comment]
Finally I have a working version. My mistake was not to realise that the ```--``` transitions between following tasks must precede the ```+``` composition, i.e., in your previous example there are parenthesis missing:
```
val mole = rigidReg + (rigidEndCaps -- othercaps -- othercaps ....)
```

I think that's a bit unfortunate because I have to refer to [```rigidEndCaps``` when constructing the ```affineReg``` mole](https://github.com/schuhschuh/REPEAT/commit/68d41c47090629eccb8e2747e4a1c6496951f466#diff-9602a79f1983cbec1101bee362379ecbR83) and cannot just add it at the end of the ```rigidReg``` mole, but at least it works.

**Comment by schuhschuh** [comment]
It's not actually that bad. Slightly rewritten, I now have
```scala
val mole = (forEachIm -- rigidReg) + (rigidEnd -- affineReg) start
```
where ```forEachIm``` starts with the exploration task and some intermediate helper task. The ```rigidEnd``` capsule after the ```+``` demonstrates that the ```affineReg``` sub-mole depends on the end of the rigidReg sub-mole. I think I can live with it. Would be great, however, if the DSL could be extended to make all this more intuitive.

**Comment by romainreuillon** [comment]
Great that you made it!

In your workflow you can select your input file directly in the sampling:
```
val explo =
  ExplorationTask (
    sampleId +
    (srcIm in SelectFileDomain(imgDir,  imgPre + "${srcId}" + imgSuf))
  )
```

**Comment by schuhschuh** [comment]
Thanks, that's definitely better. Got so accustomed to the FileSource for the not-yet-existent output files that I just used it all over the place. But the SelectFileDomain saves me an EmptyTask.

**Comment by schuhschuh** [comment]
Hm, what am I doing wrong, though ?
```scala
val srcIdSampling = CSVSampling(imgCsv) set(columns += ("ID", srcId))
val forEachIm     = ExplorationTask(srcIdSampling + (srcIm in SelectFileDomain(imgDir, imgPre + "${srcId}" + imgSuf)))
```
gives the following error
```
srcIdSampling: org.openmole.plugin.sampling.csv.CSVSamplingBuilder = org.openmole.plugin.sampling.csv.CSVSamplingBuilder@628fa8ea
<console>:145: error: type mismatch;
 found   : org.openmole.core.workflow.sampling.Factor[org.openmole.core.dsl.File,org.openmole.plugin.domain.file.SelectFileDomain]
    (which expands to)  org.openmole.core.workflow.sampling.Factor[java.io.File,org.openmole.plugin.domain.file.SelectFileDomain]
 required: String
       val forEachIm     = ExplorationTask(srcIdSampling + (srcIm in SelectFileDomain(imgDir, imgPre + "${srcId}" + imgSuf)))
```

**Comment by schuhschuh** [comment]
Got it, I needed to convert the CSVSampling using ```srcIdSampling.toSampling```.

**Comment by romainreuillon** [comment]
I just fixed it in the dev version.

**Comment by romainreuillon** [comment]
Last thing in your workflow you have no hooks, I think you'll need some to be able to gather the file produced by your executable and copy them on your system.

**Comment by schuhschuh** [comment]
> I just fixed it in the dev version.

 Meaning that the toSampling is now called implicitly I suppose. Perfect!

> Last thing in your workflow you have no hooks, I think you'll need some to be able to gather the file produced by your executable and copy them on your system.

That's true. I will see about this when I play with Glite grid environment. Otherwise I am running the tasks in our college environment (using SLURM or Condor) with shared directories between nodes. This saves me the extra copying of files and that's why I only use the ```File``` containers for the paths.

**Comment by schuhschuh** [comment]
I think I have another problem with my workflow. When I change the environment for the "if" task to SLURM, I get file not found errors before the job is even scheduled. Is it possible that OpenMOLE tries to automatically upload any file specified by the ```Val[File]``` inputs? Because what I have is an empty task which uses a ```FileSource``` to set the ```File``` variable to the path of the output file of the following task which should be submitted as SLURM job. Hence, it is expected that the file does not exist before the job even executed. Do I have to change from ```Val[File]``` to ```Val[String]``` and set the file path in a ScalaTask based on the other input variables ?

```
FINE: Error in job refresh
java.io.FileNotFoundException: /vol/medic01/users/as12312/Data/Registrations/MAC2012/dofs/rigid/mni305,1004.dof.gz (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at org.openmole.core.tools.io.HashUtil$.computeHash(HashUtil.scala:40)
        at org.openmole.core.fileservice.FileService$$anonfun$hash$1.apply(FileService.scala:55)
        at org.openmole.core.fileservice.FileService$$anonfun$hash$1.apply(FileService.scala:55)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
        at org.openmole.core.tools.cache.AssociativeCache$$anonfun$cacheMap$1$$anon$2.scala$collection$mutable$SynchronizedMap$$super$getOrElseUpdate(AssociativeCache.scala:46)
        at scala.collection.mutable.SynchronizedMap$class.getOrElseUpdate(SynchronizedMap.scala:40)
        at org.openmole.core.tools.cache.AssociativeCache$$anonfun$cacheMap$1$$anon$2.getOrElseUpdate(AssociativeCache.scala:46)
        at org.openmole.core.tools.cache.AssociativeCache.cache(AssociativeCache.scala:42)
        at org.openmole.core.fileservice.FileService$.hash(FileService.scala:52)
        at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1$$anonfun$1.apply(UploadActor.scala:71)
        at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1$$anonfun$1.apply(UploadActor.scala:71)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
        at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
        at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:154)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.immutable.TreeSet.scala$collection$SetLike$$super$map(TreeSet.scala:53)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.immutable.TreeSet.map(TreeSet.scala:53)
        at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1.apply(UploadActor.scala:71)
        at org.openmole.core.batch.refresh.UploadActor$$anonfun$org$openmole$core$batch$refresh$UploadActor$$initCommunication$1.apply(UploadActor.scala:61)
        at org.openmole.core.workspace.Workspace.withTmpFile(Workspace.scala:283)
        at org.openmole.core.workspace.Workspace$.withTmpFile(Workspace.scala:123)
        at org.openmole.core.batch.refresh.UploadActor.org$openmole$core$batch$refresh$UploadActor$$initCommunication(UploadActor.scala:61)
        at org.openmole.core.batch.refresh.UploadActor$$anonfun$receive$1$$anonfun$apply$2.applyOrElse(UploadActor.scala:50)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at org.openmole.core.batch.refresh.UploadActor.aroundReceive(UploadActor.scala:44)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
        at akka.dispatch.Mailbox.run(Mailbox.scala:221)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
