### ISSUE TITLE
Explore samples in reverse order

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#64]
I noticed that the ExplorationTask iterates the samples in reverse order. Would be nice if this could be changed, i.e., reverted again such that the following script:

```
val csvFile = new java.io.File(if (args.length > 0) args(0) else "Config/reg_f3d.csv")
val env = LocalEnvironment(1)

if (csvFile.exists) {
  csvFile.delete()
} else {
  val csvDir = csvFile.getParentFile
  if (csvDir != null) csvDir.mkdirs()
}

val i     = Val[Int]    // Index of parameter set
val ID    = Val[String] // ID of parameter set
val ds    = Val[Double] // Control point spacing
val be    = Val[Double] // Bending energy weight
val ln    = Val[Int]    // No. of resolution levels
val maxit = Val[Int]    // Maximum no. of iterations

val params = {
  (ds    in List(2.5)) x
  (be    in List(.0, .0001, .0005, .001, .005, .01, .05)) x
  (ln    in List(3, 4)) x
  (maxit in List(300, 500, 1000))
}

val sample = ExplorationTask(params zipWithIndex i) on env
val setID  = Capsule(ScalaTask("""val ID = f"${i + 1}%02d" """) set (inputs += i, outputs += ID), strainer = true) on env
val write  = AppendToCSVFileHook(csvFile, ID, ds, be, ln, maxit)
val exec   = (sample -< (setID hook write)).start.waitUntilEnded
```

produces a CSV file with ascending parameter set IDs instead of:
```
> cat Config/reg_f3d.csv 
ID,ds,be,ln,maxit
42,2.5,0.05,4,1000
41,2.5,0.05,4,500
40,2.5,0.05,4,300
39,2.5,0.05,3,1000
38,2.5,0.05,3,500
37,2.5,0.05,3,300
36,2.5,0.01,4,1000
35,2.5,0.01,4,500
34,2.5,0.01,4,300
33,2.5,0.01,3,1000
32,2.5,0.01,3,500
31,2.5,0.01,3,300
30,2.5,0.005,4,1000
29,2.5,0.005,4,500
28,2.5,0.005,4,300
27,2.5,0.005,3,1000
26,2.5,0.005,3,500
25,2.5,0.005,3,300
24,2.5,0.001,4,1000
23,2.5,0.001,4,500
22,2.5,0.001,4,300
21,2.5,0.001,3,1000
20,2.5,0.001,3,500
19,2.5,0.001,3,300
18,2.5,5.0E-4,4,1000
17,2.5,5.0E-4,4,500
16,2.5,5.0E-4,4,300
15,2.5,5.0E-4,3,1000
14,2.5,5.0E-4,3,500
13,2.5,5.0E-4,3,300
12,2.5,1.0E-4,4,1000
11,2.5,1.0E-4,4,500
10,2.5,1.0E-4,4,300
09,2.5,1.0E-4,3,1000
08,2.5,1.0E-4,3,500
07,2.5,1.0E-4,3,300
06,2.5,0.0,4,1000
05,2.5,0.0,4,500
04,2.5,0.0,4,300
03,2.5,0.0,3,1000
02,2.5,0.0,3,500
01,2.5,0.0,3,300
```

**Comment by romainreuillon** [comment]
Since OpenMOLE provides parallel computation no order of execution can be assumed.

**Comment by schuhschuh** [comment]
I am aware of this and wouldn't had come up with the request if it indeed were random. However, in this particular case of a single-threaded local execution (i.e., all tasks run on ```LocalEnvironment(1)```), the order of exploration is clearly deterministic. But for some reason, the sampling is iterated in reverse order. Why should the exploration not be in the more natural ascending order of the zipped index in such local single-threaded execution given that it it **is** indeed deterministic already? Not a big deal, though,...

**Comment by romainreuillon** [comment]
It is not caused by the sampling but by the job queue of the local environment being based on stacks for efficiency reasons (see the PriorityQueue class).

**Comment by schuhschuh** [comment]
Alright then, I thought it must be due to some reasons like this. I assume the order of priority could be reversed, though, using a FIFO instead. But feel free to close this issue and mark it as invalid/won't fix.

**Comment by schuhschuh** [comment]
(which I guess is a matter of whether the order of execution should be in a BFS or DFS manner)

**Comment by romainreuillon** [comment]
I think I found how to preserve the order in any case (mono-thread, multi-thread, remote...), I've commited it in 8b67ba2ef7ba3461c0b530e6a28ae77a25d9a57c.

**Comment by schuhschuh** [comment]
:) Nice!

**Comment by romainreuillon** [comment]
This ordering is ensured by the aggregation. Meaning that the order of execution as no meaning but the aggregated results match the submission order.

**Comment by schuhschuh** [comment]
Fair enough.

**Comment by schuhschuh** [comment]
For completeness, the initial goal can now be achieved by first aggregating the results before appending them to a CSV file using the AppendToCSVFileHook:

```scala
val sample = ExplorationTask(params zipWithIndex i)
val setID  = Capsule(ScalaTask("""val ID = f"${i + 1}%02d" """) set (inputs += i, outputs += ID), strainer = true)
val write  = Capsule(EmptyTask(), strainer = true) hook AppendToCSVFileHook(csvFile)
val exec   = (sample -< setID >- write).start.waitUntilEnded
```
