### ISSUE TITLE
ExecutionPanel.scala:42: exception during macro expansion

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#72]
Building the current HEAD of the master branch fails with the following error:
```
The referenced trait [[ExecutionInfo]] does not have any sub-classes. This may happen due to a limitation of scalac (SI-7046) given that the trait is not in the same package. If this is the case, the hierarchy may be defined using integer constants.
[error] /Users/as12312/Software/OpenMOLE/openmole/gui/client/org.openmole.gui.client.core/src/main/scala/org/openmole/gui/client/core/ExecutionPanel.scala:42: exception during macro expansion: 
[error] java.lang.AssertionError: assertion failed
[error]         at scala.Predef$.assert(Predef.scala:151)
[error]         at upickle.Macros$.macroRImpl(Macros.scala:32)
[error]     OMPost[Api].allExecutionStates.call().foreach { c ⇒
[error]
```

**Comment by mathieuleclaire** [comment]
Hi Andreas,
I cannot reproduce the bug (which is indeed the same reported by our jetkins building system). Rebuilding the whole project from scratch with a new empty user on my machine leads to a success !

**Comment by schuhschuh** [comment]
Hm, I can try again, but actually I've tried a clean build after removing all files build files from my system:
```
cd openmole/libraries
sbt clean clean-files
cd ../openmole
sbt clean clean-files
cd ..
sbt clean clean-files
rm -rf ~/.ivy2/cache/org.openmole*
rm -rf ~/.ivy2/local/org.openmole*
```

**Comment by mathieuleclaire** [comment]
Weird, but I can't do best than build the project from scratch with a different user. Did you try this ?

**Comment by mathieuleclaire** [comment]
Can you please give a shot (pulling my last commit) ?

**Comment by schuhschuh** [comment]
Sure I will. I just did above steps again and removed all build files and Ivy2 files. Building with this right now. Will then pull the changes and rebuild only.

**Comment by schuhschuh** [comment]
Unfortunately removing the ```@JSExport``` didn't help.

**Comment by romainreuillon** [comment]
It has been solved by removing this part from the API doc generation.
