### ISSUE TITLE
Multiple OpenMOLE batch scripts

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#8]
It could be useful if OpenMOLE batch scripts to be executed by the ```openmole -c``` REPL using option ```-s``` would support an [#include](https://github.com/dacr/bootstrap) statement to allow sharing code between independently executed workflows.

For starters, it might be sufficient to at least allow multiple batch scripts to be loaded by the openmole console as in:
```
openmole -c -s Common.scala -s Workflow1.scala
openmole -c -s Common.scala -s Workflow2.scala
```
or
```
openmole -c -s Common.scala -s SubMole1.scala -s SubMole2.scala -s Workflow.scala
```
where SubMole1.scala and SubMole2.scala define some pieces of the OpenMOLE puzzle which are later combined in Workflow.scala.

Alternatively, one could probably have the creation of the reusable components in Scala (package) object methods and compile these into a jar file. But then one has to "link" to the jar files in the ```plugins/``` and ```openmole-plugins/``` directories of the OpenMOLE installation. Writing an OpenMOLE plugin which imports other OpenMOLE core components and plugins might be another way of adding custom constructs.

These are a number of options and I am not clear of the best approach to make OpenMOLE batch scripts and sub-workflows re-usable.

**Comment by romainreuillon** [comment]
I just commited a patch. Now you can provide a list of scripts, and they will be executed sequentially:
-c script1 script2...

You may also want to use the ```:load``` command in your script that should behave like #include.

If you want to provide some workflow part in your plugin, it should depend from org.openmole.core.dsl. Then you can import this package and use the dsl. For functionalities provided by plugins you will need to depend / import each one you need. Tell me if you are interested in it I will deploy the last version of the plugins on our maven server and I can provide you with an example.

**Comment by schuhschuh** [comment]
Thanks! I am indeed keen on using the DSL within my plugin. I believe this would be the cleaner solution of implementing reusable workflow components plus these are compiled and thus I benefit from compile time type checks and the batch execution itself should be faster. Further, this would enable me to extend the DSL for my needs.

I tried just adding the OpenMOLE jar's as unmanaged dependencies, but that gave me problems when loading the plugin within OpenMOLE. I noticed that your Maven repositories at https://maven.openmole.org are rather outdated. If you can provide me with an example plugin which depends on some OpenMOLE types that would be really helpful.

**Comment by schuhschuh** [comment]
> You may also want to use the :load command in your script that should behave like #include.

Right! I actually found some information on this command, but didn't think further that I can just use it because OpenMOLE scripts are executed in a scala console (REPL).

**Comment by romainreuillon** [comment]
I've published up-to-date artefacts for OpenMOLE. To begin, you can now find a short example of an OpenMOLE plugin using OpenMOLE components here: https://github.com/openmole/myopenmoleplugin in the hellowf project.

**Comment by schuhschuh** [comment]
Works like a charm, thanks for this.
