### ISSUE TITLE
Display a goodbye page and hide shutdown url

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#84]
When leaving the WebUI by clicking the shutdown button, the page is refreshed and displays an error since the server is not running anymore.

Would be better to close the current tab when hitting the shutdown button.

**Comment by romainreuillon** [comment]
When clicking on shutdown the url is displayed in the current tab would it be possible to call the url in background after displaying a niche goodbye page?

**Comment by mathieuleclaire** [comment]
d608a123b2e6001eb28e283aebb3c760cdd8f7c5 implements this
