### ISSUE TITLE
confirmation before preference wipe out

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#86]
The current preference wipe out it a bit too easy and might cause manipulation error. Add a confirmation pannel.

**Comment by mathieuleclaire** [comment]
1b5638d6638d4c142a4b775e581e23e8a2d0db1b fix it

**Comment by romainreuillon** [comment]
Perfect!

It would be good to trigger this confirmation for the link in the authentication panel as well, wouldn't it ?
