### ISSUE TITLE
Make deletion less error prone

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#88]
It happened twice that I removed a folder by mistake :(. Now that I am working on real dev in the editor it frightens me. To make the deletion less error prone I propose to add a garbage mechanism. The deletion on any folder or file would move it to the garbage. The deletion action on the garbage would empty it.

What do you think about that?

**Comment by romainreuillon** [comment]
After putting some thoughts into that, may be the trash is not the best option. I was thinking that it was easy to implement but actually it would require to find a way to store the restore path and to deal with duplicate file names....

How hard would it be to implement a confirmation for the delete action?

**Comment by mathieuleclaire** [comment]
I think that the message makes sense, I will implement it.

**Comment by jopasserat** [comment]
Or something a la capitainetrain when you can cancel deletion of a ticket, a timer starts and you can cancel deletion within the next 10 seconds. I'm sure you've seen that already @mathieuleclaire ;)

**Comment by mathieuleclaire** [comment]
I did yes, it's a good idea.

**Comment by mathieuleclaire** [comment]
a90fab3bb233d61c97c53f319f722604372eaec4 fixes it

**Comment by romainreuillon** [comment]
Great, the solution is very elegant.

**Comment by jopasserat** [comment]
neat!
