### ISSUE TITLE
Folder with many files make the GUI unusable

### ISSUE THREAD

**Issue by romainreuillon** [openmole/openmole#91]
When opening a folder with many files (5000+) the GUI become barely usable.

**Comment by romainreuillon** [comment]
For info some users got bitten by that in 5.4, this should be very high priority since it impacts the scalability of OpenMOLE.

**Comment by mathieuleclaire** [comment]
A filter with 20 files by default has been implemented: e902e558f181116def44e8ca5ec935ea573e0cad
