### ISSUE TITLE
Preferences are stored in different folders on Mac...

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#92]
MacOS seems to change the hostname depending on the network the machine is connected to.

As a result, the OpenMOLE preferences end up being stored in different locations, depending on the network/IP.

There might be another more reliable to figure a machine's name when storing the preferences.

**Comment by jopasserat** [comment]
This actually solves it: http://superuser.com/a/50104/285945

Not sure whether we should fix that in the source code or mention the trick in the documentation.

**Comment by mathieuleclaire** [comment]
It fixes the bug, but it is not acceptable to oblige the user to set a 
machine name before using openmole.
We have to investigate to the necessity to use the machine name in 
openmole settings path.
Le 10/08/2015 15:31, jopasserat a écrit :
>
> This actually solves it: http://superuser.com/a/50104/285945
>
> Not sure whether we should fix that in the source code or mention the 
> trick in the documentation.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openmole/openmole/issues/92#issuecomment-129454948>.
>


-- 
Be green, keep it on the screen
Faites bonne impression et imprimez seulement au besoin!

**Comment by romainreuillon** [comment]
What about not using the machine name when OpenMOLE detects it runs on mac?

**Comment by mathieuleclaire** [comment]
And, what using instead ?
Le 10/08/2015 21:05, Romain Reuillon a écrit :
>
> What about not using the machine name when OpenMOLE detects it runs on 
> mac?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openmole/openmole/issues/92#issuecomment-129568096>.
>


-- 
Be green, keep it on the screen
Faites bonne impression et imprimez seulement au besoin!

**Comment by mathieuleclaire** [comment]
And, what should we use instead ?
Le 10/08/2015 21:05, Romain Reuillon a écrit :
>
> What about not using the machine name when OpenMOLE detects it runs on 
> mac?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openmole/openmole/issues/92#issuecomment-129568096>.
>


-- 
Be green, keep it on the screen
Faites bonne impression et imprimez seulement au besoin!

**Comment by romainreuillon** [comment]
Either nothing or "localhost".

**Comment by mathieuleclaire** [comment]
But, a conflict could happen in case of shared folder, on a cluster for 
instance.
Le 10/08/2015 22:22, Romain Reuillon a écrit :
>
> Either nothing or "localhost".
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openmole/openmole/issues/92#issuecomment-129595067>.
>


-- 
Be green, keep it on the screen
Faites bonne impression et imprimez seulement au besoin!

**Comment by romainreuillon** [comment]
Anyway if we cannot determine a machine id reliably, the feature is pointless. What would be a suitable machine id for mac systems?

**Comment by jopasserat** [comment]
I'm sure there's a way to query the owner's bank account number...

**Comment by schuhschuh** [comment]
What about using the system serial number: https://developer.apple.com/library/mac/technotes/tn1103/_index.html

http://apple.stackexchange.com/questions/40243/how-can-i-find-the-serial-number-on-a-mac-programmatically-from-the-terminal

**Comment by romainreuillon** [comment]
I have no mac to test such a fix, so I just disabled host base preference folder for macs. If a dev with a mac gets motivated to make it work and test it I would be glad to accept a patch :)

Fixed in fb0e82e905d778392307094f16f1f346365f71e9
